### ISSUE TITLE
Ability to specify (or not) sideloads

### ISSUE THREAD

**Issue by jgillmanjr** [facetoe/zenpy#103]
Commit [d0ecb8a](https://github.com/facetoe/zenpy/commit/d0ecb8a35da39fcc5c9cfc6dd6f6e5146ce6d193) actually broke some stuff that I had already written (which wasn't expecting some stuff that comes in as a result of sideloading comment data).

I think that the incremental endpoints should allow the option of using sideloads or not.

The approach that I tried didn't seem to work, and I'm not sure the best way (if possible) to add this functionality without a significant refactor.

**Comment by facetoe** [comment]
Out of interest, how did the addition of sideloads break what you had already? I thought that change would be pretty safe. 

I agree it would be nice to be able to specify (or override) sideloads for each endpoint. I'm happy to have a look at adding this functionality when I get the chance.

**Comment by jgillmanjr** [comment]
Admittedly, part of it was my fault. I was deving against my fork prior to the cherry pick of my last pull request.

When I ended up changing back to upstream (your repo), I apparently didn't notice the sideload change. Ultimately though not a huge deal though - my stuff isn't in production yet and now that the comment sideload is available, I can revert to my original plan of storing the comment data.

**Comment by facetoe** [comment]
OK cool, I was worried I might have broken other peoples code as well! 

With any luck it won't be too tricky to expose the sideload functionality for all the endpoints where it is applicable but it's definitely worth doing, just need to find the time!

**Comment by facetoe** [comment]
Hi @jgillmanjr, I've added the ability to add or remove sideloads. There are three new methods per API: `get_sideloads`, `append_sideload` and `remove_sideload`. For example, to add the `comment_events` you could do the following:

```python
zenpy_client.tickets.append_sideload('comment_events', method_name='incremental')
```

**Comment by jgillmanjr** [comment]
@facetoe Excellent!

My script has pretty much been humming along quite nicely, but this will be nice for future work.
