### ISSUE TITLE
Ticket merging?

### ISSUE THREAD

**Issue by sjtarik** [facetoe/zenpy#104]
Is ticket merging on the roadmap?

**Comment by facetoe** [comment]
Can you point me to the docs for this?

**Comment by facetoe** [comment]
All good - https://developer.zendesk.com/rest_api/docs/core/tickets#merge-tickets-into-target-ticket. 

Yes I'll implement this when I get a chance.

**Comment by sjtarik** [comment]
Thanks @facetoe. Is there a timeline for next update to PyPi?

**Comment by facetoe** [comment]
Hi @sjtarik, there isn't a timeline as yet, it's really when I get the chance to implement it. With any luck I'll get to it this weekend and then push a new version to PyPi.

**Comment by sjtarik** [comment]
Thanks @facetoe for great library. Keep it coming 👍

**Comment by facetoe** [comment]
Hi @sjtarik, I've added support for merging tickets to master. I've got some more changes coming and will push a new release to PyPi in the next week or so.

**Comment by sjtarik** [comment]
happy I can get rid of requests calls just for merging tickets. thanks @facetoe for implementation 👍

**Comment by facetoe** [comment]
No worries!
