### ISSUE TITLE
Unable to update a ticket's subject

### ISSUE THREAD

**Issue by skrud** [facetoe/zenpy#105]
When updating a ticket that already exists in Zendesk, I'm unable to alter the `subject` field. There is a `ChangeEvent` in the corresponding `TicketAudit` object, but it looks like it's empty / nothing has changed.

### Steps to Reproduce ###
1. Create a ticket in Zendesk
2. Fetch the ticket using `zenpy.tickets(id=...)`
3. Update the ticket's subject property
4. Use `zenpy.tickets.update()` to update the ticket

### Expected Behavior ###
The ticket's subject line is updated to the new value.

### Actual Behavior ###
The ticket's subject line remains the same.

### Code Snippet ###
Below is a code snippet from the REPL that demonstrates this behavior.
```
>>> import zenpy
>>> from zenpy.lib.api_objects import Ticket, Comment
>>> zenpy = Zenpy(**creds)
2017-03-03 14:23:13,595 [MainThread  ] [DEBUG   ]  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None)
>>> t = Ticket(subject='This is a new ticket', comment=Comment(public=False, body='Some stuff for the comment'))
>>> ta = zenpy.tickets.create(t)
2017-03-03 14:23:53,763 [MainThread  ] [INFO    ]  Starting new HTTPS connection (1): ******.zendesk.com
2017-03-03 14:23:54,372 [MainThread  ] [DEBUG   ]  "POST /api/v2/tickets.json HTTP/1.1" 201 2713
>>> ta.ticket
[Ticket(id=70885)]
>>> ta.ticket.subject
u'This is a new ticket'
>>> orig_ticket = zenpy.tickets(id=70885)
>>> orig_ticket
[Ticket(id=70885)]
>>> orig_ticket.subject = 'A new subject'
>>> orig_ticket.subject
'A new subject'
>>> ta = zenpy.tickets.update(orig_ticket)
2017-03-03 14:24:43,470 [MainThread  ] [DEBUG   ]  "PUT /api/v2/tickets/70885.json HTTP/1.1" 200 None
>>> ta.ticket
[Ticket(id=70885)]
>>> ta.ticket.subject
u'This is a new ticket'
>>> change_event = next(ta.audit.events)
>>> change_event
[ChangeEvent(id=183260526723)]
>>> change_event.field_name
u'22768179'
>>> change_event.previous_value
>>> change_event.to_dict()
{'type': u'Change', 'field_name': u'22768179', 'id': 183260526723, 'value': u'0'}
```

**Comment by facetoe** [comment]
Hey @skrud, thanks for the report. This looks to be a bug or quirk in the Zendesk API itself. After messing around a bit I've found that the following updates the ticket subject as you would expect:

```python
zenpy_client = Zenpy(**creds)
ta = zenpy_client.tickets.create(Ticket(subject="The subject", description="description"))

new_ticket = ta.ticket

print new_ticket.subject
new_ticket.raw_subject = "I am the new subject"
new_ticket.subject = "I am the new subject"

ta = zenpy_client.tickets.update(new_ticket)
updated_ticket = ta.ticket
print updated_ticket.subject
``` 

Alternatively, if you know the `id` this also works:

```python
zenpy_client.tickets.update(Ticket(id=2, subject='A new subject for the ticket'))
```

I will raise an issue with Zendesk so they can have a look.

**Comment by facetoe** [comment]
I've created an issue with Zendesk. After investigating this a little more I've found that the subject is updated if A) both "subject" and "raw_subject" are set to the same value or B) either "subject" or "raw_subject" are not submitted to the API. Therefore as a workaround you can just set one of them to `None` before calling `update`.

**Comment by facetoe** [comment]
OK I figured this out, whenever there is a conflict between the values of `subject` and `raw_subject` Zendesk chooses whatever is in `raw_subject`. If you want to change the subject of a ticket it is enough to only change `raw_subject`
