### ISSUE TITLE
Any way to inspect request? Could I visualize the progress of a long running operation?

### ISSUE THREAD

**Issue by joelhellman** [facetoe/zenpy#108]
I'm using the `users.incremental export` to dump data from my Zendesk, and the resulting request can run for a long time before completing, as there is much data to paginate through. 

Is there any way to see the progress of such long running requests?

Also, is there a way to see which details on the network requests being sent and the response from Zendesk API?

The docs mention there is a way to provide your own session method, and there seems to be a debug parameter you can supply at that point, but I'm new to python, and not sure if this would help me here.

**Comment by facetoe** [comment]
Hi @joelhellman, yes you can see additional information if you enable debug logging. Just place the following in your script:

```python
log = logging.getLogger()
log.setLevel(logging.DEBUG)
ch = logging.StreamHandler(sys.stdout)
formatter = logging.Formatter('%(levelname)s - %(message)s')
ch.setFormatter(formatter)
log.addHandler(ch)
logging.getLogger("requests").setLevel(logging.WARNING)
```

You can change the `requests` log level to INFO/DEBUG if you want to see the messages generated by `requests` as well. 

Hope this helps!
