### ISSUE TITLE
Support filters in user primaryendpoint

### ISSUE THREAD

**Issue by wontonst** [facetoe/zenpy#111]
https://developer.zendesk.com/rest_api/docs/core/users#filters

If I run 

`for user in client.users(role='admin')`

it doesn't apply the role filter. After digging around, I think this wrapper does not support filtering. Patch incoming.

**Comment by facetoe** [comment]
Thanks for the PR! I'm going to leave this open so I remember to add this info to the docs.

**Comment by wontonst** [comment]
I added a line of documentation in #113 and also did a similar thing for the permission_set filter

**Comment by facetoe** [comment]
Awesome, thanks.
