### ISSUE TITLE
Issue with updating fields and commenting at the same time

### ISSUE THREAD

**Issue by sjtarik** [facetoe/zenpy#114]
Following code used to work but I am no longer able to execute it successfully receiving the following error:

```
                    ticket.comment = Comment(body="long comment sentence",
                                             public=True)
                    ticket.type = "incident"
                    ticket.status = "solved"
                    self.client.tickets.update(ticket)
```
```

{
  "details": {
    "base": [
      {
        "ticket_field_type": "FieldTagger",
        "ticket_field_id": 12345657,
        "description": "Type:: is required when solving a ticket",
        "error": null
      }
    ]
  },
  "description": "Record validation errors",
  "error": "RecordInvalid"
}
```

**Comment by facetoe** [comment]
The above code still works for me. Do you have custom ticket fields?

**Comment by sjtarik** [comment]
Ticket does not have custom ticket fields. It does not have a type field, so while closing I want to set the type as "incident" and close it but still receive the error "Type:: is required when solving a ticket".

**Comment by facetoe** [comment]
When I execute the above code it correctly sets the type to "incident" and closes the ticket. From the error output you have posted it looks like you have a ticket field set to required and that is throwing the error (or something like that). It is difficult for me to troubleshoot this issue as I do not know how your Zendesk is configured. 

You should be able to get more information about this field by executing the following:

```python
ticket_field = zenpy_client.ticket_fields(id=12345657)
print json.dumps(ticket_field.to_dict(), indent=2)
```
If this does not shed some light on the issue, please let me know when the error began to appear. Also, did it begin after upgrading Zenpy?

**Comment by sjtarik** [comment]
Hi @facetoe , it is in fact a custom field using exact same name "Type" which made me thought zenpy not setting the type field successfully. Thanks for your time and help.

**Comment by facetoe** [comment]
No worries!
