### ISSUE TITLE
Support identities?

### ISSUE THREAD

**Issue by sovietnorm** [facetoe/zenpy#115]
Pretty please?

I have an organisation that did dumb things with their phone number formatting on an import. 
It's fixable, buuuuut I'm lazy and zenpy is so nice that I don't want to use another python API client that can manipulate identities to do it.

I might also be misunderstanding how to manipulate identities, I see there's some reference to it that I don't fully understand in the users primary endpoint. But I can't find any other reference to it in the docs.

Anyhow, it's great! Keep up the great work!

**Comment by facetoe** [comment]
Hi @sovietnorm, are you talking about User Identities - https://developer.zendesk.com/rest_api/docs/core/user_identities?

**Comment by sovietnorm** [comment]
Yes, if possible.

It would make really easy work out of correcting systemically fudged contact information on several thousand records.

**Comment by facetoe** [comment]
Yep, no problem, shouldn't be hard to implement. With any luck I'll get to it next week!

**Comment by sovietnorm** [comment]
Awesome. Just, awesome.

**Comment by facetoe** [comment]
Hi @sovietnorm, I've added support for identities. I'll need to update the docs but for now you can use the new functionality as follows:

```python
# Show identities for a user
for identity in zenpy_client.users.identities(id=21207616708):
    print(identity.id, identity.value, identity.verified, identity.primary)

# Create a new identity for a user
identity = zenpy_client.users.identities.create(
    user=21207616708,
    identity=Identity(type='email', value='example4@example.com')
)

# Update an identity
identity = zenpy_client.users.identities.update(
    user=21207616708,
    identity=Identity(id=identity.id, value='foo@barbaz.com')
)

user_id_or_object = 21207616708
identity_id_or_object = 6765149327

# Send email requesting verification
response = zenpy_client.users.identities.request_verification(
    user=user_id_or_object,
    identity=identity_id_or_object
)
print("request verification response: {}".format(response))

# Verify an identity
identity = zenpy_client.users.identities.verify(
    user=user_id_or_object,
    identity=identity_id_or_object
)
print("verified: {}".format(identity.verified))

# Make an identity the users primary identity
user_identities = zenpy_client.users.identities.make_primary(
    user=user_id_or_object,
    identity=identity_id_or_object
)
for identity in user_identities:
    print(identity.to_dict())

# Show a particular identity for a user
identity = zenpy_client.users.identities.show(
    user=user_id_or_object,
    identity=identity_id_or_object
)
print(identity)

# Delete an identity for a user
response = zenpy_client.users.identities.delete(
    user=user_id_or_object,
    identity=identity_id_or_object
)
print("Delete response: {}".format(response))
```

**Comment by oodzee** [comment]
Hi @facetoe, 

When trying to update a user identity, I got the following error message: 
`{"error": {"message": "You passed an invalid value for the identity attribute. Invalid parameter: identity must be a hash", "title": "Invalid attribute"}}`

The code I'm using to update the identity is:
`zenpy_client.users.identities.update(
            user=user.id,
            identity=Identity(id=identity_to_update.id, value="test_zendesk@gmail.com")
          )`

Is there something I'm missing?

Thanks!

**Comment by facetoe** [comment]
Hi @oodzee, thanks for the report, this is a bug. Patch incoming.

**Comment by facetoe** [comment]
I've got some more changes coming but I'll push an update to PyPi hopefully within the week.
