### ISSUE TITLE
Incremental ticket event - comment_events sideloading

### ISSUE THREAD

**Issue by snexus** [facetoe/zenpy#119]
Hi,
Thanks for this great wrapper.

Is it possible to add  comment_events side loading for the incremental ticket event? This way comment events could be fetched in bulk via incremental API.

Seems it is supported via API, but not in Zenpy:  https://developer.zendesk.com/rest_api/docs/core/incremental_export#incremental-ticket-event-export

Thank you!

**Comment by facetoe** [comment]
Yep, not a problem. I'll try to get to this tomorrow.

**Comment by facetoe** [comment]
Hi @snexus, I've updated the incremental endpoint to sideload comment_events.

**Comment by facetoe** [comment]
BTW @snexus, I've added the ability to add or remove sideloads in 5084478ced6aff886cb50643f96b62578489bcbf.

**Comment by snexus** [comment]
Hi @facetoe, thank you, much appreciated!
Btw, do you plan to add a basic contribution guide so we won't bother you with minor requests?
Thanks again.

**Comment by facetoe** [comment]
Yep, I still do plan on writing it. I've been doing a major refactor over the last week or so cleaning up the code and making it (hopefully) a bit easier to grok. Once that's done I'll write a guide and a tutorial showing how to implement a new api endpoint.

**Comment by facetoe** [comment]
Hi @snexus, I wrote a bit of a contributors guide here - https://github.com/facetoe/zenpy/wiki/Contributors-Guide. If you have any suggestions or questions let me know!

**Comment by aharrison7** [comment]
I see that include_comments is supported in tickets.incremental - I'm getting an error on tickets.events (also incremental)

 tickets.events = IncrementalEndpoint('incremental/ticket_events.json')

return zenpy_client.tickets.events(start_time=starttime_begin, include=['comment_events'])
TypeError: events() got an unexpected keyword argument 'include'

Does the tickets.events incremental endpoint not yet support sideloading (just the standard incremental)?

**Comment by facetoe** [comment]
Yep, that would most likely do it.

**Comment by ztweed** [comment]
Hi!
This is an old thread, but would someone mind providing an example of how to add comment_events sideloading for an incremental ticket event query? 

For context, I am attempting to pull say, all open tickets and their comments in a single query. After some digging, I don't think this is directly possible but that this method will be my closest approximation. If I am wrong, however, feel free to point me in the right direction!

**Comment by facetoe** [comment]
You can sideload comment_events as follows:

```python
for ticket in zenpy_client.tickets.events(start_time=0, include=['comment_events']):
    print(ticket.child_events)
```
