### ISSUE TITLE
Docs for latest version reference views however object does not have this attribute

### ISSUE THREAD

**Issue by arontx** [facetoe/zenpy#127]
Documentation for 1.1.12 lists support for views however attempting to use it results in AttributeError

```
Traceback (most recent call last):
  File "tsg/core/Zendesk.py", line 186, in <module>
    main()
  File "tsg/core/Zendesk.py", line 170, in main
    print('views: %s' % zd.views)
AttributeError: 'Zendesk' object has no attribute 'views'
```

Not sure if the documentation is ahead of 1.1.12 or if this an issue with the release.

In the event that the documentation is "ahead" is there any eta on when the next release would include views support? I'd love to use zenpy but I can't clone from git for production servers -- needs to come from pypi.

**Comment by facetoe** [comment]
Yes the docs are for what is on master. I'll try to push a new version tonight.

**Comment by facetoe** [comment]
Hi @arontx, I've pushed a new version to PyPi.
