### ISSUE TITLE
Chat basic authentication

### ISSUE THREAD

**Issue by jhrs21** [facetoe/zenpy#128]
Hello @facetoe 

I am trying to test your Chat integration and I have two doubts.

1) Does it support basic authentication with Zopim? I mean, I am creating the Zenpy object with an `email` and `password`. But it requires a subdomain that for Zopim I think it doesn't exist. Is this right?

2) Do you have an example what kind of parameters search method needs? I am passing a dictionary `{'started_by': start_time}`

Thank you! :)

**Comment by facetoe** [comment]
Yes a subdomain is still required by the Zenpy constructor but you're right that it is not used. I'll fix that up as it is a bit confusing.  

Basic authentication works on many endpoints however according to zopim it is deprecated (although as far as I know this is not mentioned in the docs, they told me this in a support ticket). I'd suggest trying oauth2 if you are having issues.

You should be able to pass any of the paramaters in the documentation as keyword arguments to the search method.

Hope this helps!

**Comment by facetoe** [comment]
Hi @jhrs21, you no longer need to pass a subdomain if you are only using the chat endpoints.
