### ISSUE TITLE
Is it possible can we add a custom filed in organization using zenpy?

### ISSUE THREAD

**Issue by jishnunand** [facetoe/zenpy#129]
Hi Team,

I have a requirement to add a value to custom field dropdown in the organization table. Also, I want to know is it possible can we do a search in Organization table custom field directly?
Ex: I have created a custom field in Organization called "employee id". I want to do a search directly to "employee id" field.

Currently, I am doing this by going through all companies and checking for that employee id matches or not

`zd_organization_list = zenpy_connect.organizations()
    for each_organization in zd_organization_list:
        for each_zendesk_update_record in zendesk_update_record:
            for key, value in each_zendesk_update_record.items():
                if each_organization._organization_fields["employee_id"] == key \
                        or each_organization._organization_fields["employee_id"] == key[:-3]:
..................................
.....................................`

Please help me with this.

@dym @jpulec @facetoe @wontonst @jgillmanjr

**Comment by facetoe** [comment]
You can update the an organizational field as follows:

```python
some_organization = zenpy_client.organizations(id=16984851547)
some_organization.organization_fields.employee_id = 12345
zenpy_client.organizations.update(some_organization)
```

I'm not sure if it is possible to search the organizaional field directly. Your best bet is to refer to the Zendesk search documentation to see if it is possible.

**Comment by jishnunand** [comment]
@facetoe Thanks for the Update. I have one more use case in this. Is it possible can we add a custom dropdown field using this?

**Comment by facetoe** [comment]
No creating organizational fields is not currently supported. It would not be hard to implement, I just won't have to time to do it for a while.
