### ISSUE TITLE
SearchResultGenerator AttributeError

### ISSUE THREAD

**Issue by JacobSMoller** [facetoe/zenpy#130]
Hi trying to make a search for a user doing like so: 
user = next(zenpy.search(type='user', external_id=110101))
But it throws 
Throws: AttributeError: 'Api' object has no attribute 'deserializer'
from line https://github.com/facetoe/zenpy/blob/master/zenpy/lib/generator.py#L110 

Might just be my tired brain that is missing something trivial,  but can't see why i shouldn't be able to use next on the search result generator.

**Comment by facetoe** [comment]
Yep, this is a bug. I'll patch this and push a new version to PyPi.

Thanks for the report!

**Comment by facetoe** [comment]
Ok I've pushed a new version. If you update and try again it should work as expected.

**Comment by JacobSMoller** [comment]
Yes works as expected. Thanks for the quick fix. Its a lovely wrapper for
the zendesk API.

**Comment by facetoe** [comment]
No worries!
