### ISSUE TITLE
Reading from Custom Field (Documentation Requested)

### ISSUE THREAD

**Issue by cdmerritt** [facetoe/zenpy#132]
I'm trying to pull data from custom fields, but can't seem to find an example.  Lots of examples to modify a custom field, but none of just pulling info from a custom field.  Any help would be most appreciated.  Thanks for all your work on this project!

bulk_tickets = zenpy_client.tickets.incremental(start_time=start_date)
for ticket in bulk_tickets:
     t_id = ticket.id
     ticket_int_status = ticket.custom_fields(CustomField(id=21120677))
     print(ticket_int_status)

**Comment by facetoe** [comment]
Hi @cdmerritt, when you retrieve your tickets from Zendesk the `custom_fields` list should be populated with dictionaries representing your custom fields. You can read the values as follows (assuming a field id of 79177827):

```python
for ticket in zenpy_client.tickets.incremental(start_time=start_date):
    for field in ticket.custom_fields:
        if field['id'] == 79177827:
            print(field['value'])
```

Hope this helps!

**Comment by cdmerritt** [comment]
Perfect!  Thanks for the fast response!

**Comment by tacobeard** [comment]
Greetings, and thank you for creating this wrapper!  The above loop works great for outputting a single custom field value, but how might I produce output for multiple custom fields?  I'd like the values from the multiple fields to be next to each other.  Below is a sample of the output I'm aiming for, along with code that doesn't work.  Thanks again for all your hard work on this project!

```python
for ticket in zenpy_client.tickets.incremental(start_time=start_date):
    for field in ticket.custom_fields:
        if field['id'] == 1 and == 2 and == 3:
            print(field['value'])

>>>value1a value2a value3a
>>>value1b value2b value3b
>>>value1c value2c value3c

**Comment by facetoe** [comment]
This isn't really a question about the wrapper, more a general programming question, but you have a fantastic name @tacobeard :)

You could use a dictionary comprehension: 

```python
for ticket in zenpy_client.tickets.incremental(start_time=start_date):
    print("%(1)s %(2)s %(3)s" % {f['id']: f['value'] for f in ticket.custom_fields})
```
Alternatively, if you could do something like this if you don't know the ids:

```python
for ticket in zenpy_client.tickets.incremental(start_time=start_date):
    print(" ".join((f['value'] for f in ticket.custom_fields)))
```
Hope this helps!

**Comment by tacobeard** [comment]
Thanks for the prompt response, and the compliment on my name :)  Yours is similarly great!

I'm having trouble getting either one of the above suggested scripts to work.  I know the custom field IDs that I need, so I input them as follows:
```python
yesterday = datetime.datetime.now() - datetime.timedelta(days=1)
result_generator = zenpy_client.tickets.incremental(start_time=yesterday)

for ticket in result_generator:
    print("%(29655218)s %(22917550)s %(43800168)s" % {f['id']: f['value'] for f in ticket.custom_fields})
```    

I get the following error:
```python
KeyError: '29655218'
```
I tried switching around the keys but  to no avail.  Again, I know for a fact those custom field IDs are correct, and should be populated in numerous tickets falling under my specified time frame.

The other method you suggested I'm sadly having trouble with as well:
```python
for ticket in result_generator:
    print(str(" ".join((f['value'] for f in ticket.custom_fields))))
```
I get the following error:
```python
TypeError: sequence item 5: expected str instance, NoneType found
```
Any assistance would be greatly appreciated.  Thank you so much!

**Comment by facetoe** [comment]
With the first error, it appears that not all your tickets have the `29655218` custom field id. If you print the ticket ids as you go along you should be able to confirm this theory.

**Comment by tacobeard** [comment]
Thanks for responding, I was able to get a solid output (my script is designed to output SQL insert statements) using the following code:
```python
import zenpy, datetime, zdcreds, pytz

zenpy_client = zenpy.Zenpy(**zdcreds.creds)

yesterday = datetime.datetime.now(pytz.utc) - datetime.timedelta(days=1)
result_generator = zenpy_client.tickets.incremental(start_time=yesterday)

custom = ''
data = ''
for ticket in result_generator:
    for field in ticket.custom_fields:
        if ((field['id'] == 29655218) or (field['id'] == 22917550) or (field['id'] == 43800168)):
            custom = custom+'\"'+str(field['value'])+'\", '
    data = data+'('+custom+'\"'+str(ticket.id)+'\", \"'+str(ticket.tags)+'\", \"'+str(ticket.group_id)+'\", '+'STR_TO_DATE(\''+str(ticket.created_at)+'\', \'%Y-%m-%dT%H:%i:%sZ\')'+', '+'STR_TO_DATE(\''+str(ticket.updated_at)+'\', \'%Y-%m-%dT%H:%i:%sZ\')),'+'\n'
    custom = ''
data = data[:-2]
```
If you can't tell I'm kinda fumbling my way through learning Python by largely utilizing your repository and a few others, so thank you so much for your all of the help and kindness :)

**Comment by facetoe** [comment]
No worries, glad you got it working!
