### ISSUE TITLE
Get All the tickets from a certain view

### ISSUE THREAD

**Issue by bighelmet7** [facetoe/zenpy#133]
Hi! I'm trying to get all the tickets from a particular view, here is part of my code:

    def get(self, view_id):
		creds['token'] = users[auth.username()]
		zenpy_client = Zenpy(**creds)
		tickets = zenpy_client.views.tickets(int(view_id))
		payload = {
			"tickets" : []
		}
		for ticket in tickets:
			aux = {"id": ticket.id,"subject": ticket.subject}
			payload["tickets"].append(aux)
		return payload

And the problem is, this single view has got 103 tickets, but zenpy_client.views.tickets(int(view_id)), only gave me exactly 100 (It got sense because in Zendesk Api Core, there's a maximum of 100 tickets by Get a list of tickets).

How can I get all the tickets?

**Comment by facetoe** [comment]
Hmm, Zenpy is supposed to return a generator in this case, might be a bug. I'll have a look tonight. Thanks for the report!

**Comment by bighelmet7** [comment]
Hi @facetoe, thx a lot for your support and this amazing wrapper. Do you know something more about this bug?

**Comment by facetoe** [comment]
Hi @bighelmet7, yes turns out it wasn't correctly returning a result generator. I've pushed a fix and it should work as expected now.

I'll push a new version to PyPi sometime this week.

**Comment by facetoe** [comment]
Hi @bighelmet7, I've pushed a new version to PyPi.

**Comment by bighelmet7** [comment]
Hi @facetoe thx a lot for all your effort and help! is there any place where I can contribute?

**Comment by facetoe** [comment]
No worries! As for contributing, most definitely! There are three main areas:

1) Implementing sections of the Zendesk API that are not yet supported.

2) Writing tests (or coming up with a testing strategy even). I'm not very good at testing and have implemented a few strange tests, however the vast majority of the wrapper is untested.

3) Figuring out a new way to generate documentation from the source code. In the early days I wrote some code for Sphinx to generate docs (https://github.com/facetoe/zenpy/blob/master/docs/api_doc_gen.py). This worked well until the wrapper's structure changed and now it doesn't really work anymore. The main problem is that there are a lot of nested callable classes and I'm not sure of the best way to present this. For example, with the ChatApi, you have a callable class that contains other callable classes as attributes, so you can do things like: `zenpy_client.chats()` or `zenpy_client.chats.agents()`, or `zenpy_client.chats.agents.me()`. Another example is the `UserApi` which contains the `UserIdentityApi` in the `identitites` attribute. I'm sure it's possible to present all this nicely with Sphinx (or another tool) but I haven't figured it out yet.

If any of that strikes your interest, awesome! I'm happy to answer any questions you might have about the wraper, docs, tests etc :)

**Comment by facetoe** [comment]
It just occured to me that you might have meant contribute monetarily. If that's the case, no, but I might add a bitcoin address in the future.

Let me know if you have any more trouble with Zenpy!

**Comment by bighelmet7** [comment]
Hi! @facetoe haha it was both, for contribute in this project and monetily! 

Thx for all your effort!  <3

Of course I will let you know if have more trouble, at least I've one with the views hehe but I guess is a subprocess problem of my machine.

**Comment by bighelmet7** [comment]
@facetoe Why when I'm trying to iterate over a all the tickets in a certain view, in some point I get this exception: ("bad handshake: SysCallError(104, 'ECONNRESET')",)
I fixed with a

    from time import sleep as SLEEP
    While True:
        [code] ... [/code]
        zenpy.tickets.update(ticket)
        SLEEP(2)

But in the view are like 17k tickets, and in some point I get another time the same exception, i fixed with SLEEP(5), but once again I get the exception, do you know how I could fix this?

**Comment by facetoe** [comment]
`ECONNRESET` means the remote end is closing the connection on you, so you are probably hammering the Zendesk servers. Without seeing the code or having a bit more info on what you are trying to achieve I can't help much.

**Comment by bighelmet7** [comment]
Here's my code:

    #!/usr/bin/python
    # -*- coding: utf8 -*-
    from dateutil import parser
    from zenpy import Zenpy
    from datetime import datetime
    from datetime import timedelta
    from datetime import date
    from time import sleep as SLEEP
    import time

    #[00:00 - 6:59]
    def morning_limit(t):
	    return (t.hour <= 6 and t.minute <= 59)

    #[22:01 - 23:59]
    def night_limit(t):
	    return (t.hour >= 22 and t.minute > 0)

    def adjust_time(t, requester):
	    if morning_limit(t):
		    if not requester:
			    t = t.replace(hour=7)
		    else:
			    t = t.replace(hour=7, minute=0)
	    if night_limit(t):
		    #escriben en el rango [22:01 - 23:59]
		    #se cambia al dia siguiente indepen.
		    #si es Lunes - Domingo
		    try:
			    if not requester:
				    t = t.replace(day=t.day + 1,
					    hour=7)
			    else:
				    t = t.replace(day=t.day + 1,
					    hour=7, minute=0)
		    except Exception as e:
			    if not requester:
				    try:
					    t = t.replace(day=1,
						    hour=7)
					    t = t.replace(month=t.month + 1, 
						    hour=7)
				    except Exception as e:
					    t = t.replace(year=t.year+1)
					    t = t.replace(day=1,
						    hour=7)
					    t = t.replace(month=1, 
						    hour=7)
			    else:
				    try:
					    t = t.replace(day=1)
					    t = t.replace(month=t.month + 1, 
						    hour=7, minute=0)
				    except Exception as e:
					    t = t.replace(year=t.year+1)
					    t = t.replace(day=1,
						    hour=7, minute=0)
					    t = t.replace(month=1, 
						    hour=7)
	    return t

    def adjust_week(t):

	    if t.isoweekday() == 6:
		    try:
			   t = t.replace(day=t.day + 2)
		    except Exception as e:
			    try:
				    t = t.replace(day=2)
				    t = t.replace(month=t.month + 1)
			    except Exception as e:
				    t = t.replace(day=2)
				    t = t.replace(month=t.month + 1)
	    if t.isoweekday() == 7:
		    try:
			    t = t.replace(day=t.day + 1)
		    except Exception as e:
			    #El domingo es dia 31 del mes o 30
			    try:
				    t = t.replace(day=1)
				    t = t.replace(month=t.month + 1)
			    except Exception as e:
				    t = t.replace(day=1)
				    t = t.replace(month=t.month + 1)
	    return t

    def total_weekends(time_agn, time_req):
	    fromdate = date(time_req.year, time_req.month, time_req.day)
	    todate = date(time_agn.year, time_agn.month, time_agn.day)
	    daygenerator = (fromdate + timedelta(x + 1) for x in xrange((todate - fromdate).days))
	    return sum(1 for day in daygenerator if day.weekday() >= 5)

    def total_days(time_agn, time_req):
	    fromdate = date(time_req.year, time_req.month, time_req.day)
	    todate = date(time_agn.year, time_agn.month, time_agn.day)
	    daygenerator = (fromdate + timedelta(x + 1) for x in xrange((todate - fromdate).days))
	    return sum(1 for day in daygenerator if day.weekday() < 5)


    def main():
	    zenpy = Zenpy(**creds)
	    views = [...]
	    while True:
		    try:
			    for id_view in views:
				    tickets = zenpy.views.tickets(id_view)
				    for ticket in tickets:
					    ticket_comments = zenpy.tickets.comments(ticket.id)
					    first = True
					    found = False
					    for comment in ticket_comments:
						    if comment.public:
							    if first:
								    if comment.author_id == ticket.requester_id:
									    first_req = comment.body
									    time_req = comment.created_at
									    first = False
							    else:
								    user = zenpy.users(id=comment.author_id)
								    if user.role == 'agent' or user.role == 'admin':
									    first_ass = comment.body
									    time_agn = comment.created_at
									    found = True
									    break
					
					    if found:
						    time_agn = datetime.strptime(time_agn, 
                                                        "%Y-%m-%dT%H:%M:%SZ")
						    time_req = datetime.strptime(time_req, 
                                                        "%Y-%m-%dT%H:%M:%SZ")
						    time_agn = adjust_time(time_agn, False)
						    time_agn = adjust_week(time_agn)
						    time_req = adjust_time(time_req, True)
						    time_req = adjust_week(time_req)
						    weekends = total_weekends(time_agn, time_req)
						    days = total_days(time_agn, time_req)
						    result = time_agn - time_req
						    result = result.total_seconds() - ((32280 * days) + (54000 * weekends))
						    ticket.tags.append("first_reply")
						    s1 = "################################\n"
						    s1 += "Id view: " + str(id_view) + "\n"
						    s1 += "Ticket: " + str(ticket.id) + "\n"
						    s1 += "Tiempo agente: " + datetime.strftime(time_agn, "%Y-%m-%d %H:%M:%S") + "\n"
						    s1 += "Tiempo requester: " + datetime.strftime(time_req, "%Y-%m-%d %H:%M:%S") + "\n"
						    s1 += "Resultado: " + str(result) +  " En segundos: " + str(int(result)) + "\n"
						    s1 += "################################\n"
					    else:
						    time_agn = 0
						    time_req = 0
						    result = 0 #en el caso de que no haya respuesta de ningun agente
						    ticket.tags.append("no_reply")
						    s1 = "################################\n"
						    s1 += "No hay respuesta del agente"
						    s1 += "Id view: " + str(id_view) + "\n"
						    s1 += "Ticket: " + str(ticket.id) + "\n"
						    s1 += "################################\n"
					    with open("time2.txt", 'a') as file:
						    file.write(s1)
					    for field in ticket.custom_fields:
						    if field['id'] == 38717725:
							    field['value'] = int(result)
					    zenpy.tickets.update(ticket)
					    SLEEP(2)
		    except Exception as e:
			    with open("error.txt", 'a') as file:
				    file.write(str(e))
			    SLEEP(10)
    if __name__ == '__main__':
	    main()

The places where are the SLEEP function is where I assumed that make's an error

**Comment by facetoe** [comment]
Instead of updating each ticket individually, try building a list of tickets and updating them in batches of 100 at a time (zenpy.tickets.update() accepts a list also). You can save some API calls by populating the user cache ahead of time. Increase the user cache size to > your total users then execute `[u for u in zenpy_client.users.incremental(start_time)]` to populate the cache before entering the while loop.  

I'd also move the sleep statement into the `while` loop's scope and out of the `for` loop. Process the views and tickets then sleep for a bit before hitting them again. You might also be able to ignore a bunch of tickets by checking `ticket.comment_count` or whether the tags already include "first_reply" or "no_reply".

If you still recieve exceptions after trying these things post the full stacktrace.

**Comment by ppchaigneau** [comment]
Hi @bighelmet7 

I'm wondering in this code
`def get(self, view_id):
	creds['token'] = users[auth.username()]
	zenpy_client = Zenpy(**creds)
	tickets = zenpy_client.views.tickets(int(view_id))
	payload = {
		"tickets" : []
	}
	for ticket in tickets:
		aux = {"id": ticket.id,"subject": ticket.subject}
		payload["tickets"].append(aux)
	return payload`

"self" in your function stands for what?

Thanks
