### ISSUE TITLE
How can I call ticket_audits?

### ISSUE THREAD

**Issue by bighelmet7** [facetoe/zenpy#134]
I'm trying to access into an audit, but the only way I found is:

    audit = zenpy.tickets.update(ticket)

But I just get the last audit, and I want all the list.

**Comment by facetoe** [comment]
You can retrieve the audits for a ticket as follows:

```python
for audit in zenpy_client.tickets.audits(ticket_id=some_ticket_id):
    print(audit)
```

**Comment by bighelmet7** [comment]
Thx <3 you're always saving my day haha

**Comment by facetoe** [comment]
No worries!

**Comment by gitlech** [comment]
For the sake of completeness and to provide solution to the ones who are looking for it, I thought I'd post how to retrieve all audits for all tickets which is a valid use case if you e.g. want to load all your tickets into a Data Warehouse for further analysis:

```python
for ticket_id in [ticket.id for ticket in zenpy_client.tickets()]:
    for audit in zenpy_client.tickets.audits(ticket_id=ticket_id):
        audits['audits'].append(audit.to_dict())
```
