### ISSUE TITLE
views.count() returns View and not ViewCount

### ISSUE THREAD

**Issue by jdelannoye** [facetoe/zenpy#135]
Hi,
`print zenpy_client.views.count(147347885).__dict__` that returns a View object and not ViewCount

The method count_many() looks to work fine
`print zenpy_client.views.count_many([147347885]).__dict__`

`{'count': 1, 'next_page': None, 'response_handler': <zenpy.lib.response.ViewResponseHandler object at 0x10bc2bbd0>, 'previous_page': None, '_response_json': {u'count': 1, u'view_counts': [{u'poll_wait': 30, u'url': u'https://vadesecure.zendesk.com/api/v2/views/147347885/count.json', u'view_id': 147347885, u'refresh': u'pubsub', u'value': 11, u'pretty': u'11', u'fresh': True, u'channel': u'view/deb1a0716535679123e958c7f5bfffdcffaf7ae4/count'}], u'next_page': None, u'previous_page': None}, 'values': None, 'position': 0}
[Finished in 2.0s]`

**Comment by jdelannoye** [comment]
I have fixed it in a patch

api.py
`        """
        Return a ViewCount for a view.

        :param view: View or view id
        """
        if isinstance(view, View):
            view = view.id
        return self._get(self._build_url(self.endpoint.count(id=view)))`

endpoint.py
`    views.count = SecondaryEndpoint('views/%(id)s/count.json')`

response.py
`        elif 'view_count' in deserialized_response:
            return deserialized_response['view_count']`

**Comment by jdelannoye** [comment]
Could also be easily workarounded by using the "execute()" method.

How I use zenpy now : 
```
        self.zendesk_client = Zenpy(**creds)
    def getViewCount(self,id):
        """
        :param id: view id
        :return: the tickets count in the View
        """
        return self.zendesk_client.views.execute(id).count

```

**Comment by facetoe** [comment]
Thanks for the report and patch @jdelannoye. I've applied your suggested changes.
