### ISSUE TITLE
How to close a ticket.

### ISSUE THREAD

**Issue by abadd00d** [facetoe/zenpy#136]
Hi.

Is it possible to close a ticket via zenpy?
I can't find how to do this. Can you help me?

Thank you in advance.

**Comment by facetoe** [comment]
Hi @abadd00d, 

Yes it is possible:

```python
ticket = zenpy_client.tickets(id=<some_ticket_id>)
ticket.status = "closed"
zenpy_client.tickets.update(ticket)
```

**Comment by abadd00d** [comment]
Thanks! It works!

**Comment by facetoe** [comment]
No worries!
