### ISSUE TITLE
How to use the endpoint Ticket Import?

### ISSUE THREAD

**Issue by bighelmet7** [facetoe/zenpy#139]
I don't understand how i can import a ticket to zendesk

**Comment by facetoe** [comment]
You pass a Ticket or list of Tickets to the `ticket_import` endpoint - http://docs.facetoe.com.au/zenpy.html#ticket_import. When passing a list you need to ensure that there are less than 100 Tickets as specified in the docs - https://developer.zendesk.com/rest_api/docs/core/ticket_import#ticket-bulk-import.

Hope this helps!

**Comment by bighelmet7** [comment]
Thx ! but what if a what i need to do if the current ticket from the other platform got many comments? I've to import a Ticket and a Comment object to the endpoint ticket_import?
