### ISSUE TITLE
Not able to iterate over search results .

### ISSUE THREAD

**Issue by Srinidhi-SH** [facetoe/zenpy#140]
Like the example in the documentation :
for ticket in zenpy_client.search("zenpy", created_between=[yesterday, today], type='ticket', minus='negated'):
    print ticket

I tried to get results for searching a user using the code .

for user in zenpy_client.search(user="my_id@email_id.com"):
     print user

This is returning an error : 'Api' object has no attribute 'deserializer'

But the search method is working effectively . With the email ID I provided the results.count shows up 1 and 0 if not found . 

Need help to do this . Thanks in advance

**Comment by facetoe** [comment]
You are using an old version of Zenpy. That bug has already been fixed in #130.
