### ISSUE TITLE
Metrics Data

### ISSUE THREAD

**Issue by cdmerritt** [facetoe/zenpy#144]
Forgive me.  I'm a n00b to Python and zenpy.  I've used your API to pull a lot of details about specific tickets, but now I'm trying to pull metrics.  Specifically, I'm trying to get median first reply time by year/quarter and by ticket priority.  Is this something that can be done via zenpy?  Or, do I have to look at this data from an individual ticket perspective and aggregate myself?

Thanks in advance!
Chris

**Comment by facetoe** [comment]
I do not know if this is possible, though it may be. Your best bet is to look through the Zendesk API documentation and see if there is a method that suits your needs (https://developer.zendesk.com/rest_api/docs/core/introduction). If you find one, and it is not supported in Zenpy, I would be happy to add support.

**Comment by facetoe** [comment]
Does this help - https://developer.zendesk.com/rest_api/docs/core/ticket_metrics?

**Comment by cdmerritt** [comment]
I've looked at that, but I think that is still at the individual ticket level.  I know with insights @ ZD they have aggregated data exposed, but I'm not sure it's available via their REST API...May have to try and do it by ticket and aggregate myself...Bummer.

**Comment by facetoe** [comment]
Yes I think this is likely. Zenpy does not do any processing on the data it receives with the exception of caching, it is a one to one mapping with the Zendesk API.

**Comment by cdmerritt** [comment]
Cool.  Thanks for the quick response.  Much appreciated.
