### ISSUE TITLE
Can't add tags to tickets

### ISSUE THREAD

**Issue by jorijinnall** [facetoe/zenpy#145]
Hi,

In the documentation, it is mentionned that we can use the function add_Tags to add tags to a ticket : http://docs.facetoe.com.au/zenpy.html?highlight=tag#add_tags

But unfortunately, the function does not look to be exposed for the tickets : 

my call : 
`       ticket_to_qualify = zendesk.zenpy_client.tickets(id=221773)
    ticket_to_qualify.add_tags(id=221773,tags=["account_qualifed"])`

AttributeError: 'Ticket' object has no attribute 'add_tags'

Then, with some troubleshoot with python, I have found that it should be : 
ticket_to_qualify.api.add_tags(id=221773,tags=["account_qualifed"])

Could you fix the doc ?

Thanks

**Comment by facetoe** [comment]
Hi @jorijinnall, 

The documentation is correct. The method `add_tags` is exposed via the `TicketApi`, and so the following will work:

```python
zenpy_client.tickets.add_tags(id=3, tags=['atag'])
```

Although you could also just modify the `Ticket` object directly:

```python
ticket = zenpy_client.tickets(id=3)
ticket.tags.append('atag')
t = zenpy_client.tickets.update(ticket)
```

The reason your code above works is that all Zenpy objects hold a reference to the Api that created them:

```python
ticket = zenpy_client.tickets(id=3)
print(type(ticket.api))

>>> <class 'zenpy.lib.api.TicketApi'>
```

So the code:

```python
ticket_to_qualify.api.add_tags(id=221773,tags=["account_qualifed"])
```

Is exactly equivalent to:
```python
zenpy_client.tickets.add_tags(id=221773,tags=["account_qualifed"])
``` 

I can see however where the confusion arises and will add an example that shows how to add tags to a ticket as it is no doubt a very common use case.

Hope this helps!
