### ISSUE TITLE
issue with show_macro_effect

### ISSUE THREAD

**Issue by gutdraw** [facetoe/zenpy#147]
I am having an issue with show_macro_effect()

What would be causing this none type error on self.api?

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-29-72e5ac5e65a2> in <module>()
      3 # Execute the show_macro_effect() method which returns what the macro *would* do.
      4 zenpy_client.tickets(id=16200355).custom_fields.append(CustomField(id=24196943, value=datetime.date(2017, 8, 30)))
----> 5 macro_result = zenpy_client.tickets.show_macro_effect(Ticket(id=16200355),Macro(id=59606406))
      6 
      7 # Update the ticket to actually change the ticket.

//anaconda/lib/python2.7/site-packages/zenpy/lib/api.pyc in show_macro_effect(self, ticket, macro)
    858             macro = macro.id
    859         url = self._build_url(self.endpoint.macro(ticket, macro))
--> 860         return self._get(url)
    861 
    862     def merge(self, target, source,

//anaconda/lib/python2.7/site-packages/zenpy/lib/api.pyc in _get(self, url, raw_response)
     83             return response
     84         else:
---> 85             return self._process_response(response)
     86 
     87     def _call_api(self, http_method, url, **kwargs):

//anaconda/lib/python2.7/site-packages/zenpy/lib/api.pyc in _process_response(self, response)
    174             if handler.applies_to(self, response):
    175                 log.debug("{} matched: {}".format(handler.__name__, pretty_response))
--> 176                 return handler(self).build(response)
    177         raise ZenpyException("Could not handle response: {}".format(pretty_response))
    178 

//anaconda/lib/python2.7/site-packages/zenpy/lib/response.pyc in build(self, response)
    100         response_json = response.json()
    101 
--> 102         zenpy_objects = self.deserialize(response_json)
    103 
    104         # Collection of objects (eg, users/tickets)

//anaconda/lib/python2.7/site-packages/zenpy/lib/response.pyc in deserialize(self, response_json)
     73                 zenpy_object = self.api._object_mapping.object_from_json(
     74                     zenpy_object_name,
---> 75                     response_json[zenpy_object_name]
     76                 )
     77                 response_objects[zenpy_object_name] = zenpy_object

//anaconda/lib/python2.7/site-packages/zenpy/lib/mapping.pyc in object_from_json(self, object_type, object_json)
     96             return object_json
     97         ZenpyClass = self.class_for_type(object_type)
---> 98         obj = ZenpyClass(api=self.api)
     99         for key, value in object_json.items():
    100             if isinstance(value, dict):

TypeError: 'NoneType' object is not callable

**Comment by facetoe** [comment]
Can you post a minimal snippet of code that triggers the error?

**Comment by gutdraw** [comment]
So i pulled from the docs and am editing a custom field this works fine and if i update it does take effect:

zenpy_client.tickets(id=16200355).custom_fields.append(CustomField(id=24196943, value=datetime.date(2017, 8, 30)))


now when i pull from the example in the documentation and pass api objects with id to the show_macro_effect() method . i am getting the above error,  is there a way i should examine the macro to ensure a proper response is sent to python?


# Execute the show_macro_effect() method which returns what the macro *would* do.

macro_result = zenpy_client.tickets.show_macro_effect(Ticket(id=16200355),Macro(id=59606406))

# Update the ticket to actually change the ticket. 
zenpy_client.tickets.update(macro_result.ticket)

**Comment by facetoe** [comment]
Thanks for the report @gutdraw, this is a bug. I should have it fixed by tomorrow afternoon and will push a new version to PyPy.

**Comment by facetoe** [comment]
I've fixed the bug, will push a new version to PyPy soon.

**Comment by facetoe** [comment]
@gutdraw, I've pushed the latest version to PyPy. Let me know if you have any trouble!

**Comment by gutdraw** [comment]
Works!  Thanks so Much
