### ISSUE TITLE
Search returning nothing 

### ISSUE THREAD

**Issue by jeromemyers02** [facetoe/zenpy#151]
when using the search feature for organizations types. It returns a null value in version 1.2.2 but version 1.1.12 works.  

example
zd.search(type='organization', tags=orginal_organization_name)

**Comment by facetoe** [comment]
I'm not able to replicate this. If I execute:

```python
zenpy_client.organizations.update(Organization(id=116452523473, tags=['sometag']))
for org in zenpy_client.search(type='organization', tags='sometag'):
    print(org)
```
I get a single result as expected: `[Organization(id=116452523473)]`.

If nothing is found you shouldn't receive None back, you should get an empty SearchResultGenerator. Is this what you mean by null value?

In your example, what is `orginal_organization_name`? Is it a string, a list?

**Comment by facetoe** [comment]
Hi @jeromemyers02, as I haven't heard back I'm going to assume the issue is fixed. If you have any further trouble feel free comment or open a new issue.
