### ISSUE TITLE
Help Center API Support

### ISSUE THREAD

**Issue by nealdav** [facetoe/zenpy#153]
Wasn't clear from skimming the docs if this is available. 

zenpy.lib.api_objects.Topic Looks promising but I didn't see an example of it in action. Thanks

**Comment by facetoe** [comment]
Hi @nealdav, the Help Centre API is not currently supported. In theory it would be straightforward to add support, it's just a matter of defining the endpoints and the objects. I won't have time to implement this for a while but I will mark this issue as an enhancement and return to it when I am able.

**Comment by nealdav** [comment]
Sounds good and thank you for all of your great work on this client. It's proven to be very helpful.

**Comment by facetoe** [comment]
I've merged initial support for the HelpCentre API into master. There are a couple of endpoints that still are not supported, but the majority are. I haven't written any docs yet, but you can see what is available here - https://github.com/facetoe/zenpy/blob/master/zenpy/lib/api.py#L1468.

Let me know if you have any issues!

**Comment by nealdav** [comment]
I didn't see this until today. Will test, asap. Thank you!

**Comment by gho21** [comment]
Thanks for the cool library that made accessing Zendesk APIs easier. If you have time, please add support to get article_attachment from an article. Thanks again!

**Comment by gho21** [comment]
really impressive stuff, thanks!

**Comment by facetoe** [comment]
No worries :)

**Comment by gho21** [comment]
what is the syntax to create a section? I assume I need to pass in two parameters (category Id and the Section object) since the underlying REST API need them?

Thanks in advance!

**Comment by cryptomail** [comment]
HC support in there!
