### ISSUE TITLE
Support custom headers when making API requests

### ISSUE THREAD

**Issue by shihanwan** [facetoe/zenpy#154]
This is to satisfy the new Zendesk Marketplace requirements for all Integration Apps:
https://help.zendesk.com/hc/en-us/articles/115010249348-Announcing-Updated-Apps-Marketplace-API-Header-Requirements

**Comment by facetoe** [comment]
Hi @shihanwan, you should be able to do this by creating your own requests.Session object with the required headers and passing it to the Zenpy constructor.

**Comment by shihanwan** [comment]
@facetoe Thanks for the reply! We will try that solution and close the ticket if it work :)
