### ISSUE TITLE
Api Object to JSON/string

### ISSUE THREAD

**Issue by meriadok** [facetoe/zenpy#156]
I'm trying to print all the properties of a returned object into a file, or a JSON, is there a way to do this or do I have to print all the individual fields of the object? Specifically, tickets and their audits.

Thanks in advance, I know this is probably not the right channel but I'm desperate.

**Comment by facetoe** [comment]
Hi @meriadok, the easiest way is to call the `to_dict()` method of the object, eg:

```python
for ticket in zenpy_client.tickets():
    print(ticket.to_dict())
```
If the object you want to print contains nested objects, you can try the following:

```python
from lib.api import ZenpyObjectEncoder
for ticket in zenpy_client.tickets():
    print(json.dumps(ticket, cls=ZenpyObjectEncoder))
```
This will recursively de-serialize all the nested objects to JSON.

Hope this helps!

**Comment by meriadok** [comment]
Amazing, thanks a lot dude!
