### ISSUE TITLE
Identities

### ISSUE THREAD

**Issue by squeakyboots** [facetoe/zenpy#157]
Hi facetoe!
I thought I read all the docs but am not seeing how identities handling would be managed in the current build. Am I overlooking something, or has it not been built out?

User Identities ZD documentation:
https://developer.zendesk.com/rest_api/docs/core/user_identities#list-identities

I see it gets pulled per the debug request in the docs under the "Caching" docs but it doesn't seem to make its way into the user object as far as I can tell from examining a User object via User.to_dict(). 

Is there any way to get the other identity information (such as secondary phone numbers) in the current build?

![image](https://user-images.githubusercontent.com/11595454/31300412-d682f4c2-aab0-11e7-9e67-c5a19d815e71.png)

Thanks for your time and expertise. Great package!

Regards,
squeakyboots

**Comment by facetoe** [comment]
Hi @squeakyboots, yes the docs are falling behind the code a bit, need to update them. Identities are supported and you can query the identities for a user as follows:

```python
for identity in zenpy_client.users.identities(id=<user id>):
    print(identity)
```
The other operations on identities are documented in the code and can be found here - https://github.com/facetoe/zenpy/blob/master/zenpy/lib/api.py#L486.

Hope this helps!

**Comment by squeakyboots** [comment]
Derp, that makes sense, just wasn't where I expected it to be.

Thank you!
