### ISSUE TITLE
zenpy search all tickets except closed and solved

### ISSUE THREAD

**Issue by clagio** [facetoe/zenpy#159]
Hello,
I'm not sure how to make a search for all the tickets except the one in some particular status.
I tried with:
zenpy_client.search("", type='ticket', status!='closed',subject='ticket subject')
zenpy_client.search("", type='ticket', status<>'closed',subject='ticket subject')
zenpy_client.search("", type='ticket', -status='closed',subject='ticket subject')

In the documentation says to use the "minus" keyword, but it works only if we want to exclude some strings. How can I exclude based on the values on some ticket fields?

Thanks

**Comment by facetoe** [comment]
Hi @clagio, you could try something like the following:

```python
for ticket in zenpy_client.search(type='ticket', status_less_than='closed'):
    print(ticket)
```
There is a mapping table in the docs that shows how Zenpy translates the operators Zendesk uses  - http://docs.facetoe.com.au/zenpy.html#searching-the-api, and a great article provided by Zendesk that shows the available operators and how they can be used - https://support.zendesk.com/hc/en-us/articles/203663226.

I don't believe Zendesk supports a `NOT` operator, so you might need to experiment a bit with what is available to get the result you are after. 

Hope this helps!

**Comment by lalfaro1704** [comment]
Hi @facetoe how i can get all replies from a ticket and append a new reply

**Comment by ShellAndPython** [comment]
Nice this sintaxy work for me
