### ISSUE TITLE
Properly Support Ticket Fields

### ISSUE THREAD

**Issue by bighelmet7** [facetoe/zenpy#160]
Im trying this current line:
    zenpy_client.ticket_fields.update(field)
but the IDE tells me: 'Api' has not 'update' method
There's no update endpoint for Ticket Fields?

**Comment by bighelmet7** [comment]
The update, creating, ... is not supported

https://github.com/facetoe/zenpy/issues/28

**Comment by facetoe** [comment]
@bighelmet7, I'm going to keep this issue open to remind me to implement this when I get the chance. It shouldn't be too hard to add support.

**Comment by bighelmet7** [comment]
Amazing! thanks @facetoe

**Comment by facetoe** [comment]
Hi @bighelmet7, I've added support for CRUD operations on TIcketFields.

**Comment by bighelmet7** [comment]
Hi @facetoe I was trying to update a custom_field_options from a TicketField, and with the CRUD I wasnt able to update it, but this is a current bug on Zendesk with custom_field_options.
For exemple, this is a ticket_fields.to_dict() printable:

{
  "active": true,
  "collapsed_for_agents": false,
  "created_at": "2017-10-17T09:33:35Z",
  "description": "",
  "editable_in_portal": false,
  "id": 114100270111,
  "position": 9999,
  "raw_description": "",
  "raw_title": "Modelo",
  "raw_title_in_portal": "Modelo",
  "required": false,
  "required_in_portal": false,
  "title": "Modelo",
  "title_in_portal": "Modelo",
  "type": "tagger",
  "updated_at": "2017-12-20T09:03:08Z",
  "url": "HERE WAS AN URL",
  "visible_in_portal": false,
  "removable": true,
  "custom_field_options": [
    {
      "id": 114096469691,
      "name": "sergi",
      "raw_name": "sergi",
      "value": "mans_not_hot",
      "default": false
    },
    {
      "id": 114096279152,
      "name": "test_3",
      "raw_name": "test_3",
      "value": "test_update_3",
      "default": false
    },
  ]
}

And you want to append {"name": "test_new", "value": "test_not_hot"} in custom_field_options, it would be something like:

    ticket_field = zenpy.ticket_fields(id=TICKET_FIELD_ID)
    ticket_field.custom_field_options.append({"name": "test_new", "value": "test_not_hot"})
    zenpy.ticket_fields.update(ticket_field)

But the update wont be made, same with zendesk, if you curl ticket_field.to_dict() it wont made nothing, so to fix it, you need to be specific and just send {"ticket_fields": {"custom_field_options"}}

In zenpy it looks like:

    from zenpy.lib.api_objects import TicketField

    ticket_field = zenpy.ticket_fields(id=TICKET_FIELD_ID)
    ticket_field.custom_field_options.append({"name": "test_new", "value": "test_not_hot"})
    zenpy.ticket_fields.update(TicketField(id=ticket_field.id, custom_field_options=ticket_field.custom_field_options))

And this will made the update

**Comment by facetoe** [comment]
Hmmm, this could be a bug with the new incremental update feature. When you execute `ticket_field.custom_field_options.append({"name": "test_new", "value": "test_not_hot"})` it won't call `__setattr__` on the object and as such the `custom_field_options` won't be set as dirty and sent off to Zendesk.

Do you get the same behaviour if you use the version of Zenpy that is currently in Pip?

**Comment by facetoe** [comment]
Wait. scratch that, you said you tried using curl as well.

I just need to implement https://developer.zendesk.com/rest_api/docs/core/ticket_fields#create-or-update-a-ticket-field-option and then you should be able to modify custom_field_options.

**Comment by bighelmet7** [comment]
I didnt see that endpoint, now I understand all the failures! Because is another method of TicketFields.

**Comment by bighelmet7** [comment]
I was using this endpoint: PUT /api/v2/ticket_fields/{id}.json, sending just the custom_field_options, and it fails, and how is the "right way" to modify custom_field_options that will be reflected on 
    __setattr__ with the current zenpy version?

**Comment by facetoe** [comment]
This `__setattr__` thing is still a pretty big issue. I'm not sure how to fix it right now, need to think about it a bit.

**Comment by facetoe** [comment]
Hi @bighelmet7, I think I've fixed the `__setattr__` issue in 4f53c1094b30e3bdb510214c68d6d83fe853906c and now updating lists/dicts should work as expected.
