### ISSUE TITLE
Support NPS API

### ISSUE THREAD

**Issue by flpStrri** [facetoe/zenpy#162]
Is there any plan to implement NPS incremental api presented on [https://developer.zendesk.com/rest_api/docs/nps-api/nps_incremental_export](https://developer.zendesk.com/rest_api/docs/nps-api/nps_incremental_export)? I am not sure how to implement it but since it works the same way as the other incremental ones it will probably be quite simple.

**Comment by facetoe** [comment]
Hi @flpStrri, not currently, but I can look to add support for this API when I get the chance.

**Comment by flpStrri** [comment]
Do you have a dev oriented readme? If you give me a high level overview of how you implement this I can make a PR. I will need to implement a good way of getting this data anyway, in your library or in my.

**Comment by flpStrri** [comment]
Hey, @facetoe not sure if you saw, I created the PR to fix this ticket. Can you check it, please? ❤️

**Comment by facetoe** [comment]
Thanks @flpStrri! I'm going to leave this issue open as I'm hoping to add full support for the NPS endpoints soon.

**Comment by flpStrri** [comment]
That will be great!

**Comment by flpStrri** [comment]
@facetoe I forgot to bump the version number. You need to change that to update pip?

**Comment by facetoe** [comment]
@flpStrri, I have some more changes coming soon and was planning on updating pip with those as well. With any luck it won't be too much longer until that work is done.

**Comment by flpStrri** [comment]
What else is needed here?

**Comment by facetoe** [comment]
There is quite a lot of functionality not implemented in Zenpy - https://developer.zendesk.com/rest_api/docs/nps-api/introduction
