### ISSUE TITLE
requests.comments(request_id) returns a user object?

### ISSUE THREAD

**Issue by nealdav** [facetoe/zenpy#165]
It appears that the zenpy_client.requests.comments(request_id) api returns a user object instead of a comment object. 

Please let me know if this is actually the expected result. Thanks

**Comment by facetoe** [comment]
Thanks for the report @nealdav, that sounds like a bug.

**Comment by facetoe** [comment]
I've pushed a patch to fix this issue. I'm planning on pushing a new version to PyPi in the next week or so as I have some other changes as well.

**Comment by nealdav** [comment]
Awesome. Thank you!

**Comment by facetoe** [comment]
I've pushed a new version to PyPi.
