### ISSUE TITLE
Ticket Events

### ISSUE THREAD

**Issue by bjaus** [facetoe/zenpy#167]
Does zenpy support accessing ticket events for a specific ticket given the ticket id?

Great work by the way!

**Comment by facetoe** [comment]
Hi @bjaus,

Yes you can access all the events that have occurred for a given ticket via ticket audits:

```python
ticket = zenpy_client.tickets(id=1)
for audit in zenpy_client.tickets.audits(ticket.id):
    for event in audit.events:
        print(event)
```

Hope this helps!

**Comment by bjaus** [comment]
Awesome I didn't even think to look at the audits. Thanks for your help!

**Comment by facetoe** [comment]
No worries!
