### ISSUE TITLE
Access to ticket_metrics

### ISSUE THREAD

**Issue by leoqivivo** [facetoe/zenpy#170]
Hi !

thank you for this very usefull wraper,

i have a little question : how can i access to the ticket_metrics of a ticket (for example, i need the number of replies of a ticket, contained in the object "TicketMetric") ?

thanks, 

Léo

**Comment by facetoe** [comment]
Hi @leoqivivo, yes you can access the TicketMetric for a ticket as follows:

```python
metric = zenpy_client.tickets.metrics(ticket_id=<some ticket id>)
```

Hope this helps!

**Comment by leoqivivo** [comment]
Thank you for your reactivity !
yes its works :)
