### ISSUE TITLE
Resarch rapport is it implemented ?

### ISSUE THREAD

**Issue by leoqivivo** [facetoe/zenpy#171]
Hi again, thank you for your awnser this morning, 

i have another question (the last one, promised !) : 
how can i take the data about the "research" in zenpy ?

you can analyse the request of client (who ask from help center of my website) on zendesk, and i don't know if you implemented this in zenpy

thank you,

Léo

**Comment by facetoe** [comment]
Hi @leoqivivo, can you link me to the Zendesk API documentation that describes this feature? If so I can tell you if it's implemented and where to find it in Zenpy.

**Comment by leoqivivo** [comment]
That's the problem, i don't find in the zendesk, but maybe its exists and i didn't find it
its looks like this : 
https://support.zendesk.com/hc/en-us/articles/203662296
at the end, the part "Viewing top content, searches, and agents"

thank you !

**Comment by leoqivivo** [comment]
if found this : 
https://developer.zendesk.com/rest_api/docs/help_center/search

**Comment by facetoe** [comment]
I don't think Zendesk exposes that information via the API unfortunately.

**Comment by leoqivivo** [comment]
ok thanks
