### ISSUE TITLE
Can't iterate over a single search result

### ISSUE THREAD

**Issue by konaya** [facetoe/zenpy#172]
I'm not sure if I'm doing something wrong here. I create a ticket, search for it, get one search result as expected, but then I can't do a next() to retrieve it. Is this expected behaviour? If so, how is it supposed to be handled?

I'm running version 1.2.3 on Python 2.7.14.

```
>>> tics = zc.search(type="ticket", status_before="closed", tags="backup_failure device:vps1.example.com", sort_by="created_at", sort_order="desc")
>>> tics.position
0
>>> tics.count
1
>>> len(tics)
1
>>> ticket = tics.next()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/konaya/virt_zenpy/lib/python2.7/site-packages/zenpy/lib/generator.py", line 35, in next
    self.handle_pagination()
  File "/home/konaya/virt_zenpy/lib/python2.7/site-packages/zenpy/lib/generator.py", line 44, in handle_pagination
    self._response_json = self.get_next_page()
  File "/home/konaya/virt_zenpy/lib/python2.7/site-packages/zenpy/lib/generator.py", line 59, in get_next_page
    raise StopIteration()
StopIteration
>>> tics.position
0
>>> tics.count
1
>>> len(tics)
1

```

**Comment by konaya** [comment]
I could provice a [pickled](https://wiki.python.org/moin/UsingPickle) zenpy.lib.generator.SearchResultGenerator object if that would do any good.

**Comment by facetoe** [comment]
Hmm, this is a strange one. I am unable to replicate this behaviour. Can you check that the `_response_json` attribute of the `SearchResultGenerator` is populated correctly? It should match the response you get from executing the same request via `curl`. 

If you turn logging on DEBUG you will see the request URLs that are being generated.

It's probably best not to send through a pickled `SearchResultGenerator` as it contains your API credentials.

**Comment by facetoe** [comment]
Hi @konaya, as I haven't heard back I'm going to assume this issue is resolved. If you have any further trouble with this issue feel free to reopen.
