### ISSUE TITLE
user_fields returns [UserField(id='None')]

### ISSUE THREAD

**Issue by JulianSchneider** [facetoe/zenpy#173]
When I retrieve a user by ID that has a custom user field, the user_field dictionary returns [UserField(id='None')] where as the curl call returns the actual values. 

Submitting the fields works fine.

**Comment by facetoe** [comment]
Hi @JulianSchneider, 

Yes this is a little confusing, but your values are there in the UserField object. If you had a field called `test_user_field`, you could access it as follows:

```python
for user in zenpy_client.users():
    print(user.user_fields.test_user_field)
```

Alternatively, if you want you fields in the same format as the curl command returns, you could do:

```python
for user in zenpy_client.users():
    print(user.user_fields.to_dict())
```

The reason you see the strange id='None' business has to do with how the `__repr__` method works for Zenpy objects. I'll fix it up to just display `UserField()` so as to avoid the confusion.
