### ISSUE TITLE
Help desk api

### ISSUE THREAD

**Issue by Shaakmiller** [facetoe/zenpy#174]
Hello,

Does zenpy support the help desk API? For example, can I make calls to download or create knowledge base articles?

Thank you,

Joshua

**Comment by facetoe** [comment]
Hi @Shaakmiller, I started implementing support in this branch - https://github.com/facetoe/zenpy/tree/help_centre_api, however I never got the time to finish it. Most of the API is supported, and when I get the chance I will finish it off. If you you do use this branch please note that it is unstable and the Python API may change a little before it is merged into master.

I haven't had a chance to write documentation for this yet, but you can find out what supported by checking the HelpCentreApi code here - https://github.com/facetoe/zenpy/blob/help_centre_api/zenpy/lib/api.py#L1464. 

For example, you can read articles as follows:

```python
for article in zenpy_client.help_center.articles():
    print(article)
```

Hope this helps!

**Comment by Shaakmiller** [comment]
Alright, thanks for letting me know. I will probably take a crack at it in a few months, just wondering if it was in your sights.

**Comment by Shaakmiller** [comment]
Yes this helps, thank you!
