### ISSUE TITLE
Incremental export to dataframe

### ISSUE THREAD

**Issue by inmorales** [facetoe/zenpy#175]
Hello,

Do you know how can I convert result generator of incremental ticket export object to a dataframe (pandas)? and another question, is there any quick way to transform custom_fields in a dataframe of pandas?

Thank

**Comment by facetoe** [comment]
Hi @inmorales, I'm not very familiar with pandas so can't help with this. The one thing that might assist however is converting your Ticket objects to Python dictionaries and then to pandas dataframes. The first step can be done as follows:

```python 
from lib.api import ZenpyObjectEncoder
for ticket in zenpy_client.tickets.incremental(start_time=start_time):
    print(json.loads(json.dumps(ticket, cls=ZenpyObjectEncoder)))
```
This will recursively serialize the Ticket object and any nested object to JSON, then convert to a Python dict.

Hope this helps!
