### ISSUE TITLE
Bug with the UserIdentities

### ISSUE THREAD

**Issue by oodzee** [facetoe/zenpy#176]
Hi @facetoe! 

Thanks for the update for the identities, it works now! 
However, I think I noticed some other bug linked with the identity: 

If I want to make an identity primary, the code gets the identity id

`      if isinstance(identity, Identity):
            identity = identity.id
        return UserIdentityRequest(self).put(self.endpoint.make_primary, user, identity)`

but this is also repeated when creating the UserIdentityRequest:

`class UserIdentityRequest(BaseZendeskRequest):

    def put(self, endpoint, user, identity):
        payload = self.build_payload(identity)
        url = self.api._build_url(endpoint(user, identity.id))
        return self.api._put(url, payload=payload)`

which gets me this error:
`AttributeError: 'int' object has no attribute 'id'`

I'm kind of new to Python so I might be wrong about this. If not, then the issue is also for the other functions request_verification and verify. 

Thanks!

**Comment by oodzee** [comment]
Hi again @facetoe 

Thanks for the fix for this. After testing, it works and I can make an identity primary but I get the warning: 
`WARNING:zenpy.lib.api:Non-zenpy object found in _dirty_object list 115441605054. This should never happen!
`

115441605054 being in this case the id of the identity that I want to make primary.

The code that triggers this warning is the following: 
`zenpy_client.users.identities.make_primary(
    user=user_to_update.id,
    identity=Identity(id=identity_to_make_primary_id)   
)`

I tried using a User directly, or an identity id instead of an Identity object but it doesn't work. Am I missing something obvious maybe?

Thanks in advance!

**Comment by facetoe** [comment]
Hi @oodzee, thanks for the report. Just to clarify, does the code above successfully make the identity primary?

The warning shouldn't be anything to worry about. It is generated when trying to clean up dirty objects after they have successfully been submitted to Zendesk. I should probably set the log level to DEBUG though.

**Comment by facetoe** [comment]
Also, I should mention that it should work using either an object or an id.

**Comment by oodzee** [comment]
@facetoe: Yes it does make the identity primary, and I tried both (id or object) to see if it would remove the warning but I haven't been successful so far.

**Comment by facetoe** [comment]
Excellent, thanks. I'll fix up the warning.
