### ISSUE TITLE
Dynamic Content Endpoint

### ISSUE THREAD

**Issue by facetoe** [facetoe/zenpy#18]
https://developer.zendesk.com/rest_api/docs/core/dynamic_content

**Comment by facetoe** [comment]
I didn't have a Professional plan at the time so was unable to implement it. If this is a feature you'd like to see added I can have a look at implementing it when I get the chance.

**Comment by scelen** [comment]
Thanks, definitely would like access to Dynamic Content.

**Comment by facetoe** [comment]
@scelen I've added support for Dynamic Content.
