### ISSUE TITLE
Can't fetch all data from chat api

### ISSUE THREAD

**Issue by ThiagoCobli** [facetoe/zenpy#181]
Hello.
It seems that this lib does not support pagination feature, and I can't fetch all data. When I use curl I can paginate normally using the `next_url` param from response.

Could you please help? If it does not support pagination, could you give instructions on how to implement?

Thanks in advance.

**Comment by facetoe** [comment]
Hi @ThiagoCobli, Zenpy supports pagination transparently via generators. You can iterate over results as follows:

```python
for chat in zenpy_client.chats():
    print(chat)
```

**Comment by oodzee** [comment]
Hi @facetoe,

I think that the pagination is indeed not working, unless I missed something.
In my code, I have this: 
`list_total = zenpy_client.chats()
total = len(list_total)
print("Found {} entries".format(total))
for item in list_total:
   [...code to insert item in db]`

The result printed is "Found 3521 entries" but in the db I got only 40 rows, which is only the first page ("The Search Chats endpoint returns a limit of 10,000 results per query, or 200 pages with 40 results per page. ")

Thanks!

**Comment by facetoe** [comment]
It may well be broken, but can you try executing the following:

```
for chat in zenpy_client.chats():
    print(chat)
```

And see if it still only returns 40 items? The chat endpoint returns a generator which I can't see from the code above whether it is being fully consumed.

**Comment by oodzee** [comment]
@facetoe I just tried and it just print 40 items Chat(id='[...]') without displaying any errors.

**Comment by facetoe** [comment]
Yep, definitely a bug. I'll look into it. Thanks for the report.

**Comment by facetoe** [comment]
OK finally got a chance to fix this.
