### ISSUE TITLE
Updating User object with multiple organizations on Enterprise removes organizations

### ISSUE THREAD

**Issue by bighelmet7** [facetoe/zenpy#183]
Hi! I found an error this morning, that its quite annoying:

Suppose you've got an user with two or more organizations, and you need to append a tag to the list tags of the user so your code would look something like this:

    USER_ID = 1234
    creds = {...}
    zenpy_client = Zenpy(**creds)
    user = zenpy.users(id=USER_ID)
    user.tags.append("new_tag")    #this is the tag you need to append
    zenpy.users.update(user)          #send the user to zendesk

And the expected result is that your user now has the new tag, but what happens is that the user, loose all his organizations except of one (the default_one).
If you do a requests call (with the requests package of python, for exemple), and the payload you need to send will look like this: {"user": "tags": ["old_tag", "new_tag"]} simulating an append, then you made the PUT method, and know you will see that your user is update successfully and does not loose any organization.

So to implement this with Zenpy, will be like this:
    
    from zenpy.lib.api_objects import User
    ....
    USER_ID = 1234
    creds = {...}
    zenpy_client = Zenpy(**creds)
    user = zenpy.users(id=USER_ID)
    tags = user.tags.append("new_tag")    #this is the tag you need to append
    zenpy.users.update(User(id=user.id, tags=tags))          #send the user to zendesk

This is a current bug, in many zendesk framework, less in zendesk ruby framework (their official), analyzing it, I detect that the framework, just send to an update method, just the modified fields or attributes of the user.

It would be nice to have this feature, @facetoe

**Comment by facetoe** [comment]
Hi @bighelmet7,

This issue does not arise if you pass the modified user to the update method, instead of creating a new User object and passing that. For example:

```python
user = zenpy_client.users.me()
print(user.tags)

user.tags.append('new_tag')
zenpy_client.users.update(user)
user = zenpy_client.users.me()
print(user.tags)
```
Outputs:

```
['two_tag', 'onetag']
['two_tag', 'onetag', 'new_tag']
``

I agree that only sending the modified attributes would be a nice feature, and much more efficient on the wire, however it would require quite a bit of refactoring so I'm hesitant to try to implement it at the moment as I don't have the time.

If executing the code above leads to different results on your system, could you let me know what version of Python you are running?

**Comment by bighelmet7** [comment]
@facetoe the tags are successfully modified, but if your user has more than one organization, and made the zenpy.users.update he will loose all the organizations. Im using python3.6.1

**Comment by facetoe** [comment]
Ahh sorry, I misread your issue.

**Comment by facetoe** [comment]
Ahhh, are you on an Enterprise plan? I only have a trial account, and according to - https://support.zendesk.com/hc/en-us/articles/203661766-About-organizations-and-groups, Enterprise users can belong to multiple organizations but trial and Team cannot.

I'll need to get in contact with Zendesk and see if they will give me an Enterprise account to test with. It might finally be time to have a go at refactoring things to only update the modified attributes.

Thanks for the report @bighelmet7, this is a particularly nasty bug.

**Comment by bighelmet7** [comment]
@facetoe yep! but I can attach you the json:

The next user has got 3 organizations, but when you call the user endpoint, you only get one organization:

<img width="319" alt="captura de pantalla 2017-12-15 a las 12 51 31" src="https://user-images.githubusercontent.com/23640897/34041045-b1ee9b12-e196-11e7-8b02-7b817e0798b2.png">


{
  "user": {
    "id": 116104534834,
    "url": "https://test.zendesk.com/api/v2/users/116104534834.json",
    "name": "BigHelmet",
    "email": "bighelmet7@test.com",
    "created_at": "2017-12-15T09:34:23Z",
    "updated_at": "2017-12-15T10:46:33Z",
    "time_zone": "Madrid",
    "phone": null,
    "shared_phone_number": null,
    "photo": null,
    "locale_id": 1194,
    "locale": "es-419",
    "organization_id": 116498799233,
    "role": "end-user",
    "verified": false,
    "external_id": null,
    "tags": [
      "test3",
      "test4",
      "test6",
      "test2",
      "test5"
    ],
    "alias": "",
    "active": true,
    "shared": false,
    "shared_agent": false,
    "last_login_at": null,
    "two_factor_auth_enabled": false,
    "signature": null,
    "details": "",
    "notes": "",
    "role_type": null,
    "custom_role_id": null,
    "moderator": false,
    "ticket_restriction": "requested",
    "only_private_comments": false,
    "restricted_agent": true,
    "suspended": false,
    "chat_only": false,
    "default_group_id": null,
    "user_fields": {
      
    }
  }
}

And if I do:
    user.tags.append("test7")
    zenpy.users.update(users)

Json of the request:

{
  "user": {
    "id": 116104534834,
    "url": "https://test.zendesk.com/api/v2/users/116104534834.json",
    "name": "BigHelmet",
    "email": "bighelmet7@test.com",
    "created_at": "2017-12-15T09:34:23Z",
    "updated_at": "2017-12-15T11:53:02Z",
    "time_zone": "Madrid",
    "phone": null,
    "shared_phone_number": null,
    "photo": null,
    "locale_id": 1194,
    "locale": "es-419",
    "organization_id": 116498799233,
    "role": "end-user",
    "verified": false,
    "external_id": null,
    "tags": [
      "test3",
      "test4",
      "test6",
      "test2",
      "test5",
      "test7"
    ],
    "alias": "",
    "active": true,
    "shared": false,
    "shared_agent": false,
    "last_login_at": null,
    "two_factor_auth_enabled": false,
    "signature": null,
    "details": "",
    "notes": "",
    "role_type": null,
    "custom_role_id": null,
    "moderator": false,
    "ticket_restriction": "requested",
    "only_private_comments": false,
    "restricted_agent": true,
    "suspended": false,
    "chat_only": false,
    "default_group_id": null,
    "user_fields": {
      
    }
  }
}

And the user:
<img width="305" alt="captura de pantalla 2017-12-15 a las 12 55 23" src="https://user-images.githubusercontent.com/23640897/34041147-3396538a-e197-11e7-940c-c28e4910b1b9.png">

If you need an Enterprise, you just need to access here [https://developer.zendesk.com/apps/docs/publish/sponsored_account](url) and if you compromise to use this just for testing youll have a year of account for free.

**Comment by facetoe** [comment]
That's awesome @bighelmet7, I've been wishing I had an Enterprise account for years! I'll sign up and have a go at implementing this when I get time. I might be able to get some work done on it this weekend.

**Comment by bighelmet7** [comment]
@facetoe thats awesome! Im trying to understand more the framework so Im been able to made commits. Have fun with the Enterprise! Its more worth than trial, if you need more info, our company is an official Zendesk Partners :)

**Comment by facetoe** [comment]
That's excellent @bighelmet7, thanks!

**Comment by facetoe** [comment]
@bighelmet7, I've implemented support for incremental object updates in https://github.com/facetoe/zenpy/tree/incremental_object_updates. Are you able to test if this fixes the issue with deleting organizations? I haven't heard back from Zendesk yet about the Enterprise plan, but it is the weekend :)

**Comment by bighelmet7** [comment]
@facetoe ofc! in a few hours I could test it. You're awesome how you fix it in a short time!
Glad you finally will have the Enterprise

**Comment by facetoe** [comment]
Hey @bighelmet7, I merged these changes into master, so it's best to test from there!

**Comment by bighelmet7** [comment]
@facetoe Sorry I wasnt able to test it yesterday, at the moment I'm downloading the repo!

**Comment by bighelmet7** [comment]
Works amazing @facetoe, you're a genius!

**Comment by bighelmet7** [comment]
@facetoe can you explain a little how the new commit works? I cant understand, that of self.__dict__['_dirty_attributes'] its like, everything that was change will be in the dirty_attributes to send to zendesk?

**Comment by facetoe** [comment]
Yep, that's right. The way it works is whenever you assign a value to an object in python using the dot notation, eg `user.name = 'Bob'`, under the hood it calls [\__setattr__](https://docs.python.org/3/reference/datamodel.html#object.__setattr__). In `BaseObject` I override that method [here](https://github.com/facetoe/zenpy/blob/master/zenpy/lib/api_objects/__init__.py#L18), to add the name of the modified attribute to the `_dirty_attributes` set.

There is one complication, in that when an object is initialized, inside the `__init__` method, attributes are assigned which populates the `_dirty_attributes` set. To work around that, I clear the set after instantiating the object [here](https://github.com/facetoe/zenpy/blob/master/zenpy/lib/mapping.py#L119) . That way, when the object is returned to the user the set is empty.

Once the user has made their modifications and are ready to update, the object needs to be converted to JSON. This is done by the [ZenpyObjectEncoder](https://github.com/facetoe/zenpy/blob/master/zenpy/lib/api.py#L23). The way this works is whenever the `json.dumps` method encounters a type that it doesn't understand, it calls the `default` method in the encoder class. If it is a Zenpy object, then I convert it to a Python dictionary using `to_dict(serialize=True)`, which only returns those attributes that are in the `_dirty_attributes` set, and the id. That way, only the modified attributes are converted and sent to Zendesk.

There is one final issue that could arise. Imagine a case where the user tries to update an object, but the update fails due to network instability. If the `_dirty_attributes` set was cleared before confirming that Zendesk had processed it, they would lose their changes. For this reason, I store the last object sent to Zendesk [here](https://github.com/facetoe/zenpy/blob/master/zenpy/lib/api.py#L70), and only when I know the update succeeded, do I clear the objects `_dirty_attributes` set [here](https://github.com/facetoe/zenpy/blob/master/zenpy/lib/api.py#L186).

That's basically how it works. Let me know if you have any questions!

**Comment by bighelmet7** [comment]
@facetoe amazing !!! you're my reference to be a success Python programmer :)

**Comment by facetoe** [comment]
Haha I'm flattered, but there are lot better Python programmers than me :) The [requests](https://github.com/requests/requests) project has some really nice Python code.

**Comment by eduardomirandacd** [comment]
Hi there.

I know that this case has been closed for years now, but I am unfortunately unable to understand how the solution provided works.

I have here two screen captures where it shows from the Zendesk interface a user who belongs to 03 Organizations.

When via Zenpy I print that user as JSON, it shows only one **organization_id**.  Shouldn't that be 03 different IDs?

Additionally, how can I programmatically via Zenpy add more organizations to my user?

![zenpy-org-01](https://user-images.githubusercontent.com/66138483/128274582-eac89096-7724-4283-8a1c-04c2347b5329.png)
![zenpy-org-02](https://user-images.githubusercontent.com/66138483/128274590-a0fc794f-ff7a-4c7f-9072-b12f4104124b.png)


Any help would be greatly appreciated!

Regards,
Eduardo

**Comment by eduardomirandacd** [comment]
For those that had the same doubt as I did, I recommend taking a look at [https://github.com/facetoe/zenpy/issues/52#issuecomment-216018911](https://github.com/facetoe/zenpy/issues/52#issuecomment-216018911).
