### ISSUE TITLE
Sideload kwarg generates incorrect Zendesk URL

### ISSUE THREAD

**Issue by rtkmrussell** [facetoe/zenpy#187]
I am trying to fetch requests as a normal end user and use sideloading to get the display name of users associated with the request:
```
zenpy.requests(id=request_id, sideload='users')
```
Based on my limited understanding of the code in `endpoint.py` it looks like that should be a supported syntax.

Around line 120 in `endpoint.py` it looks for the sideload kwarg:
```
        if 'sideload' in kwargs and not kwargs['sideload']:
            return query
        else:
            return query + self._format_sideload(self.sideload)
```

At that point, `query` is just `requests/123.json`, but `self._format_sideload` uses an ampersand as the separator instead of a question mark.  It also appends `self.sideload` instead of `kwargs['sideload']`, so the resulting URL zenpy fetches is:
 `/requests/123.json&include=`
instead of
`/requests/123.json?include=users`.

It seems like a bug, but I may also be completely misusing the library 😄

**Comment by facetoe** [comment]
Thanks for the report @rtkmrussell. The way sideloading is currently implemented is a bit terrible, I've been meaning to refactor it for a while now. 

What you tried is perfectly logical but not supported by the current implementation. The way it works is sideloads are defined per endpoint, for example - https://github.com/facetoe/zenpy/blob/master/zenpy/lib/endpoint.py#L468. 

I must have missed the requests sideload as they are not defined for the requests endpoint - https://github.com/facetoe/zenpy/blob/master/zenpy/lib/endpoint.py#L441.

Thankfully, you should be able to fix this by adding the sideload as follows:

```python
zenpy_client.requests.append_sideload('users')
```

From this point forward users should be sideloaded.

Let me know if this doesn't work or you have any questions.
