### ISSUE TITLE
Unable to set ticket created_at and updated_at values.

### ISSUE THREAD

**Issue by mardicas** [facetoe/zenpy#190]
Hi,
I am able to set due_at, but NOT created_at and updated_at values when creating ticket. The ticket get's created but has the created_at and updated_at set to current time, not what I set in the api call.

```
...
newticket=Ticket(subject=summary , description=description,due_at=update_date, created_at=create_date, status="open", type="task", organization_id=thinmap[compname]['zen_id'], recipient=reporter_mail, priority="normal", assignee_id=assignee_id, submitter_id=creator_id, requester_id=thinmap[compname]['zen_uid'])
print(newticket.to_dict())
zenpy_client.tickets.create(newticket)

```
I have tried to change the status and also use tickets.update after creating the ticket to change the values.

Example values from to_dict():
`{'status': 'open', 'description': u'Imported from jira issue https://jira.cloud.ee/browse/SD-2373', 'submitter_id': 360038121234, 'assignee_id': 360038121234, 'due_at': u'2017-12-06T13:47:33Z', 'requester_id': 360051219253, 'recipient': u'tarmo.xxx@xxx.ee', 'organization_id': 360000462693, 'created_at': u'2017-12-06T13:47:03Z', 'priority': 'normal', 'subject': u'SD-2373 https://api.nutiarve.callista.ee/ basi auth eemaldamine', 'type': 'task'}`

I am importing tickets from another system and want to preserve the ticket dates. Ticket is created, but the dates seem to be ignored, except for due_at field.

Do you have an idea what might be causing the issue?

**Comment by facetoe** [comment]
Hi @mardicas, yes this is becuase created_at and updated_at are read only attributes of a ticket: https://developer.zendesk.com/rest_api/docs/core/tickets. If you are importing tickets from an external system you are better off using the ticket import API which allows setting these values: https://developer.zendesk.com/rest_api/docs/core/ticket_import.
