### ISSUE TITLE
Support for ticket_audits? (Not the same as tickets.audits)

### ISSUE THREAD

**Issue by jdmarch** [facetoe/zenpy#191]
The `ticket_audits` endpoint can be used to return the most recent audits, regardless of what ticket they are for. (Vs. tickets.audits, that can return all the audits for a given ticket.)
https://developer.zendesk.com/rest_api/docs/core/ticket_audits

In the absence of support for this endpoint, seems like the most likely way to get recent audits would be to get the most recently updated tickets ~use tickets.recent~, then get the most recent audits for those tickets.

The disadvantage of this workaround, is that in a situation where many tickets have a long history and many audits, most of the audits in recent tickets are not recent, so the ratio of desired (recent) audits to retrieved audits is low, adding greatly to bandwidth and runtime.

Any other suggestions / plans? Thanks!

**Comment by jdmarch** [comment]
Also the ticket_audits endpoint can return up to 1000 recent audits with a single API call, vs 1 or 2 API calls per changed ticket IIUC.

**Comment by jdmarch** [comment]
Corrected issue description which wrongly referred to tickets.recent

**Comment by facetoe** [comment]
Thanks for the report @jdmarch. This looks like a new endpoint, I'll add support when I get the chance.

**Comment by facetoe** [comment]
Hi @jdmarch, I've added support for this endpoint. Here is a quick example of how it can be used:

```python
audit_generator = zenpy_client.tickets.audits()
for audit in audit_generator:
    print(audit)

# You can retrieve the cursor values from the spent generator.
print(audit_generator.after_cursor, audit_generator.before_cursor)

# You can pass an explicit cursor value to consume audits create after that point.
for audit in zenpy_client.tickets.audits(cursor='fDE1MTc2MjkwNTQuMHx8'):
    print(audit)

# Reversing the generator reverses the direction in which you consume objects. The
# following grabs objects from just before the cursor value until the beginning of time.
for audit in reversed(zenpy_client.tickets.audits(cursor='fDE1MTc2MjkwNTQuMHx8')):
    print(audit)
```

**Comment by jdmarch** [comment]
Thanks, @facetoe , looks brilliant. I'll report if I encounter any issues.

**Comment by jdmarch** [comment]
> `# You can pass an explicit cursor value to consume audits created after that point.`

AFAICT, that is true if the explicit cursor is an `after_cursor`. If the explicit cursor is a `before_cursor`, then it consumes audits created before that point, yes?

With that in mind, I don't yet see the use-case for the reversed generator here, but that's probably just since I haven't yet played with it.

**Comment by cpickard** [comment]
It looks the previous syntax to retrieve the audit entries for a ticket no longer works.

This is the syntax suggested in issue [#134]( #134 ):

```
for audit in zenpy_client.tickets.audits(ticket_id=some_ticket_id):
    print(audit)
```

In zenpy 1.2.5 this works as expected, in 2.0.1 it retrieves 1000 most recent audits.

**Comment by facetoe** [comment]
Yes the keyword argument for this endpoint (and all others that were in the form `<object>_id`) has changed to just the object name. You can pass either an id or an object to the endpoint, eg: 

```python
for audit in zenpy_client.tickets.audits(ticket=4980):
    print(audit)
```

or 

```python
for audit in zenpy_client.tickets.audits(Ticket(id=4980)):
    print(audit)
```

Will both work. This is also true for the other endpoints that work in the same way, for example:

```python
for user in zenpy_client.users():
    for organization in zenpy_client.users.organizations(user=user):
        print(organization)
```
