### ISSUE TITLE
Latest Tickets are not having Assignee details

### ISSUE THREAD

**Issue by sreenathmenon** [facetoe/zenpy#193]
Hi Guys,

I am using Zenpy version 1.2.6. Everything was working correctly till 4-5 days back.

_**Exact issue:**_

**New Tickets - When I create a ticket and view it's details, it doesn't contain Assignee details. Assignee Id is returned as 'None' in the api response.**

Api Response

`
{'follower_ids': [], 'via': Via(), 'updated_at': u'2018-02-02T12:55:54Z', 'submitter_id': 36004*****, 'assignee_id': None, 'brand_id': ******, 'api': <zenpy.lib.api.TicketApi object at 0x7f8494cf2550>, 'url': u'https://*******.zendesk.com/api/v2/tickets/21.json', 'id': 21, 'custom_fields': [], 'satisfaction_rating': None, 'tags': [], 'collaborator_ids': [], 'priority': u'low', 'subject': u'test attachments', 'type': None, 'status': u'new', 'description': u'test attachmentstest attachmentstest attachmentstest attachmentstest attachments', 'sharing_agreement_ids': [], 'forum_topic_id': None, 'organization_id': None, 'is_public': True, 'requester_id': 360048******, 'recipient': None, 'problem_id': None, 'raw_subject': u'test attachments', 'fields': [], 'created_at': u'2018-02-02T12:37:48Z', 'due_at': None, '_dirty_attributes': set([]), 'allow_channelback': False, 'has_incidents': False, 'group_id': 114094335****, 'external_id': None}
`

**Old Tickets** - In the case of old, tickets, the assignee details are getting displayed. Issue is only for new tickets.

`
{'follower_ids': [], 'via': Via(), 'updated_at': u'2018-01-17T07:02:20Z', 'submitter_id': 3600482****, 'assignee_id': 11432668****, 'brand_id': *******, 'api': <zenpy.lib.api.TicketApi object at 0x7f8494d18550>, 'url': u'https://******.zendesk.com/api/v2/tickets/5.json', 'id': 5, 'custom_fields': [], 'satisfaction_rating': None, 'tags': [], 'collaborator_ids': [], 'priority': u'high', 'subject': u'assigning ticket to another user (testing)', 'type': None, 'status': u'open', 'description': u'assigning ticket to another user (testing) assigning ticket to another user (testing) assigning ticket to another user (testing)assigning ticket to another user (testing)assigning ticket to another user (testing)', 'sharing_agreement_ids': [], 'forum_topic_id': None, 'organization_id': None, 'is_public': True, 'requester_id': 3600482*****, 'recipient': None, 'problem_id': None, 'raw_subject': u'assigning ticket to another user (testing)', 'fields': [], 'created_at': u'2018-01-17T07:00:32Z', 'due_at': None, '_dirty_attributes': set([]), 'allow_channelback': False, 'has_incidents': False, 'group_id': 114094335****, 'external_id': None}
`

Have anyone seen such an issue?

Thanks,
Sreenath

**Comment by facetoe** [comment]
Hmm, I haven't seen this before. When I create a ticket I the assignee is set as expected:

```python
ta = zenpy_client.tickets.create(Ticket(subject='test', description='test'))
print(ta.ticket.assignee)
>>> User(id=116514121092)
```
How are you creating your tickets? Does the user associated with your email address exist?

**Comment by sreenathmenon** [comment]
Hi,

I have done further testing on this using multiple accounts. 

**1) Account 1 - Assignee details are returned correctly. (an old account)**

First Output - Assignee details
Second Output - full Ticket response

`
User(id=8668193668)
`
`
{'follower_ids': [], 'via': Via(), 'updated_at': u'2018-02-02T13:46:49Z', 'submitter_id': 8668193668, 'assignee_id': 8668193668, 'brand_id': 1535088, 'api': <zenpy.lib.api.TicketApi object at 0x7f956c0af590>, 'url': u'https://*******.zendesk.com/api/v2/tickets/201.json', 'id': 201, 'custom_fields': [], 'satisfaction_rating': None, 'tags': [], 'collaborator_ids': [], 'priority': None, 'subject': u'Ticket Attachment', 'type': None, 'status': u'open', 'description': u'test', 'sharing_agreement_ids': [], 'forum_topic_id': None, 'organization_id': 8358087008, 'is_public': True, 'requester_id': 8668193668, 'recipient': None, 'problem_id': None, 'raw_subject': u'Ticket Attachment', 'fields': [], 'created_at': u'2018-02-02T13:46:47Z', 'due_at': None, '_dirty_attributes': set([]), 'allow_channelback': False, 'has_incidents': False, 'group_id': 29859848, 'external_id': None}
done
`

**2) Account 2 - Assignee details are not returned (a new account - 1-2 month old)**

`
None
`
{'follower_ids': [], 'via': Via(), 'updated_at': u'2018-02-02T13:47:02Z', 'submitter_id': 114326680233, 'assignee_id': None, 'brand_id': 114094129333, 'api': <zenpy.lib.api.TicketApi object at 0x7fe7ed5bc5d0>, 'url': u'https://******.zendesk.com/api/v2/tickets/29.json', 'id': 29, 'custom_fields': [], 'satisfaction_rating': None, 'tags': [], 'collaborator_ids': [], 'priority': None, 'subject': u'Ticket Attachment', 'type': None, 'status': u'new', 'description': u'test', 'sharing_agreement_ids': [], 'forum_topic_id': None, 'organization_id': 115025186273, 'is_public': True, 'requester_id': 114326680233, 'recipient': None, 'problem_id': None, 'raw_subject': u'Ticket Attachment', 'fields': [], 'created_at': u'2018-02-02T13:47:00Z', 'due_at': None, '_dirty_attributes': set([]), 'allow_channelback': False, 'has_incidents': False, 'group_id': 114094335253, 'external_id': None}
`

So, We can conclude that this isn't an issue with zenpy module.
Sorry for posting the bug early.

Also, what do you think about this issue?
Will this be related to any account settings? I have compared the settings and couldn't find anything.

Only change I observed was that there is an API tab (under Channels section) in the zendesk admin interface. The settings in this were configured for new account. But it wasn't enabled for old account.

If I remember correctly, this API setting was enabled since there were API authentication errors at first:

`
zenpy.lib.exception.APIException: {"error": "Couldn't authenticate you"}
`
Any ideas on this are much appreciated.

Thanks,
Sreenath

**Comment by facetoe** [comment]
Yea I'd guess it must be related to the account settings in some way. As far as I know you must have the API explicitly enabled or it won't authenticate you, so it is a bit funny that the old account didn't have this enabled. Maybe try enabling it for the old account and see if the issue is still present?
