### ISSUE TITLE
TypeError when string coded int passed as rate limit parameter

### ISSUE THREAD

**Issue by tesmerjg** [facetoe/zenpy#194]
I observed this error:

```if time_since_last_call() is None or time_since_last_call() >= 10 or lastlimitremaining >= self.ratelimit:
TypeError: '>=' not supported between instances of 'int' and 'str'
```
and through debugging identified that the issue is that i coded the rate limit as a string in my config file, like this: "10".

the issue was clearly mine, but perhaps changing to int(self.ratelimit) rather than just self.ratelimit would prevent others from encountering this issue?

**Comment by facetoe** [comment]
Sure, can't hurt.
