### ISSUE TITLE
reversed tickets.audits generator behavior seems inconsistent

### ISSUE THREAD

**Issue by jdmarch** [facetoe/zenpy#196]
Running this code after creating client `zpc`:

```
revgen=reversed(zpc.tickets.audits(limit=5))
for i,audit in enumerate(revgen):
    if i%5==0:
        print()
        if i==15:
            break
    print(audit.created.time())
```

Gives this output:

```
02:19:39
03:01:08
03:01:09
03:01:10
04:01:44

02:18:24
02:03:07
02:01:56
02:01:55
02:01:55

02:01:55
02:01:55
02:01:21
01:43:44
01:41:48
```

The first chunk of results are in chronologically increasing order, whereas each subsequent chunk of results are in decreasing order (as is expected if one is running backwards in time).

Saving the user the effort of chaining together a series of chunks, by implicitly retrieving and passing on the before_cursor, is appealing, but it's not entirely clear that `reversed` is a clear / intuitive way of doing this, given that the default order of the returned audits generator is already backwards in time, and leading to counter-intuitive behavior such as reported here.

xref https://github.com/facetoe/zenpy/issues/191#issuecomment-363300838

**Comment by facetoe** [comment]
Hmm yes I see the issue. I'm not set on using the `reversed()` method, happy to consider alternate implementations. One possibility could be to explicitly define the direction that you intend to iterate when calling the method, and then depending on the value passed return a generator going in that direction. 

For example you could do something like (have to think of better names):

```python
for audit in zenpy_client.tickets.audits(backwards=True, cursor='some_cursor'):
    ...
```
What do you think? Any other ideas?

**Comment by jdmarch** [comment]
An explicit direction sounds good to me. (Explicit > implicit and all that)

I would think that backwards should be the default, because it's the only direction that can be started without already having an explicit cursor.

When chaining repeated chunks backwards, the before_cursor would be passed between chunks, and also by the user if starting with an explicit cursor.

When chaining repeat chunks forwards, the after_cursor would be passed between chunks and also by the user in the top level parameter.

Also, just for clarity, I think it's useful in your examples to include the `limit` parameter, since small limits make testing so much more efficient.

It's not clear to me whether there should be two methods -- a lower-level one that doesn't chain, just stops at limit, and a higher-level one that chains the lower level one until stopped by the user (e.g. with islice) or by exhaustion of the data. 

It's not strictly necessary to expose the lower-level one, as the chaining one can do anything that it can, and would seem to be more useful in most real-world situations. But the chaining one would be a bit more complicated to use for the simplest small-N test cases, so I guess having the low-level one exposed would probably be useful. 

Hmm, how about just having the single `audits` method, but having another `repeat=False` (or `chain=False`?) parameter for the chaining case?

**Comment by facetoe** [comment]
I'm not quite sure I understand what you mean by chaining chunks. I was thinking you just kick the generator off in a direction with an optional limit and it keeps on going until either it runs out of audits or it hits the limit. Happy to look at implementing something with chaining that but would need to have a better understanding of how it should work first!

> Also, just for clarity, I think it's useful in your examples to include the limit parameter

Yes, agreed. I'll add that in.

**Comment by jdmarch** [comment]
> I'm not quite sure I understand what you mean by chaining chunks. I was thinking you just kick the generator off in a direction with an optional limit and it keeps on going until either it runs out of audits or it hits the limit. Happy to look at implementing something with chaining that but would need to have a better understanding of how it should work first!

To be explicit, and for clarity -- there's always a limit. I think the default (and the max allowed) is 1000. What's optional is that you can specify a smaller value. That's the max number of audits that ZD will give you with one API call. That's what I meant by a "chunk". Different limit values (chunk sizes)  may be useful in different situations

It's most convenient to have the generator keep progressing through the audits, one chunk at a time, until you stop calling it. That's what I mean by "chaining". For example, you might be examining all audits for the past month. You're not sure how many there will be, but you guess about 500. So maybe you set the limit (chunk size) to 500, and often that's enough, but sometimes it's not; the generator just keeps giving you audits until you stop invoking it.

AFAICT (and as the initial example in this issue shows), that's what your "reverse" does, and I don't *think* that's what your un-reversed `audits` generator does, though I might have missed that or there might be some unintended failure to do so because the bug in #195. If that's already the intention, then this suggestion would amount to nothing more than fixing that bug.

**Comment by facetoe** [comment]
OK finally got a chance to look at this. I've patched the bug, your test code above now yields:

```
04:55:46
04:55:40
04:55:34
04:55:28
04:55:22

04:55:16
04:55:10
04:55:04
04:54:58
04:54:52

04:54:47
04:54:41
04:54:35
04:54:29
04:54:23
```

**Comment by jdmarch** [comment]
Thanks @facetoe !
