### ISSUE TITLE
Ticket Last comment

### ISSUE THREAD

**Issue by inmorales** [facetoe/zenpy#197]
Is there a way to find the last comment of a ticket? I would like to put the last comment when I bring the tickets with incremental export.

**Comment by facetoe** [comment]
It doesn't look like the incremental ticket API allows you to sideload comments, so you would have to request them for each ticket you are interested in, which could slow things down quite a lot. It does provide a comment_count value, so that might come in handy.

**Comment by jedi4z** [comment]
```python
*_, last_comment = zenpy_client.tickets.comments(ticket=<ticket_id>)
return last_comment
```
