### ISSUE TITLE
Support for creation of user as part of ticket creation?

### ISSUE THREAD

**Issue by jdmarch** [facetoe/zenpy#199]
Does zenpy support this pattern?

https://developer.zendesk.com/rest_api/docs/core/tickets#creating-a-ticket-with-a-new-requester

> Creating a ticket with a new requester
> You can specify a requester when creating a ticket. A name, email, and locale id can be set for the requester. A name and email are required. For locale ids, see the Locales API.
> If the requester's identity doesn't exist in Zendesk, a new user profile is created on the user's behalf. The user needs to verify their identity to view his or her requests.
> If a user exists in Zendesk with the specified email address, then Zendesk uses that user and makes no updates to existing users during the ticket creation process. In this approach, only the email attribute is required.

**Comment by jdmarch** [comment]
This may not be worth the time. I was hoping that this might provide a way to support a custom role that could create tickets for new users, but could not delete existing users. But on reflection, that seems unlikely, constrained by Zendesk rather than by zenpy.

**Comment by facetoe** [comment]
No worries, I'll leave this open though and implement it when I get the chance. Shouldn't be too tricky to do.

**Comment by facetoe** [comment]
Looks like this is already supported, just need to pass a User object as the requester:

```python
zenpy_client.tickets.create(Ticket(subject='TestUserCreate',
                                   description='testing',
                                   requester=User(email='someguy@example.com', name="Some Guy")))
```

**Comment by jdmarch** [comment]
Thanks @facetoe, confirmed. 
For the record, if the user already exists, `name` is ignored.
