### ISSUE TITLE
Fix issue where objects modified in a list are not sent to Zendesk in an update

### ISSUE THREAD

**Issue by dlasusa** [facetoe/zenpy#200]
Not sure if this is the same as discussed in issue #93 but since it deals with tickets instead of users, I'm creating a new issue.  

```
# Default
zenpy_client = Zenpy(**creds)

# Get the right ticket
ticket = zenpy_client.tickets(id=8)

# Get the right list item - which is a dictionary - new to python, this is for my own benefit
mgr_field = ticket.custom_fields[5]
print(mgr_field)

# Version 1 -  Update the VALUE key as i thought I should?
mgr_field['value'] = "test21"

# Version 2 - Update the VALUE key based on workaround from issue #93
mgr_field = dict(id=360001802253, value="test21")

# Printing again for checking output - this looks correct from either version above
print(mgr_field)

# Update the ticket - This seems to not be working
zenpy_client.tickets.update(ticket)
```

I seem able to update the object in Python, but it never gets written back to Zendesk.  No errors to report, exit code 0

**Comment by facetoe** [comment]
Hi @dlasusa, you've managed to hit a bit of an obscure edge case which will need to be fixed. Short answer, reassign the field to the list:

```python
ticket = zenpy_client.tickets(id=200)
field = ticket.custom_fields[0]
field['value'] = "SOMEVALUE"
ticket.custom_fields[0] = field
zenpy_client.tickets.update(ticket)
```

It's nasty, it's dumb, it shouldn't be that way, but it will work for now.

Long answer, it has to do with incremental object updates. Basically, Zenpy used to send all the attributes of an object to Zendesk to be updated, even if they had not changed. The assumption was that updating an item with the same value is essentially a NOP. This is true, but the way it plays out in the real world is something like this:

* Zenpy pulls ticket N
* some other process P modifies ticket N
* Zenpy executes an update to ticket N
*  process P's change to ticket N is reverted

To solve this problem Zenpy was patched to only send those attributes that have been modified to Zendesk when executing an update. This was simple enough for direct changes to a Zenpy object, for example Ticket.status, but a bit trickier when that attribute is a list or dictionary. How do you know whether or not the dict or list was modified? To solve that issue, I implemented proxy lists and dicts, so I can detect whether or not a list or dict has been altered:

```python
>>> ticket = zenpy_client.tickets(id=200)
>>> print(type(ticket.custom_fields))
<class 'zenpy.lib.proxy.ProxyList'>
```
The ProxyList implementation has a flaw, in that it does not detect when an item stored in the list has been modified, only whether or not the list was modified, and that explains the behavior you are seeing. I'll need to figure out a way to fix this.

You can see what will be sent to Zendesk in an update as follows:

```python
>>> ticket = zenpy_client.tickets(id=200)
>>> print(ticket.to_dict(serialize=True))
{'id': 200}
>>> ticket.status = "closed"
>>> print(ticket.to_dict(serialize=True))
{'id': 200, 'status': 'closed'}
```

Hope this helps.

**Comment by dlasusa** [comment]
Ahh....gotcha.  Weird, but I get it.  Thanks for the workaround.  It does exactly what I need in the meantime.  Thanks!!

**Comment by facetoe** [comment]
This has been fixed, and now updating elements inside a list should work as expected.
