### ISSUE TITLE
Add to_json() method to Zenpy objects

### ISSUE THREAD

**Issue by allisonwang** [facetoe/zenpy#202]
I followed this example #156 with ticket but the returned JSON only has id field. Ticket here contains nested objects. I am wondering what could be issue here?
```python
for ticket in zenpy_client.tickets():
    print(json.dumps(ticket, cls=ZenpyObjectEncoder))
>>> {id:123}
```

**Comment by facetoe** [comment]
This will no longer work after the incremental update patch. Does `ticket.to_dict()` work for you?

**Comment by allisonwang** [comment]
Using a different default function for `json.dumps` works for me!

**Comment by facetoe** [comment]
Mind posting your solution? Could help others facing the same issue.

**Comment by facetoe** [comment]
I'm going to look at adding this functionality to the Zenpy objects as it seems like a pretty common thing people would want to do.

**Comment by allisonwang** [comment]
Thanks! That would be really helpful. Here is my workaround:
```python
def zenpy_obj_dumper(obj):
    return obj.to_dict()

json.dumps(list(result_generator), default=zenpy_obj_dumper)
```

**Comment by facetoe** [comment]
Cool thanks, I'll see if I can add this on the weekend.

**Comment by jadbuck** [comment]
Hi there,
Looking to see if there are any traction on this. This would be a very much appreciated feature.
Much thanks for all your work!
