### ISSUE TITLE
SearchEndpoint cannot handle args with '+' character

### ISSUE THREAD

**Issue by AaronTorgerson** [facetoe/zenpy#203]
I was testing the Zenpy client today with a gmail address that has a '+' character in it, and I couldn't figure out why it was returning no results. After some digging, I found this:

```python
from zenpy.lib import endpoint
e = endpoint.EndpointFactory('search')
print e('mfwmtesting+201803140@gmail.com', type='ticket')
# ==> 'search.json?query=mfwmtesting+201803140@gmail.com+type:"ticket"'
```

It seems to me that the issue is that the _args_ are not getting properly URL encoded, and the "+" in my email address is being interpreted as a space character in the query parameter. Furthermore, the [ZD API reference](https://developer.zendesk.com/rest_api/docs/core/search#url-encoding-the-search-string) states that the entire search string should be URL encoded. It appears that the code is trying to do that, however it seems to miss encoding (at least) the _args_. 

**ZenPy Version:** 1.2.6

**Comment by facetoe** [comment]
Zenpy uses the requests library under the hood, which will URL encode the search string. I'm guessing the issue you are facing comes from the fact the Zendesk uses the + character to separate search blocks. If you put the same search string in the Zendesk search box in the web app do you see the same behavior?

**Comment by AaronTorgerson** [comment]
I was wondering about that myself, however IIRC requests only does that for query parameter that you pass to it via kwargs. E.g: `requests.get('http://example.com/api', params={'thing1': 'true'})`. It seems not to URL encode query parameters that are already baked into the URL you pass to it, which is what this Search `EndpointFactory` is doing. 

I turned on debug logging for urllib3 to see what the actual URL of the outgoing request was and this is what it spat out:

```
DEBUG 2018-03-15 03:58:25,541 urllib3.connectionpool connectionpool 1 <munged> https://mfwm.zendesk.com:443 "GET /api/v2/search.json?query=mfwmtesting+201803140@gmail.com+type:%22ticket%22&sort_order=desc&sort_by=updated_at HTTP/1.1" 200 None
```

**Comment by AaronTorgerson** [comment]
Based on the examples in the [ZD API docs on this subject](https://developer.zendesk.com/rest_api/docs/core/search#syntax-examples), they separate the blocks by spaces, then go on to recommend that you URL encode the search string as a whole.  (Perhaps the guidance for using '+' to separate search blocks is outdated?) That would seem like a safer way to handle things in ZenPy, ensuring that all args, etc., are properly handled.

**Comment by facetoe** [comment]
Yep I think you're right. It might even be an ancient bug from when I implemented the endpoints and is only now showing up. I'll have a look at this on the weekend.

**Comment by facetoe** [comment]
I haven't been able to reproduce this behavior but I've changed the code to use space as a separator instead of the '+' character. Let me know if you are still having issues after this change has been applied.

**Comment by ye** [comment]
@facetoe b46b0dc is not a proper fix. This hasn't addressed the original issue @AaronTorgerson raised, which was the plus sign "+" was not urlencoded. It should be urlencoded to `%2B` because on Zendesk's end when they decode the query string, `%2B` decoded to `+` whereas `+` decoded to ` ` (a white space).

**Comment by facetoe** [comment]
Can you provide a snippet that demonstrates this bug?
