### ISSUE TITLE
SearchEndpoint - NameError: name 'ZENDESK_DATE_FORMAT' is not defined

### ISSUE THREAD

**Issue by nealdav** [facetoe/zenpy#204]
**v1.2.3**
`ZENDESK_DATE_FORMAT = "%Y-%m-%d"

    def __call__(self, *args, **kwargs):

        renamed_kwargs = dict()
        modifiers = list()
        sort_order = list()
        for key, value in kwargs.items():
            if isinstance(value, datetime):
                kwargs[key] = value.strftime(self.ZENDESK_DATE_FORMAT)`

**v1.2.6**
`    def __call__(self, *args, **kwargs):

        renamed_kwargs = dict()
        modifiers = list()
        sort_order = list()
        for key, value in kwargs.items():
            if isinstance(value, datetime):
                kwargs[key] = value.strftime(ZENDESK_DATE_FORMAT)`

I just found that some of my older queries are throwing a NameError on Zenpy v1.2.6. 
Looks like the ZENDESK_DATE_FORMAT attr is missing. 

v1.2.3 is the last version without the issue.

**Comment by facetoe** [comment]
Thanks for the report @nealdav, I'll push a patch.

**Comment by nealdav** [comment]
thank you!
