### ISSUE TITLE
Updating tags after ticket comment is added

### ISSUE THREAD

**Issue by erinachavez** [facetoe/zenpy#206]
I'm trying to specifically update tags on a ticket after a comment is added to the ticket. According to Zendesk events it seems as if the comment and tags are being updated at the same time. Advice?

```
this_ticket = zenpy_client.tickets(id=ticket_id)
this_ticket.description = admin_id
this_ticket.status = "open"
this_ticket.comment = Comment(body="Comment!",public=True)
zenpy_client.tickets.update(this_ticket)

zenpy_client.tickets.delete_tags(id=ticket_id, tags="dontnotify")
```

**Comment by facetoe** [comment]
Well `zenpy_client.tickets.update` and `zenpy_client.tickets.delete_tags` are separate API calls, so they can't be happening at the same time. You can try setting the desired tags directly on the ticket object before calling `zenpy_client.tickets.update` and removing the `delete_tags` call:

```python
this_ticket.tags = [tags...]
```

**Comment by erinachavez** [comment]
Perhaps I'm just missing something dumb.

```
this_ticket = zenpy_client.tickets(id=ticket_id)
tags_list = zenpy_client.tickets(id=ticket_id).tags

if 'customerresponded' not in tags_list and '3fields' not in tags_list:
      zenpy_client.tickets.add_tags(id=ticket_id, tags=['qquote','dontnotify'])
      zenpy_client.tickets.delete_tags(id=ticket_id, tags=['followupquote','quotesent','moreinfo','other'])

this_ticket.description = admin_id
this_ticket.status = 'open'
this_ticket.comment = Comment(body='Comment!',public=True)
zenpy_client.tickets.update(this_ticket)

zenpy_client.tickets.delete_tags(id=ticket_id, tags='dontnotify')
```
This is what is happening on the ticket...
![capture](https://user-images.githubusercontent.com/25967093/37834165-85a90e4a-2e83-11e8-8b9b-24b384c04f7f.PNG)

**Comment by facetoe** [comment]
What version of Zenpy are you running? Anyway, I think I know what is happening here. Basically, when you create `this_ticket`, you get the state of the ticket as it was in that instant. Later, you modify the tags, however the `this_ticket` object holds the old state (ie, with all the tags). Finally, you add a comment to `this_ticket` and update it, along with the original tags. This has the effect of reverting your previous changes to the tags.

You have two options. Pull the ticket afresh after modifying the tags:

```python
this_ticket = zenpy_client.tickets(id=ticket_id)
tags_list = this_ticket.tags

if 'customerresponded' not in tags_list and '3fields' not in tags_list:
    zenpy_client.tickets.add_tags(id=ticket_id, tags=['qquote','dontnotify'])
    zenpy_client.tickets.delete_tags(id=ticket_id, tags=['followupquote','quotesent','moreinfo','other'])
    # Pull the new state of the ticket
    this_ticket = zenpy_client.tickets(id=ticket_id)

this_ticket.description = admin_id
this_ticket.status = 'open'
this_ticket.comment = Comment(body='Comment!',public=True)
zenpy_client.tickets.update(this_ticket)

zenpy_client.tickets.delete_tags(id=ticket_id, tags='dontnotify')
```

Or just work with the Ticket.tags list directly:
```python
this_ticket = zenpy_client.tickets(id=ticket_id)
if 'customerresponded' not in this_ticket.tags and '3fields' not in this_ticket.tags:
    this_ticket.tags = ['qquote']

this_ticket.description = admin_id
this_ticket.status = 'open'
this_ticket.comment = Comment(body='Comment!', public=True)
zenpy_client.tickets.update(this_ticket)
```

Hope this helps.

**Comment by erinachavez** [comment]
Thanks for the advice! I decided to just use a combination of zdesk and zenpy. That eventually worked. Thanks again!
