### ISSUE TITLE
How can I do more with zenpy_client.views

### ISSUE THREAD

**Issue by Axeish** [facetoe/zenpy#210]
Hello,
There are two things that I am trying to do but not able to find a way to do it.

1. Count each tags in a view.
2. display views count

So far my zenpy client does is count total ticket through this line:
`zenpy_client.views.execute(324730048).count`

**Comment by facetoe** [comment]
The best place to look is the Zendesk documentation - https://developer.zendesk.com/rest_api/docs/core/views. Zenpy wraps the Zendesk API in a one to one fashion, so you can checkout their docs and if you can find an API call that will suit your needs then call it from Zenpy.

So for example, the docs show that you can list active views - https://developer.zendesk.com/rest_api/docs/core/views#list-active-views. And you can do this in Zenpy as follows: 

```python
zenpy_client.views.active()
```
As the return type is a generator, you can ask for it's len:

```python
print(len(zenpy_client.views.active()))
```
If you find an API call that is not implemented that you would like to use, raise an issue and I will look into adding support for it.

Hope this helps.

**Comment by Axeish** [comment]
its not directly implemented but definitely there is a way to do it.

what i want to do instead is create a view with particular tag and then count it  and then update it with new tags

for example:

suppose i have a tag " issues1" , "issues2", "issues3", "question"

- create a view which contains all the issue in last 24 hours ( issue1,2,3)
- update it to see in last 48 hours
- update it so views contain only issue 1 in 48 hours
- update it so view contains only questions in 48 hours
- update it so view contains all the tickets in last 3 hours ( no tag condition)

I will try creating this scenario .. i want to focus on create and update view
