### ISSUE TITLE
Organization & user fields support

### ISSUE THREAD

**Issue by Ptr314** [facetoe/zenpy#213]
Could you please add an "organization_fields" property to the Zenpy class like "user_fields" is done.

Also it will be very useful to have a possibility to update user & organization fields.

**Comment by facetoe** [comment]
Hi @Ptr314, this is already supported:

```python
for organization in zenpy_client.organizations():
    print(organization.organization_fields)

for user in zenpy_client.users():
    print(user.user_fields)
```

**Comment by Kilo59** [comment]
I'm able to access the `organization_fields` property but I don't seem to be able to access the actual fields as they exist in our Zendesk instance.

![image](https://user-images.githubusercontent.com/13108583/38780178-9e30c3de-40a0-11e8-9227-6eed8a7bfb33.png)

![image](https://user-images.githubusercontent.com/13108583/38780043-f4ad6b38-409e-11e8-86cd-2292f9cf1336.png)

**Comment by facetoe** [comment]
Looks like you are using an older version of Zenpy, this issue was fixed a while back.

**Comment by Ptr314** [comment]
Yes, the newest version from Git has got this property but it is still impossible to get the LIST of available fields. If I call zenpy.organizations.organization_fields() I get an error "id is required" - I've inspected the source and if I just change the id parameter to be not required, it works fine - I can get the list of available organization fields.

**Comment by facetoe** [comment]
Ahh, I misunderstood what you were asking. I will need to add support for that endpoint. To be sure, you are talking about these methods - https://developer.zendesk.com/rest_api/docs/core/organization_fields?

**Comment by facetoe** [comment]
I created an issue to add support - https://github.com/facetoe/zenpy/issues/219.
