### ISSUE TITLE
Get total number of Object

### ISSUE THREAD

**Issue by flyingdutchman** [facetoe/zenpy#214]
Is it possible to get the total number of Objects in an API ?

A nice feature would be to have a zenpy_client.organizations.total(), .num() or size()

Thanks !

**Comment by facetoe** [comment]
Yep this should work for any endpoint that returns a generator. So for example:

```python
print("Organizations: {}".format(len(zenpy_client.organizations())))
print("Tickets: {}".format(len(zenpy_client.tickets())))
print("Users: {}".format(len(zenpy_client.users())))
```

Hope this helps!
