### ISSUE TITLE
User Identities Sideloading

### ISSUE THREAD

**Issue by flyingdutchman** [facetoe/zenpy#215]
Hello !

I am trying to sideload User Identities to the a user call with:
`zenpy_client.users(include=['identities'])`

But I don't know how to access them. I have been looking into your documentation and there is no mention of an existing User Identity API even if, by the looks of it, it has been implemented in the code in some places.

Thanky you in advance

**Comment by facetoe** [comment]
Yea the sideloading needs some work. Currently it us only really useful when including a linked attribute, for example Organizations. This is because the sideloaded object is cached,  preventing an extra API call when accessing the linked attribute. As an example, the following code does not need to generate an extra API call for the organization:

```python
for user in zenpy_client.users(include=['organizations']):
    print(user.organization)
```
```
DEBUG - GET: https://d3v-zenpydev.zendesk.com/api/v2/users.json?include=organizations - {'timeout': 60.0}
DEBUG - GenericZendeskResponseHandler matched: {u'count': 1, ....
DEBUG - Caching: [Organization(id=115219725952)]
DEBUG - Caching: [User(id=116514121092)]
DEBUG - Cache HIT: [Organization 115219725952]
Organization(id=115219725952)
```

Whereas the following does:

```python
for user in zenpy_client.users():
    print(user.organization)
```
```
DEBUG - GET: https://d3v-zenpydev.zendesk.com/api/v2/users.json - {'timeout': 60.0}
DEBUG - GenericZendeskResponseHandler matched: {u'count': 1, ...
DEBUG - Caching: [User(id=116514121092)]
DEBUG - Cache MISS: [Organization 115219725952]
DEBUG - GET: https://d3v-zenpydev.zendesk.com/api/v2/organizations/115219725952.json - {'timeout': 60.0}
DEBUG - GenericZendeskResponseHandler matched: {u'organization': ...
DEBUG - Caching: [Organization(id=115219725952)]
Organization(id=115219725952)
```

If you just want to retrieve identities for users, you can do so as follows:

```python
for user in zenpy_client.users():
    for identity in zenpy_client.users.identities(id=user.id):
        print(identity)
```

I need to update the docs to reflect this, however in the meantime you can see the methods that are available documented in the code - https://github.com/facetoe/zenpy/blob/master/zenpy/lib/api.py#L552. 

Hope this helps.

**Comment by flyingdutchman** [comment]
Thank you very much for this complete answer !

So the code you're suggesting makes a new call for each user ?
I'll be better off using a for loop for all user identities instead of calling it with individual calls.

**Comment by facetoe** [comment]
Yep that's right, each call to `zenpy_client.users.identities(id=user.id)` is going to over the network. Depending on what you are trying to do, you might be able to take advantage of the fact the identities are still in the cache:

```python
for user in zenpy_client.users(include=['identities']):
    # Do thing with user
    pass
for _, identity in cache_mapping['identity'].items():
    # Link user to identity
    print(identity.user)
```

Note that the caches are bounded, so you might need to tweak them a bit if you have a lot of users/identities. 

You can see which API calls are being generated if you enable logging:

```python
log = logging.getLogger()
log.setLevel(logging.DEBUG)
ch = logging.StreamHandler(sys.stdout)
formatter = logging.Formatter('%(levelname)s - %(message)s')
ch.setFormatter(formatter)
log.addHandler(ch)
logging.getLogger("requests").setLevel(logging.WARNING)
```

Hope this helps.

**Comment by flyingdutchman** [comment]
Well I'm currently working on a program that dumps all the data in Zendesk into a local DB.
The individual ticket calls take way to much time (~1s per ticket instead of 100t/s with sideloading). I'll give a try to your workaround.

It would be awesome if the sideloading feature could work in a way or another.
I'd gladly help, but I must say that I am not totally at ease with Python for now (could be a great experience though).

**Comment by facetoe** [comment]
If you are looking to dump a lot of data, have a look at the incremental endpoints - https://developer.zendesk.com/rest_api/docs/core/incremental_export. They allow you to retrieve 1000 objects per API call, and support sideloading some object types. If you have a bit of memory to play with, bumping up the cache max capacity tunables could speed things up quite a bit if you find a lot of API calls are being generated to retrieve single objects.

I'll create an issue to fix up sideloading. I think it might require a bit of a refactor so I won't be able to look at it for a while unfortunately.

**Comment by flyingdutchman** [comment]
Yes I use the incremental exports for my tickets as it is the only way to get the archived tickets.
I tried to get the incremental users with : 
````python
zenpy_client.users.incremental(start_time=start_time, include="identities")
````
But apparently this Zenpy does not support sideloading on Incremental Exports.

> I'll create an issue to fix up sideloading. I think it might require a bit of a refactor so I won't be able to look at it for a while unfortunately.

No worries, thank you very much for the quick answers ! 👍

**Comment by facetoe** [comment]
All good, I just submitted a patch to support sideloading for incremental endpoints. Just note that the include parameter must be a list of sideloads, eg: `zenpy_client.users.incremental(start_time=yesterday, include=['identities'])`

**Comment by alexyuisingwu** [comment]
I'm not sure if I'm just missing something, but I'm not sure how to get sideloaded identities from the generator. I can see that the ZendeskResultGenerator _response_json includes the "identities" list, but iterating over it seems to only return users (with no identity fields).

**Comment by facetoe** [comment]
Yea looking at it now that can't work. Most Zendesk objects have the ids of the child in the parent (eg ticket.requester) but not identities. The sideloaded objects exist in the cache though, so this workaround might do the trick:

```python
user_identities = defaultdict(set)
for user in zenpy_client.users.incremental(start_time=yesterday, include=['identities']):
    for identity in zenpy_client.cache.mapping['identity'].cache.values():
        user_identities[identity.user_id].add(identity)
    print(user_identities[user.id])
```

**Comment by facetoe** [comment]
>  if the cache isn't large enough, will identities be excluded

Yep, but you can set the size of it. By default it is 10,000, but you can increase like so:

```python
zenpy_client.set_cache_max('identity', 100000)
```

> how do you make sure that the identities you're retrieving from cache are from the current user

The identity object has a user id, and in the code above it creates a dict with user.id as the key, and a set of identity objects as the value. At the line `print(user_identities[user.id])` you can be sure that the identities in the set are linked to the current user. It is possible for race conditions etc where an identity is unlinked from the user by another system and it still exists in the cache, but this is a bit of an edge case.

If you want to be certain the identities are current you can use the `user.identities` endpoint:

```python
user_identities = zenpy_client.users.identities(id=user_id)
```

But that is way slower if you are processing many users.

Hope this helps!
