### ISSUE TITLE
No comment_count on incremental export 

### ISSUE THREAD

**Issue by BFunk86** [facetoe/zenpy#217]
While using the incremental ticket export API I noticed that it doesn't include the comment_count attribute, which is a part of the JSON returned from the API

**Comment by BFunk86** [comment]
Sorry I realized I had included it with the side load option

**Comment by facetoe** [comment]
Yep it is already supported in master, just need to push a new version to Pypi.

**Comment by facetoe** [comment]
OK I've pushed a new version.
