### ISSUE TITLE
show view

### ISSUE THREAD

**Issue by Axeish** [facetoe/zenpy#223]
How can I do the following from Zendesk API 👍 

Show View
GET /api/v2/views/{id}.json

Allowed For:
Agents
Using curl
curl https://{subdomain}.zendesk.com/api/v2/views/{id}.json \
  -v -u {email}:{password}
Example Response
Status: 200 OK

{
  "view": {
    "id": 25,
    "title": "Tickets updated <12 Hours",
    "raw_title": "{{dc.tickets_updated_last_12_hours}}",
    "description": "View for recent tickets",
    "active": true,
    "sla_id": 23842,
    "position": 3,
    "execution": { ... },
    "conditions": { ... },
    "restriction": { ... }
  }
}

**Comment by facetoe** [comment]
You can do this as follow:

```python
print(zenpy_client.views(id=114139576032))
```
