### ISSUE TITLE
users.create_or_update_many fails with APIException:"InvalidEndpoint"

### ISSUE THREAD

**Issue by lvisintini** [facetoe/zenpy#227]
Trying to update/create many users at the same time is failing:

```
zenpy = Zenpy(**settings.ZENDESK_CREDENTIALS)
zendesk_users = [ZendeskUser(**user) for user in users]
zenpy.users.create_or_update(zendesk_users)
```
results in 

``APIException: {"error": "InvalidEndpoint", "description": "Not found"}``

Apparently, the zenpy is trying to interact with zendeks on the following: api/v2/users/create_or_update_many.json**.json**

Notice the extra **.json** suffix.

This is happening in zenpy==2.0.1

**Comment by facetoe** [comment]
Thanks for the report @lvisintini, I've pushed a patch.
