### ISSUE TITLE
New release please?

### ISSUE THREAD

**Issue by lvisintini** [facetoe/zenpy#229]
Hi there,

Any change we could have a new release?

I obviously would not want to interfere with any release schedule that may be in place, but I'm very keen on  seeing https://github.com/facetoe/zenpy/commit/e9ae5bce8e739cb9676b1c539521302508af7b8e make it's way to pip.

Apologies if this is annoying or out of line

Cheers

**Comment by facetoe** [comment]
Hi @lvisintini, yes I can create a new release. I just need to do a bit more testing to ensure my patch for #225 doesn't break anything. Should be good to push one out tomorrow.

**Comment by lvisintini** [comment]
Thanks make. Looking forward to it.

**Comment by facetoe** [comment]
Ok new version released.
