### ISSUE TITLE
Support for Jira Integration API

### ISSUE THREAD

**Issue by aesmat1** [facetoe/zenpy#230]
https://developer.zendesk.com/rest_api/docs/services/jira

**Comment by facetoe** [comment]
I don't have an environment to develop against so it's a but tricky to implement.

**Comment by jorijinnall** [comment]
@facetoe I have an environment with JIRA to test. So I can help.

But I would like to have few guidelines on what needed to be changed/updated.

If I understand correctly how it works, we need to  : 
- In api.py : Create a class JiraApi
- In endpoint.py : Add a new Endpoint JiraEndpoint
- In mapping.py : Add JiraObjectMapping

Do you you see anything else ?

**Comment by facetoe** [comment]
Yep that's pretty much it. Also need to get the JSON for a Jira "link", save it in the specifications directory as "link.json" and run the "gen_classes.py" tool which will create the object. Once it's created you can add it to the mapping.

Let me know if you run into any issues. Thanks for the help!

**Comment by jorijinnall** [comment]
Hi @facetoe ,

Thank you for your recommandation, and sorry for the delay to check this.

I started the changes and uploaded to my own repo before merge into yours (https://github.com/jorijinnall/zenpy/commit/54868e319641ae305bde09e9568c2a6bc605faf7)

I have 2 questions : 
1) I am not able to run gen_classes.py. Do I miss something ?
`➜  zenpy git:(master) python tools/gen_classes.py --spec-path specification --doc-json tools/doc_dict.json --out-path zenpy/lib/
Traceback (most recent call last):
  File "tools/gen_classes.py", line 417, in <module>
    namespace='core')
  File "tools/gen_classes.py", line 404, in process_specification_directory
    with Pool() as pool:
AttributeError: __exit__`

2) In endpoint, I added the line below
`jiralink = PrimaryEndpoint('services/jira/links/{}')`

But in Zendesk, by default it is /api/v2/...
Here, in this part of the API, there is no version : /api/services/... (see Zendesk doc https://developer.zendesk.com/rest_api/docs/services/jira)
Will it be an issue to manage ?

**Comment by facetoe** [comment]
Ahh yes, I should update the docs, the `gen_classes.py` tool requires Python3.

For the api prefix issue, you should be able to override the `api_prefix` attribute in the `__init__` method of your JiraApi class and set it to `/api/`. I think that should be enough, let me know if you have any issues.

**Comment by facetoe** [comment]
I left a couple of comments on your branch. Basically, Zenpy cheats quite a bit by relying on a naming convention that maps to the JSON keys the Zendesk API returns. It's possible to work around it, but it's much easier to follow the convention. This is why it is best to call the specification file `link.json` etc.

**Comment by jorijinnall** [comment]
Thank @facetoe 
I updates my branch. I think I am almost finished.
https://github.com/jorijinnall/zenpy/commit/1ddfd83f155fef757fac341ca1b10c761e463a02

For my tests, I made a class Zendesk on my local script to initialize zenpy client
`    zendesk = Zendesk()
    print(zendesk.zenpy_client.link(ticket_id=253457))`

I can get a Link now. But I have 2 remaining questions :
- The link result is `<zenpy.lib.generator.ZendeskResultGenerator object at 0x10b24b6d8>`
The JSON looks correct but why I dont have a Link object as a result ? I tried to review and understand but I don't find what I missed
JSON result : 
`{'links': [{'id': 6440994, 'ticket_id': '253457', 'issue_id': '25186', 'issue_key': 'ENG-4180', 'url': 'https://vadesecure.zendesk.com/api/services/jira/links/6440994', 'created_at': '2018-07-03T18:39:41.000Z', 'updated_at': '2018-07-03T18:39:41.000Z'}], 'total': 1}`

2) I tried to setup a links.show endpoint but I don't figure out what I should do : 
I tried to add to endpoint.py : 
`links.show = SecondaryEndpoint('services/jira/links/%(id)s')`

But I get this : 
`Traceback (most recent call last):
  File "zenpy_test.py", line 39, in <module>
    print(zendesk.zenpy_client.link.show(id=6440994))
AttributeError: 'LinkApi' object has no attribute 'show'`

For info, my test code : 
`class Zendesk():
    def __init__(self):
        # Zenpy accepts an API token
        #We do a split to remove the ""
        creds = {
            'email' : ZENDESK_USER.split('/')[0],
            'token' : ZENDESK_TOKEN,
            'subdomain': 'mysubdomain'
        }
        self.zenpy_client = Zenpy(**creds)

if __name__ == "__main__":
    zendesk = Zendesk()
    print(zendesk.zenpy_client.link(ticket_id=253457))
    print(zendesk.zenpy_client.link(ticket_id=253457)._response_json)
    print(zendesk.zenpy_client.link.show(id=6440994))`
