### ISSUE TITLE
merge command on tickets hitting api exception 

### ISSUE THREAD

**Issue by gutdraw** [facetoe/zenpy#231]
it seems zendesk api may have shifted data types or something

zenpy_client.tickets.merge(source=22598883,target=22597915,target_comment="",source_comment="test")

APIException                              Traceback (most recent call last)
<ipython-input-66-ad6cc9ae4ed2> in <module>()
      1 
----> 2 zenpy_client.tickets.merge(source=22598883,target=22597915,target_comment="",source_comment="test")

/anaconda2/lib/python2.7/site-packages/zenpy/lib/util.pyc in inner(*args, **kwargs)
    103             new_args = [id_of(arg) for arg in args]
    104             new_kwargs = {k: id_of(v) for k, v in kwargs.items()}
--> 105             return func(*new_args, **new_kwargs)
    106 
    107         return inner

/anaconda2/lib/python2.7/site-packages/zenpy/lib/api.pyc in merge(self, target, source, target_comment, source_comment)
   1016         return TicketMergeRequest(self).post(target, source,
   1017                                              target_comment=target_comment,
-> 1018                                              source_comment=source_comment)
   1019 
   1020 

/anaconda2/lib/python2.7/site-packages/zenpy/lib/request.pyc in post(self, target, source, target_comment, source_comment)
    264         )
    265         url = self.api._build_url(self.api.endpoint.merge(id=target))
--> 266         return self.api._post(url, payload=payload)
    267 
    268     def put(self, api_objects, *args, **kwargs):

/anaconda2/lib/python2.7/site-packages/zenpy/lib/api.pyc in _post(self, url, payload, **kwargs)
     84                                   timeout=self.timeout,
     85                                   headers=headers,
---> 86                                   **kwargs)
     87         return self._process_response(response)
     88 

/anaconda2/lib/python2.7/site-packages/zenpy/lib/api.pyc in _call_api(self, http_method, url, **kwargs)
    133                 response = http_method(url, **kwargs)
    134 
--> 135         self._check_response(response)
    136         self._update_callsafety(response)
    137         return response

/anaconda2/lib/python2.7/site-packages/zenpy/lib/api.pyc in _check_response(self, response)
    272                     raise TooManyValuesException(json.dumps(_json), response=response)
    273                 else:
--> 274                     raise APIException(json.dumps(_json), response=response)
    275             except ValueError:
    276                 response.raise_for_status()

APIException: {"error": {"message": "You passed an invalid value for the ids attribute. Invalid parameter: ids must be an array", "title": "Invalid attribute"}}

**Comment by facetoe** [comment]
OK fixed, was a bug in Zenpy.

**Comment by gutdraw** [comment]
thanks much and i presume version 2.04 in PyPi contains the fix?
