### ISSUE TITLE
Not able to create a private Ticket

### ISSUE THREAD

**Issue by manda986** [facetoe/zenpy#232]
Hi there! I'm looking to create a private Ticket on behalf of a user. However, it seems that calling the `tickets.create()` method with `is_public=False` doesn't set that field, and it ends up sending an email to that user (which I don't want). I want to avoid having to set a submitter. Here's a sample call:

```
zenpy_client.tickets.create(
        Ticket(
            subject="Ticket created for John Smith",
            description="foo",
            is_public=False, 
            requester=User(name="John Smith", email="john.smith@foo.com"))
    )
```

Thanks in advance!

**Comment by facetoe** [comment]
Hi, 

You can achieve this as follows:

```
zenpy_client.tickets.create(Ticket(subject='something', comment=Comment(body='somethingsomthing', public=False)))
```

Hope this helps.

**Comment by facetoe** [comment]
BTW, `is_public` is read only and means something a bit different (https://developer.zendesk.com/rest_api/docs/core/tickets):

> Is true if any comments are public, false otherwise
