### ISSUE TITLE
passing a empty string for `email` field in search API does bad things

### ISSUE THREAD

**Issue by boknows** [facetoe/zenpy#233]
We encountered this bug yesterday.  It turned out that one of our clients had an empty string set as their email.  When we went to a page on our site that fetches Zendesk tickets for that client, Zenpy took the empty string and took that to mean "Get ALL tickets for ALL clients".  This ground our webserver to a halt.

**Comment by facetoe** [comment]
Can you provide the search that you are using?

**Comment by boknows** [comment]
`for ticket in zendesk_api.search(
  email,
  type='ticket',
  sort_by='updated_at',
  sort_order='desc'):`

**Comment by boknows** [comment]
We're passing in `email` from the User object in our system.  This particular time, it was an empty string (which is a bit of bad practice on our part).

**Comment by facetoe** [comment]
I don't think this is a bug in Zenpy, it formatted the parameters correctly and passed them through to Zendesk. If you enter the equivalent query in the search bar in Zendesk you get the same result: "type:ticket order_by:created sort:desc".

So maybe a bit unexpected, but not a bug :)
