### ISSUE TITLE
end_user() uses a wrong endpoint

### ISSUE THREAD

**Issue by breki** [facetoe/zenpy#234]
end_user() method uses `users` endpoint, but it should be `end_users` (see [EndUser docs](https://developer.zendesk.com/rest_api/docs/core/end_user)).

Why is this important? The end users do not have access to `users` endpoint in Zendesk REST API (only agents do), so an end user must use `end_user` endpoint to access and modify their data. Right now that is not possible using Zenpy.

**Comment by facetoe** [comment]
Thanks for the report @breki, I've fixed up the bug.
