### ISSUE TITLE
Duplicate tickets in SearchResultGenerator

### ISSUE THREAD

**Issue by asherkinyon** [facetoe/zenpy#235]
I'm having a problem with zenpy ticket searches yielding duplicate tickets. 

When I feed the search generator a query, for instance: 

`results = zenpy.search(query="tags:testing_123 status:open", type='ticket')` 

it returns a SearchResultGenerator that has the correct, expected `count` attribute (e.g. 40 unique tickets). 

However, when I iterate over the SearchResultGenerator using a standard for loop, appending each ticket into a DataFrame, the resultant DataFrame sometimes has a substantial amount of duplicate tickets. I'm thinking that I'm not using your SearchResultGenerator correctly? Here's a sample that produces the duplicate error:

    results = zenpy.search(query="tags:testing_123 status:open", type='ticket')
    
    for ticket in results:
          ticket_list = ticket_list.append(pd.DataFrame(columns=['ticket'], data=[ticket]))

Thanks for your help!

**Comment by facetoe** [comment]
Hi @asherkinyon,

Yes it is possible that placing all the search parameters n the query is leading to funny results. Do you get the same result when running:

```python
generator = zenpy_client.search(type='ticket', tags=['testing_123'], status='open')
assert len(generator) == len(list(generator)), "Tis a bug"
```

**Comment by asherkinyon** [comment]
Hi @facetoe - thank you for the quick response! I think I found my issue. When grouping parameters for the "and" operator, you have to wrap them in quotes, like tags:"testing_123 other_tag". I wasn't doing this, so I think Zendesk was interpreting the other_tag as a keyword query instead of a tag, leading to some weird results.

I retried my queries with the correct quote syntax and it seems to be working. Hopefully that was the issue. Thanks again for the response.

**Comment by facetoe** [comment]
No worries, glad it's working.
