### ISSUE TITLE
SSL certificate error

### ISSUE THREAD

**Issue by mordechaia** [facetoe/zenpy#238]
Hi,
when i'm using your module im getting 
SSLError: HTTPSConnectionPool(host='{company name}.zendesk.com', port=443): Max retries exceeded with url: /api/v2/tickets.json (Caused by SSLError(CertificateError("hostname 's{company name}.zendesk.com' doesn't match either of 'ssl385002.cloudflaressl.com', '*.zdorigin.com', 'zdorigin.com'",),)).
if i try to set my session with ignore verfiy ssl, im getting 
TTPError: 403 Client Error: Forbidden for url: https://{company name}.zendesk.com/api/v2/tickets.json

Api calls with curl working well same for browsers. 
do you have any suggestions?

**Comment by mordechaia** [comment]
thanks!!

**Comment by GlennTng** [comment]
Hi,

I faced the same issue as OP and it seems like the link you've shared above is no longer available. Is there any other way to resolve this? 

> File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\requests\adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='[company].zendesk.com.zendesk.com', port=443): Max retries exceeded with url: /api/v2/search.json?query=type%3Aticket%20status%3Aopen&filter%5Btype%5D=ticket (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1129)')))

**Comment by GlennTng** [comment]
> Hi,
> 
> I faced the same issue as OP and it seems like the link you've shared above is no longer available. Is there any other way to resolve this? Below is the error that I am receiving
> 
> > File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\requests\adapters.py", line 563, in send
> > raise SSLError(e, request=request)
> > requests.exceptions.SSLError: HTTPSConnectionPool(host='[company].zendesk.com.zendesk.com', port=443): Max retries exceeded with url: /api/v2/search.json?query=type%3Aticket%20status%3Aopen&filter%5Btype%5D=ticket (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1129)')))

Just to update, managed to make it work. Dumb me was using the entire link including the domain as my subdomain credentials.

**Comment by FroostySnoowman** [comment]
> 

Hey, sorry to bother you, can you show me what you had previously and what you did to fix it? I'm having the same issue.

**Comment by FroostySnoowman** [comment]
> > Hi,
> > I faced the same issue as OP and it seems like the link you've shared above is no longer available. Is there any other way to resolve this? Below is the error that I am receiving
> > > File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\requests\adapters.py", line 563, in send
> > > raise SSLError(e, request=request)
> > > requests.exceptions.SSLError: HTTPSConnectionPool(host='[company].zendesk.com.zendesk.com', port=443): Max retries exceeded with url: /api/v2/search.json?query=type%3Aticket%20status%3Aopen&filter%5Btype%5D=ticket (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1129)')))
> 
> Just to update, managed to make it work. Dumb me was using the entire link including the domain as my subdomain credentials.

Hey, sorry to bother you, can you show me what you had previously and what you did to fix it? I'm having the same issue.
