### ISSUE TITLE
Support sideloads in SecondaryEndpoints

### ISSUE THREAD

**Issue by ppchaigneau** [facetoe/zenpy#239]
Hi,

I'm trying to get the solved date for a list of tickets in a view.
I included the fields below in my query, but the updated_at field is giving literally the last update and the tickets are auto closed so I got the closed date and not the solved one.
In my view (when I setup it in Zendesk backoffice) I got the option to chose the solved date but in the zenpy/ticket.json I don't see the option to get this filed. Any idea?

`def get(self, view_id):
    ##creds['token'] = users[auth.username()]
    zenpy_client = Zenpy(**creds)
    tickets = zenpy_client.views.tickets(int(view_id))
    payload = []
    for ticket in tickets:
        aux = {"id": ticket.id,
               "status":ticket.status,
               "satisfaction":ticket.satisfaction_rating,
               "subject": ticket.subject,
               "requester":ticket.requester_id,
               "request_date":ticket.created_at,
               "updated_dates":ticket.updated_at,
               "channel":ticket.via.channel,
               "tag":ticket.tags,
               "type":ticket.type,
               "last_comment":ticket.description
              }
        payload.append(aux)
    return payload`

I have seen this in a Zendesk community post, but it doesn't seem to work if I do ticket.dates:
https://support.zendesk.com/hc/en-us/community/posts/115000867608-Need-Solved-Date-information-
{  
   "ticket":{  
      ...
      "dates":{  
         "assignee_updated_at":"2017-02-07T14:01:23Z",
         "requester_updated_at":"2017-02-07T13:59:55Z",
         "status_updated_at":"2017-03-08T08:01:50Z",
         "initially_assigned_at":"2017-02-07T13:59:55Z",
         "assigned_at":"2017-02-07T13:59:55Z",
         "solved_at":"2017-02-07T14:01:23Z",
         "latest_comment_added_at":"2017-02-07T14:01:18Z"
      },
      ...
   }
}

Thanks Pierre-Philippe

**Comment by facetoe** [comment]
Hi @ppchaigneau, you can sideload dates via the ticket endpoint:

```python
ticket = zenpy_client.tickets(id=<ticket_id3>, include="dates")
print(ticket.dates['solved_at'])
```

Currently the view/tickets endpoint does not support sideloading but I will add support when I get the chance.
