### ISSUE TITLE
How to bulk update tags on tickets after doing bulk ticket creation?

### ISSUE THREAD

**Issue by Black-Milk** [facetoe/zenpy#24]
I'm following your `job status` example for bulk ticket creation; however, I'm not sure how I would then update the ticket tags or ticket descriptions using the generator object. The documentation is rather sparse and does not indicate how to do this.

**Comment by facetoe** [comment]
I know the documentation definitely needs work! I hope to get some more done soon.

You can set the tags and description when creating the ticket by passing them as parameters when creating the Ticket object:

```python
ticket = Ticket(subject='test', description='testing', tags=['sometag', 'anothertag'])
```

Unfortunately my test Zendesk account has expired so I can't test this, however I believe you can poll the JobStatus object to retrieve the ticket ID's as they are created. For example (untested):

```python
tickets_created = 10
ticket_ids = []
job_status = zenpy.tickets.create([Ticket(subject="Ticket%s" % i, description="Bulk")for i in range(0, tickets_created)])
js = zenpy.job_status(id=job_status.id)
while js.index < tickets_created:
    for status in js.results:
        if status.success:
            ticket_ids.append(status.id)
        else:
            print status.details

    sleep(1)

for ticket in zenpy.tickets(ids=ticket_ids):
    # Do things with tickets here
```

Unfortunately Zendesk doesn't return a complete object when using bulk creation, which would make things a little easier. 

Also, you might want to pull the latest version as I've fixed a small bug with the Status object.  

Let me know if you have any trouble!

**Comment by Black-Milk** [comment]
Thank you!
