### ISSUE TITLE
How to set assignee by email id to a  ticket using Zenpy python client library

### ISSUE THREAD

**Issue by savi-ganesh** [facetoe/zenpy#240]
0
down vote
favorite
I am integrating Zendesk ITSM API in my python library using Zenpy client.

For creating ticket using zenpy client , I can set reporter of ticket by email id, but for assignee I am not able to set assignee by email id.

This is the code I have tried so far.

            ticket_payload = Ticket(
                description="some description",
                type="task",
                priority="high",
                status="open"
            )

            ticket_payload.requester = User(email="requester1@gmail.com"])
            ticket_payload.assignee = User(email="assignee1@gmail.com")

            response = self.zenpy_client.tickets.create(ticket_payload)
Response ticket I get has reporter set, but assigneee is None.

If I pass id along with the email as

ticket_payload.assignee = User(id= 354876354,email="assignee1@gmail.com")
then it works and I can see assignee is set to ticket. But this is not required for reporter.

Is this the defult behaviour of zenpy, or am I missing something?

**Comment by facetoe** [comment]
This is how the Zendesk API works. When creating tickets, for some of these User attributes you can only pass the email address, and others you need the id. If you execute the call via curl you can see that it actually ignores the `assignee` parameter completely:

```
curl https://domain.zendesk.com/api/v2/tickets.json   -d '{"ticket": {"assignee": {"email": "example@example.com"}, "id": null, "description": "desc"}}'   -H "Content-Type: application/json" -v .. auth stuff -X POST
```

```
< X-Zendesk-API-Warn: Removed restricted keys ["ticket.assignee.email", "ticket.assignee", "ticket.id"] from parameters according to whitelist
```

**Comment by savi-ganesh** [comment]
Thanks for clarification...
