### ISSUE TITLE
ITSM : Zendesk Request vs Ticket

### ISSUE THREAD

**Issue by savi-ganesh** [facetoe/zenpy#241]
Zendesk has both a Tickets API and a Requests API. A ticket is an agent's perspective on a ticket. A request is an end user's perspective on a ticket. 
For managing tickets, Zenpy provides a  "Ticket" object. 
For Request (end users perspective) I could not find any object as "Request".

is the Ticket and Request same thing? should I go with "Ticket"  for ITSM.

**Comment by facetoe** [comment]
Yep, Ticket should do the job.
