### ISSUE TITLE
Query organization membership by organization id

### ISSUE THREAD

**Issue by tvallois** [facetoe/zenpy#246]
Hey,

First, thank you for the amazing job there. I tried to filter organization membership by organization id during the query like GET /api/v2/organizations/{organization_id}/organization_memberships.json in https://developer.zendesk.com/rest_api/docs/core/organization_memberships but it doesn't do anything. 
Here is my logic:
`    for organization_membership in zenpy_client.organization_memberships(organization_id=360038655793):
       print(organization_membership)`
Is it normal or not?

Thanks !

**Comment by facetoe** [comment]
Can you post your code?

**Comment by tvallois** [comment]
y my bad. I was updating my ticket when you send your message :)

**Comment by facetoe** [comment]
Ahh, yes this is a bit of a gotchya. The keyword argument has to be named `id`, not `organization_id`. Give it a go with `id` and it should work as expected.

**Comment by tvallois** [comment]
I've already tried with id.
`    user_organization = zenpy_client.organizations.external('0878da0e-1eaf-4cd6-bac9-abcad8222263')
    user_organization = list(user_organization)
    print(user_organization[0])
    for organization_membership in zenpy_client.organization_memberships(id=360038655793):
        print(vars(organization_membership))`

first print return Organization(id=360038655793)
second raise RecordNotFoundException

**Comment by facetoe** [comment]
Ahh my bad, the correct code is:

```python
for organization in zenpy_client.organizations():
    for membership in zenpy_client.organizations.organization_memberships(organization):
        print(organization)
```

`organizations.organization_memberships()` takes either an Organization object or an organization_id.

**Comment by tvallois** [comment]
Perfect thank you very much @facetoe
