### ISSUE TITLE
Timeout during bulk insert

### ISSUE THREAD

**Issue by tvallois** [facetoe/zenpy#249]
Hi,

I have issues to insert multiple organizations with bulk insert. I have 100 lists of 100 organization objects.
It raises an exception from requests library:
  File "/home/tvallois/dev/taskworker/taskworker/tasks/ticketing/services.py", line 56, in import_zendesk_organizations
    job_status = zenpy_client.organizations.create(organizations)
  File "/home/tvallois/dev/taskworker/env/lib/python3.5/site-packages/zenpy/lib/api.py", line 421, in create
    return CRUDRequest(self).post(api_objects)
  File "/home/tvallois/dev/taskworker/env/lib/python3.5/site-packages/zenpy/lib/request.py", line 82, in post
    return self.api._post(url, payload)
  File "/home/tvallois/dev/taskworker/env/lib/python3.5/site-packages/zenpy/lib/api.py", line 92, in _post
    **kwargs)
  File "/home/tvallois/dev/taskworker/env/lib/python3.5/site-packages/zenpy/lib/api.py", line 125, in _call_api
    response = http_method(url, **kwargs)
  File "/home/tvallois/dev/taskworker/env/lib/python3.5/site-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/tvallois/dev/taskworker/env/lib/python3.5/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/tvallois/dev/taskworker/env/lib/python3.5/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/tvallois/dev/taskworker/env/lib/python3.5/site-packages/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: None: None

organizations is a list of 100 organizations object.
I tried to increase the timeout from 60 to 90 seconds but it didn't work, problem is still there.

I'm not sure this issue come from Zenpy.

**Comment by facetoe** [comment]
Hmm, yea looks like a network/Zendesk issue. Might be worth trying to submit smaller batches and see if that helps.

**Comment by tvallois** [comment]
Nope, same issue. I reduce batches from 100 to 60. I've the same issue when i try to batch delete organizations. Same when i try to get all organizations and i don't receive all results just by doing:
```
for user in zenpy_client.users():
    delete_list.append(user)
print(user)
```

**Comment by facetoe** [comment]
Yea sounds like you could be having some issues with the network.

**Comment by tvallois** [comment]
Seems not to be a network issue. When i send more requests than the ratelimit (400 here), Zendesk doesn't send any status code and the error appear.

**Comment by facetoe** [comment]
Unfortunately there isn't much I can do to help, this error is thrown deep in the `requests` package. It looks like it is timing out waiting for the response from the POST. I guess you could try verifying if the same thing happens with `curl`, or using another library apart from requests to rule that out. 

Best of luck.

**Comment by tvallois** [comment]
What about adding a try except block on http_method function in _call_api to retry after some seconds? I've tested with one minute. It seems to avoid the probelm.

**Comment by facetoe** [comment]
You can catch the `ReadTimeout` in your application code, but it's not a good idea for me to swallow that exception in Zenpy.

**Comment by tvallois** [comment]
Yeah that was my first shot. Can i ask you also why did you put 10 seconds for the check of time_since_last_call in _ratelimit function?

**Comment by facetoe** [comment]
Hmm, that was added in this PR - https://github.com/facetoe/zenpy/pull/99, there are some more details there. I'm not sure if that will help in your case though as the error is thrown after you have submitted your POST request and are reading the response (from the look of the stacktrace). 

You might be able to try configuring requests to transparently retry those requests on failure, something like - https://www.peterbe.com/plog/best-practice-with-retries-with-requests. You can then pass that Session object to Zenpy.

**Comment by tvallois** [comment]
Yep Zendesk seems not to answer. I've reduced this value from 10 to 5 which looks good. Look like a sleep before each request. What about a parameter just like ratelimit in Zenpy object to manage that?

**Comment by facetoe** [comment]
Yes we could make that value configurable with a default of 10, no harm in that.

**Comment by tvallois** [comment]
I'll do a pull request for that if you want.

**Comment by facetoe** [comment]
Pull requests always welcome :)
