### ISSUE TITLE
Ticket form property on Ticket

### ISSUE THREAD

**Issue by dangerwheeler** [facetoe/zenpy#25]
Great library.

I'd like to set a ticket form id when I create a ticket. Doesn't look like this is currently possible. Looking at https://developer.zendesk.com/rest_api/docs/core/tickets, I think it's just: ticket_form_id.

**Comment by facetoe** [comment]
Hi @dangerwheeler, 

I've added an issue (#26) to properly support ticket forms, however I can suggest a workaround that might work for you now, although I can't test it as I don't have an enterprise account. When the `Ticket` object (or any api object) is serialized into JSON for submission to Zendesk all of it's attributes are serialized as well, so it *should* be as simple as just setting that attribute, eg:

```python
some_ticket.ticket_form_id = 10
```

Let me know if this works and I'll add it to the docs.
