### ISSUE TITLE
Python crushes without reason on ticket updating

### ISSUE THREAD

**Issue by LPCBullBets** [facetoe/zenpy#251]
Hi. 

First, thanks for the help. I'm having problems when I update a ticket with a new comment. The app crush with out any error code. My terminal close / crush when the line *self.__zenpy_client.tickets.update(ticket)* is executed. 

If I check in Zendesk, the ticket is updated, but my terminal (MAC) closed/crushed. I reached only one time to the next line *input('updated')*. When I repeated (with any change in the source code), the result was the same: crush.

If I execute line by line using python command, work fine.

Any idea about what is happening?

My function: 

`def __printNotice(self, created_ticket, body, files):

		try:
			# Delete html codes
			body 					= self.__deleteHtml(body)
			# Upload files to zendesk
			tokens 					= []
			for file in files:
				upload_instance 	= self.__zenpy_client.attachments.upload(file)
				tokens.append(upload_instance.token)
			# Ask ticket from Zendesk
			ticket 			= self.__zenpy_client.tickets(id=created_ticket.ticket.id)
			# Create the comment with all attachments
			if(len(tokens) == 0):
				ticket.comment 	= Comment(body=body, public=True)
			else:
				ticket.comment 	= Comment(body=body, uploads=tokens, public=True)
			input("updating")
			# Update the ticket
			self.__zenpy_client.tickets.update(ticket)
			input('updated')
			return

		except Exception as e:
			(...)
`
created tickets is the returned object from -> zenpy_client.tickets.create() function.

**Comment by facetoe** [comment]
There area  few issues with your code. First, I'm not sure why you are using the [input](https://docs.python.org/3/library/functions.html#input) builtin, maybe you want `print` instead? Also, your `except Exception as e:` line is swallowing any error that does occur. What happens if you remove the try/catch and `input` lines and run it again?

**Comment by LPCBullBets** [comment]
I used `input` function to check in what line I had the problem, cuz if I use print, I can't see nothing when the terminal crush.

I forced an error by changing "`zenpy_client.tickets(id=created_ticket.ticket.id`" to "`ticket(created_ticket.ticket)`" and the system inform about the error. 

I tried with out try/catch and `input`, and I got the same result.

**Comment by LPCBullBets** [comment]
Hi @facetoe !
I have tested the module independently, outside the application and it works correctly. The error only occurs when it is executed from the main application (a very large application). I can't understand why, but maybe is not a `zenpy` problem.

I think, we can close the issue. But if you have any idea about this issue, I will be glad to listen it.

Thanks for your help.

**Comment by LPCBullBets** [comment]
Finally, I found the problem.

The call `zenpy_client.tickets.update(ticket)` fails when the class where this function is codified, is instantiated as global inside other class. The action is executed (update the ticket) but python (v3.6) crash without error description.

I hope this topic can help to somebody in the future.

Thanks!

**Comment by facetoe** [comment]
Ahh glad you found the issue! Sounds like you might have found a bug in the Python interpreter?

**Comment by LPCBullBets** [comment]
It seems ! :-)
