### ISSUE TITLE
How to get the satisfaction_ratings for a single ticket?

### ISSUE THREAD

**Issue by aesmat1** [facetoe/zenpy#258]
Hello,

I'm doing an incremental extraction of Zendesk tickets using Zenpy, and I need to extract the satisfaction_ratings for changed tickets only. How can I pass the ticket number to the  satisfaction_ratings function? I have the following code, but I get the whole list for all tickets:

`for CSR in zenpy_client.satisfaction_ratings(sort_order='desc'):`

How can I pass a single ticket ID to get the satisfaction_ratings for it?

Regards,
Ahmed Esmat

**Comment by facetoe** [comment]
The Zendesk API does not seem to support retrieving satisfaction ratings for an individual ticket, however it you might be able to use the `start_time` and `end_time` parameters to help you find the relevant rating - https://developer.zendesk.com/rest_api/docs/core/satisfaction_ratings#list-satisfaction-ratings. Perhaps building a cache of satisfaction ratings created after a certain point in time and checking it as you process your tickets, or something like that.
