### ISSUE TITLE
Deleted tickets while doing incremental extract

### ISSUE THREAD

**Issue by aesmat1** [facetoe/zenpy#259]
Wile doing an incremental extract using the code:

```
yesterday = datetime.datetime.now(datetime.timezone.utc) - datetime.timedelta(days=1)
result_generator = zenpy_client.tickets.incremental(start_time=yesterday)
for ticket in result_generator:
...
...
	ticket_comments = zenpy_client.tickets.comments(ticket.id)

```

I am getting the following error:

```
Traceback (most recent call last):
  File "zenex-inc.py", line 214, in <module>
    ticket_comments = zenpy_client.tickets.comments(ticket.id)
  File "/usr/local/lib/python3.6/site-packages/zenpy/lib/api.py", line 913, in comments
    return self._query_zendesk(self.endpoint.comments, 'comment', id=ticket_id)
  File "/usr/local/lib/python3.6/site-packages/zenpy/lib/api.py", line 240, in _query_zendesk
    return self._get(url=self._build_url(endpoint(*endpoint_args, **endpoint_kwargs)))
  File "/usr/local/lib/python3.6/site-packages/zenpy/lib/api.py", line 95, in _get
    response = self._call_api(self.session.get, url, timeout=self.timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/zenpy/lib/api.py", line 132, in _call_api
    self._check_response(response)
  File "/usr/local/lib/python3.6/site-packages/zenpy/lib/api.py", line 267, in _check_response
    raise RecordNotFoundException(json.dumps(_json), response=response)
zenpy.lib.exception.RecordNotFoundException: {"error": "RecordNotFound", "description": "Not found"}
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

How to test if a ticket is deleted?

**Comment by facetoe** [comment]
Hmm, yea that's unfortunate. I'd hazard a guess that this is a bit of a race condition where some other process deleted the ticket out from under you. There isn't really a way to test for this that I can think of, you can only catch the `RecordNotFoundException` and continue.

**Comment by jwjordan** [comment]
It might be bad form to comment on this old issue, but it appears that this might actually be fixable now since the Zendesk API now supports "exclude_deleted" as an arg to incremental (https://developer.zendesk.com/api-reference/ticketing/ticket-management/incremental_exports/#exclude_deleted). I am not a very good Python developer or I'd attempt to contribute, but I did check if that arg was already supported in Zenpy and as best I can tell, it is not yet.

**Comment by jwjordan** [comment]
Also, I'll add that you can avoid the error above by checking that the ticket's status is not "deleted" and if it is, skip it. In my code I accomplished that with this:

```
# Check if the ticket status is deleted
if ticket.status == "deleted":
     print(f"Skipping deleted ticket: {ticket.id}")
     continue
```
