### ISSUE TITLE
Properly support Ticket Forms. 

### ISSUE THREAD

**Issue by facetoe** [facetoe/zenpy#26]
https://developer.zendesk.com/rest_api/docs/core/ticket_forms

**Comment by originalcheng** [comment]
hey facetoe, can you show how to call "GET /api/v2/ticket_forms.json" using version 1.2.2?

**Comment by facetoe** [comment]
Hi @originalcheng, I'm afraid support for ticket forms has not been implemented as I don't have an enterprise account.

I could have go at implementing support and maybe you could test to verify that it works?

**Comment by originalcheng** [comment]
@facetoe it does seem to work using your Api class and passing in your PrimaryEndpoint class with object_type='ticket_forms'. Couldn't figure out how to use 'side_load' though.

**Comment by facetoe** [comment]
Excellent! PRs welcome :) No need to worry about sideloads, it doesn't look like ticket forms use them - https://developer.zendesk.com/rest_api/docs/core/side_loading#supported-endpoints.
