### ISSUE TITLE
Add html_body functionality to Ticket api object

### ISSUE THREAD

**Issue by DBa19** [facetoe/zenpy#261]
Hi, 

After a bit of research, it's apparently possible to add html_body to comments and I assume creating tickets, even though it's not explicitly researched in the official API:

https://support.zendesk.com/hc/en-us/community/posts/217875987-Rich-Text-Formatting-via-API-email

Is it possible to add this feature to zenpy as well? - I've looked over the code and I didn't see it available.

Thanks,

**Comment by facetoe** [comment]
Yep this works already:

```python
zenpy_client.tickets.create(Ticket(subject='Html',
                                   comment=Comment(body='The smoke is very colorful',
                                                   html_body='<h2>The smoke is <i>very</i> colourful</h2>')))
```

Might be worth adding an example to the README.

**Comment by libra17951** [comment]
Thank you so much!
your answer is so great for me!

**Comment by netllama** [comment]
It doesn't seem like the `html_body` parameter is documented anywhere yet?
