### ISSUE TITLE
Using 'minus' ticket search

### ISSUE THREAD

**Issue by dking010** [facetoe/zenpy#262]
I've been having trouble using the 'minus' condition when searching tickets. For example, if I want to search for -via:'web', I'm not sure how to use your keyword of minus to put - into the search. Hope this is an ok means for this type of question - spent a bunch of time on this and couldn't figure it out.

**Comment by facetoe** [comment]
Hi @dking010, I think this will do the trick:

```python
zenpy_client.search(minus='via:web')
```
I don't think you need the quotes in this case.

**Comment by dking010** [comment]
Thanks, that worked great! And thanks for the great tool, this has been very helpful.
