### ISSUE TITLE
Ticket skips in play mode

### ISSUE THREAD

**Issue by caduri** [facetoe/zenpy#263]
Hi, the doc_dict.json has the definition of ticket_skips but the code doesn't support it

are you planning on supporting it anytime soon?

**Comment by facetoe** [comment]
I'll implement this when I get the time - https://developer.zendesk.com/rest_api/docs/core/ticket_skips

**Comment by caduri** [comment]
That would be awesome! Thanks!

**Comment by facetoe** [comment]
Implemented Skips.
