### ISSUE TITLE
Get python datetime instead of datetime string from object properties like ticket.created_at

### ISSUE THREAD

**Issue by joelhellman** [facetoe/zenpy#266]
After I read the docs about some object properties implemented as attributes:
http://docs.facetoe.com.au/api_objects.html?highlight=date#object-properties

I expected to resolve something like 
```
>>> ticket = client.tickets(id=123)
>>> type(ticket.created_at) 
<class 'datetime.datetime'>
```

But the actual behavior is 
```
>>> ticket = client.tickets(id=123)
>>> type(ticket.created_at) 
<class 'str'>
```

Is this behavior supported?

**Comment by facetoe** [comment]
`created_at` is the raw string returned by Zendesk, `created` is implemented as a property that returns a datetime object:

```python
ticket = zenpy_client.tickets(id=6800)
print(type(ticket.created))
```
