### ISSUE TITLE
Support for create_many for organization_memberships

### ISSUE THREAD

**Issue by ville-solja** [facetoe/zenpy#269]
According to Zendesk API documentation they support create_many for organization_membership. Would it be possible to implement this in zenpy as well?

Atleast according to zenpy documentation only create and delete operations are currently supported.

**Comment by facetoe** [comment]
You can pass a list of memberships to the `create` endpoint:

```python
memberships = [
    OrganizationMembership(user_id=27, organization_id=88),
    OrganizationMembership(user_id=1, organization_id=89)
]
r = zenpy_client.organization_memberships.create(memberships)
print(r)
```

**Comment by ville-solja** [comment]
Thanks!

Now that i looked closer to the zenpy documentation there indeed is a part about this 

"Create (POST) one or **more** API objects"
