### ISSUE TITLE
I'm a useless noob...

### ISSUE THREAD

**Issue by opsmgr3774** [facetoe/zenpy#271]
I've been attempting to pull all of our Zendesk data into splunk and thought that your API might be a solid way to do it.  All the Python and API knowledge I have I learned in the last week.  Im using the following script to pull ticket data, but the include statement doesnt seem to be working.  I need to get full data on every ticket in the system.  I seem to get only partial data and it doesnt match up the users and groups to the id numbers.  

import sys, os, traceback
import csv
from zenpy import Zenpy
import datetime
import json

creds = {
    'email' : '<email>',
    'token' : '<token>,
    'subdomain' : '<token>'
}

zenpy_client = Zenpy(**creds)

timespan = datetime.datetime.now() - datetime.timedelta(hours=1)

result_generator = zenpy_client.tickets.incremental(start_time=timespan, include=['users','groups','organizations','comment_events','comments'])
for ticket in result_generator:
    sys.stdout.write(ticket.to_json())

**Comment by facetoe** [comment]
Unfortunately not all the includes are supported for all the endpoints. The incremental ticket endpoint only supports a few - https://developer.zendesk.com/rest_api/docs/core/incremental_export#incremental-ticket-export. If you need information on groups/organizations etc you will need to pull that data from the respective endpoints. 

Also, just a heads up, you posted your API token in the snippet above. I've edited the comment to remove it, but you should definitely revoke that token ASAP and create a new one.
