### ISSUE TITLE
Ability to add Zendesk Talk endpoints?

### ISSUE THREAD

**Issue by Shaakmiller** [facetoe/zenpy#272]
Hello,

I have already made an app that uses Zenpy but now I have to add Talk functionality. Have you already played around with this? 

If you have anything half done for talk I can kind of play around with I will take it, otherwise I guess I can take a crack at it solo and see how far I get.

I am wondering, is Talk not done just because the need or time hasn't been there or has it been tried and it proves to be quite difficult?

I read your documentation on how to hack Zenpy and I get the impression it is just a question of someone having the need and the time? I just wanna know if I am walking into a huge challenge that other people have already tried and abandoned. If thats the case I may just whip together my own little requests app. I would be looking to create endpoints for printing data mostly. I don't know that i'd get into the more complicated stuff.

Thank you, I really love Zenpy, I have already used it to make other apps at work!

Joshua

Much appreciated,

Joshua

**Comment by Shaakmiller** [comment]
I ran your gen tools to create the API_objects, it runs through the classes that are already created but then throws an error when I get to the zendesk talk that I have been working with.

`Traceback (most recent call last):

  File "./gen_classes.py", line 430, in <module>
    write_baseclass=False)
  File "./gen_classes.py", line 409, in process_specification_directory
    classes.extend(pool.map(func, paths))
  File "C:\Users\joshua.miller\AppData\Local\conda\conda\envs\zentalk\lib\multiprocessing\pool.py", line 290, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Users\joshua.miller\AppData\Local\conda\conda\envs\zentalk\lib\multiprocessing\pool.py", line 683, in get
    raise self._value
KeyError: 'voice-api'`

I modified the gen_classes.py by adding:

`process_specification_directory('talk/*.json', 'api_objects/talk_objects.py',
                                    namespace='voice-api',
                                    write_baseclass=False)`    

and I modified doc_dict_gen.py by adding the appropriate url at the end:

`    urls = (
        'https://developer.zendesk.com/rest_api/docs/core/introduction',
        'https://developer.zendesk.com/rest_api/docs/help_center/introduction',
        'https://developer.zendesk.com/rest_api/docs/chat/introduction',
        'https://developer.zendesk.com/rest_api/docs/voice-api/phone_numbers',
    )`

I also added about 8 json files into the specification folder that I wanted to turn into objects

**Comment by facetoe** [comment]
Hmm, I think if you just remove `'https://developer.zendesk.com/rest_api/docs/voice-api/phone_numbers'` from the url tuple and choose the `core` namespace that should get you over this hurdle for now. The only effect is a possible naming collision and there will be no autogenerated docs for these objects, but I can have a look and try to fix that up later.

**Comment by facetoe** [comment]
Actually I'm not 100% sure the above is correct. I'll have a look this afternoon.

**Comment by facetoe** [comment]
OK if you remove the phone numbers url from urls, create a directory `talk` in the specification directory and edit the gen-classes.py script as follows:

```
process_specification_directory('talk/*.json', 'api_objects/talk_objects.py',
+                                namespace='core')
```

You should be good to go.

**Comment by Shaakmiller** [comment]
Ah I really appreciate that, I don’t mind writing out some docs if need be. I’m definitely ready to do some grunt work to put together something that will work for me and something I can also give back to the community too. I appreciate the help, i really really do.

**Comment by Shaakmiller** [comment]
It worked! On to the next step! I will work with some of the most popular objects for now and perfect those before adding more complex and less popular ones if I can get around to it. I am using the ones that people will use for statistic and agent availability dashboards, etc. for now.

![image](https://user-images.githubusercontent.com/17973037/47826720-c873fe80-dd4f-11e8-9da4-e1a25a522632.png)

**Comment by facetoe** [comment]
Ahh excellent, not a problem. Happy to help in any way I can, so don't hesitate to ask if you get stuck.

**Comment by Shaakmiller** [comment]
I am starting to figure out the structure of your program, it has definitely been some trial and error but it is all starting to flow a bit better now. 

I was able to use Zenpy to get a response for current_queue_activity:

zenpy.lib.exception.ZenpyException: Unknown Response: {'current_queue_activity': {'agents_online': 2, 'average_wait_time': 0, 'calls_w
aiting': 0, 'longest_wait_time': 0, 'callbacks_waiting': 0, 'embeddable_callbacks_waiting': 0}}

So this is great, I am typing in zenpy_client.talk.current_queue_activity() and it is returning what you see above (which is teh right data), so I know it is now making a succcessful request. I just dont have the right handler to deserialize the data. Just have to build a talk response handler class and result generator class now to get it to pump out a proper result. Is there another step at the end of that or does that sound about right?

Thanks so much for the help!

**Comment by Shaakmiller** [comment]
Nevermind, it was much easier than that, I just didn't have it mapped properly to its respective object. Got the first endpoint up and running!

**Comment by Shaakmiller** [comment]
Everything is pretty much done with these 6 endpoints, I just have to test them a bit before I do a pull request. Once I do that you can give it a final look over and see if it is mergeable or needs to be adjusted.

**Comment by facetoe** [comment]
Great news! Yep, send through a PR whenever you're ready and I'll have a look.

**Comment by Shaakmiller** [comment]
I sent through a PR. Ignore the first one I sent. I closed it.

**Comment by Shaakmiller** [comment]
I edited the PR, let me know what you think.

**Comment by facetoe** [comment]
Great stuff!

(merged in https://github.com/facetoe/zenpy/pull/274)
