### ISSUE TITLE
Proactive rate limit documentation/code inconsistencies

### ISSUE THREAD

**Issue by joekohlsdorf** [facetoe/zenpy#275]
The current code activates proactive ratelimit by default, however the documentation states "If you wish to avoid ever hitting the rate limit you can set the proactive_ratelimit parameter when instantiating Zenpy."

The documentation about this feature was left in a mess after this change: https://github.com/facetoe/zenpy/commit/564d3600729ecbd231c51770ac208fec8238f917

It says to set `proactive_ratelimit` and then shows an example setting `proactive_ratelimit_request_interval`. This might be desired, after all the current code never reads the variable `proactive_ratelimit`.

This could be a mistake and this line should maybe have been `if self.proactive_ratelimit is not None:`
https://github.com/facetoe/zenpy/blob/19f248be8a90e142a61842528c97800636f60280/zenpy/lib/api.py#L121

In addition to that, `ratelimit_budget` is not honored for the time spent in the proactive rate limit path.

I am not submitting a PR because I need an explanation how this should work, the inconsistency between docs and code make it impossible to understand how things were meant to be.

**Comment by facetoe** [comment]
Yep agreed. Kindof ironic that a commit titled " Update docs to better explain proactive_ratelimit settings. " made the situation worse...

TBH, I'd need to stare at that code for a bit to remember how it was supposed to work and how it should interact with the `ratelimit_budget` feature. It definitely should not be on by default.

**Comment by joekohlsdorf** [comment]
I'll work on a PR later that week, thanks for clarifying what should be the default.

**Comment by mtcronin99** [comment]
This was also a breaking change to existing code.  One of the parameters to the `Zenpy` initializers `ratelimit` was removed.  I believe that it was replaced by `proactive_ratelimit`.    This has been released in 2.0.7

**Comment by facetoe** [comment]
Hey finally had a chance to look into this. From what I can see it is working as specified in the documentation. It is a little confusing as the parameters accepted by the Zenpy constructor (`proactive_ratelimit_request_interval`/`proactive_ratelimit`) are passed in a dict to the `Api` classes and then internally the old names are used - https://github.com/facetoe/zenpy/blob/master/zenpy/__init__.py#L91. 

I'll fix it up so the `ratelimit_budget` option includes time spent in proactive ratelimiting.
