### ISSUE TITLE
unhandled requests/urrlib3 default retry logic interferes with rate limiting

### ISSUE THREAD

**Issue by joekohlsdorf** [facetoe/zenpy#276]
`By default, urllib3 will retry requests 3 times` for the following status codes: [503, 413, 429]
https://urllib3.readthedocs.io/en/latest/user-guide.html

Zenpy doesn't handle this which means that the whole rate limit retry logic is flawed. With the standard configuration, when executing any call to external URLs, urllib3 will retry internally with its own waiting mechanism for up to 3 times.
For 429 (rate limited), urllib3 will respect the retry-after headers. So you have rate-limiting within rate-limiting!

My suggestion: Tear the whole rate limiting code out and pass the configuration values on to urrlib3.

Proof (first 3 are urllib3 retries, last is Zenpy retry), also note the times at the right, this is with ratelimit_budget=10.
<img width="1131" alt="screen shot 2018-11-13 at 22 30 12" src="https://user-images.githubusercontent.com/32424163/48453868-e8fe7880-e793-11e8-8d88-9d21edb67076.png">

**Comment by facetoe** [comment]
Thanks for the heads up! I didn't know urlib could handle this. It would definitely be preferable to pass that task of to urlib if possible.

**Comment by joekohlsdorf** [comment]
I had a look at what requests/urllib3 offers in terms of configurability. Sadly there is no way to set something like a rate-limit budget which I find quite useful, it will instead always respect the retry-after headers.

After playing with this for a long time I managed to deactivate retries for 429 while keeping it in tact for 5xx like shown below.
Not really intuitive and for sure not what the documentation says about this.
```
import logging
import requests
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

logging.basicConfig(level=logging.DEBUG)

session = requests.Session()
retries = Retry(
    total=3,
    status_forcelist=[500, 502, 503, 504],
    respect_retry_after_header=False
)
session.mount('http://', HTTPAdapter(max_retries=retries))

resp = session.get('http://httpstat.us/429')
```

**Comment by facetoe** [comment]
Hey finally had a chance to look at this. I've put together something very similar to what you have above and it seems to be working well - https://github.com/facetoe/zenpy/pull/286.

If you don't see any issues there I'll merge this in the next couple of days.
