### ISSUE TITLE
requests.open() does not return all tickets

### ISSUE THREAD

**Issue by hellvix** [facetoe/zenpy#277]
Hi.

```
return client.search(type='ticket', status='open', assignee=self.email)
```
```
return client.requests.open()
```

Shouldn't these two statements return the same result? I have 6 tickets assigned to myself, the first one returns them, however the second only returns 4.

I would also like to suggest adding another queryset method called `unsolved`, since a ticket can be either `pending` or `open`.

**Comment by facetoe** [comment]
Thanks for the report! I'll have a look and see if I can figure out what's going wrong when I get the chance (super busy ATM, shouldn't be too long though).

**Comment by hellvix** [comment]
I guess the second statement only returns the tickets with status `opened` whose requester is the user the object `client` is instantiated with.

I misunderstood the method.
