### ISSUE TITLE
Missing user details

### ISSUE THREAD

**Issue by hellvix** [facetoe/zenpy#278]
The following statement:

```
for r in client.requests.comments(request_id=request_id):
    print(r.body, r.author.name, r.author.email)
```

Returns:

```
>>> 'Request body', 'John Doe', None
```

If I go directly to the JSON URL for that specific user, I can see his details there, including his e-mail address.

**Comment by facetoe** [comment]
Thanks for the report! I'll have a look and fix this up.

**Comment by hellvix** [comment]
After some digging I found out that if I disable the caching the e-mail address appears.

**Comment by facetoe** [comment]
So looks like the User object returned with the comment only has minumul information if you are not an agent.
