### ISSUE TITLE
Possible caching problem

### ISSUE THREAD

**Issue by hellvix** [facetoe/zenpy#279]
Imagine the following scenario:

> 1. On Tab 1, the user writes a message, attaches a file and submits the page. A ticket is created on Zendesk.
> 2. On Tab 2, the same user writes another message, attaches a different file and submits the page. Another Zendesk ticket is created.
> 3. If for some reason this same user decides to go back to, for example, to Tab 1, click in "Back" in his browser and re-submit the page, when the ticket is created both Attachments (from Tab 1 and 2) have been attached to a new ticket (Ticket number 3).

I am still making tests to see if this is either my code or Zenpy, but do you think this could have something to do with the caching Zenpy provides?

**Comment by facetoe** [comment]
Without more information it is impossible to tell, however you can disable caching easily enough to test:

```python
zenpy_client.disable_caching()
```

Hope this helps.

**Comment by hellvix** [comment]
Did not work. Very puzzling that two different requests manage to share some of the data.

I am basically initializing the `client = Zendesk()` every time the user enters that page to modify a ticket. Cannot see where the object would share the data like that.

**Comment by facetoe** [comment]
That is weird. Are you using the latest version? A while back I moved all the global state into the instance, previously multiple Zenpy instances would share the same caches.

**Comment by hellvix** [comment]
Yes, it is the latest version (2.0.7). Below I'll add what I am doing in my code. I hope I have included all the necessary bits.

```
class Zendesk(object):
    """
    An abstraction of the Zenpy API interface.
    """

    def __init__(self, email):
        try:
            token = ZendeskToken.objects.get(email=email)
            self.email = email
            self.__api = Zenpy(email=token.email, token=token.token, subdomain=token.subdomain)
        except ObjectDoesNotExist:
            raise Exception('{} does not have a Zendesk Token configured.'.format(email))

    def add_comment(self, request_id, body, cc=None, status=None, attachments=None):
        """
        Add a comment to an existing ticket.
        """

        ticket = self.get_ticket(request_id)

        # Add MAIN_TICKET_TAG to the ticket if not already there
        if MAIN_TICKET_TAG not in ticket.tags:
            ticket.tags.extend([MAIN_TICKET_TAG, ])

        # Change the ticket status if necessary
        if status:
            ticket.status = status

        # cc is a list of v3.mail.Recipient
        if cc:
            ticket.collaborators = [self.get_or_create_user(sandbox_email(c.email)) for c in cc]

        if attachments:
            attachments = self.upload_attachment(attachments)

        ticket.comment = Comment(body=body, uploads=attachments)
        return self.__api.tickets.update(ticket)

    def upload_attachment(self, attachments):
        """
        Upload attachments and return their tokens in a list of dictionaries.
        Expects a list of v3.ship.Attachment
        """
        upload_tokens = []

        for attachment in attachments:
            upload_instance = self.__api.attachments.upload(
                target_name=attachment.file_name,
                # Bytes like objects do not have read()
                fp=attachment.instance.read() if hasattr(attachment.instance, 'read') else attachment.instance,
                content_type=attachment.content_type
            )
            upload_tokens.append(upload_instance.token)

        return upload_tokens
```

## MyView
```
def dispatch():
    ...
    # Initializes the object here, otherwise tells the view the user is not allowed to use the Zendesk API
    self.client = Zendesk(email='some@email')
    ...
def post(request, *args, **kwargs):
    ...
    if form.is_valid():
        self.client.add_comment(**ticket_data)
    ....
```

**Comment by facetoe** [comment]
Nothing stands out sorry, very strange issue.
