### ISSUE TITLE
Ticket Fields

### ISSUE THREAD

**Issue by facetoe** [facetoe/zenpy#28]
https://developer.zendesk.com/rest_api/docs/core/ticket_fields

**Comment by facetoe** [comment]
Reading is supported but not updating/creating etc.

**Comment by Myst3ri0n** [comment]
Hello, 

I'm trying to understand how to pull basic ticket info like the title, status, and organization. I'm having a hard time figuring out how to do that from the docs. I'm able to do a search and get all of my active tickets, but that's as far as I got, any help would be appreciated.

**Comment by facetoe** [comment]
Hi @Myst3ri0n, 

The Ticket object contains this information, eg:

```python
ticket = zenpy.tickets(id=4)
print(ticket.subject)
print(ticket.status)
print(ticket.organization.name)
```
The full list of available attributes for the ticket object can be found here - https://facetoe.com.au/zenpy/docs/api_objects.html#zenpy.lib.api_objects.Ticket

**Comment by Myst3ri0n** [comment]
Hi @facetoe ,

Thanks for your reply! I was able to get almost all the fields I needed with your help. But I see that the assignee_updated is under ticket_metrics. Looking at the code of the module I thought I had it figured out, but I get an error. Any ideas?

Thanks for your help!

```
tickMet = zenpy.ticket_metrics(ticket_id=123)
print tickMet.assignee_updated
```

I get the following error: **AttributeError: 'ResultGenerator' object has no attribute 'assignee_updated'**

**Comment by facetoe** [comment]
You're almost there. The `ticket_metrics` endpoint returns multiple items (as a generator) not a single item. Try:

```python
for t in zenpy.ticket_metrics(ticket_id=1):
    print(t.assignee_updated)
```

**Comment by Myst3ri0n** [comment]
Thanks for the quick reply, I used your exact code from above and put in a valid ticket number, one that was just opened this morning, and I'm slightly confused by the output. I expected to get one result returned, a none, since the ticket hasn't been updated yet, but instead I got hundreds of dates spit out, and it kept going, I had to kill the process. Any insight would be most helpful.

**Comment by facetoe** [comment]
My bad, the correct code is:

```python
ticket_metric = zenpy.tickets.metrics(ticket_id=2)
```

This returns the ticket metric for the ticket with an id of 2. The `ticket_metric` endpoint is a primary endpoint, so in the code:

```python
zenpy.ticket_metrics(ticket_id=1)
```
the `ticket_id` keyword argument is ignored, leading to all ticket metrics being returned (which would be a lot). The `ticket_metric` endpoint is to be used when you want to retrieve a `TicketMetric` by it's id, the `tickets.metric` endpoint is for when you want to retrieve a `TicketMetric` by it's associated ticket's id, which is what you want to do.

**Comment by Myst3ri0n** [comment]
Thanks! That worked great! Your explanation makes sense, I appreciate you working with a noob! Thanks for taking the time to build this module! I plan on using it quite a bit to load data into pandas and build statistics on the data to help my team and me stay on top of tickets!

**Comment by facetoe** [comment]
No worries! Glad it's working :)

**Comment by Myst3ri0n** [comment]
Hi Sorry to keep bugging you, but I'm having trouble with grabbing user fields.

I have looked over the module code, and compared to where you pointed me last time, I thought for sure this would work:

```
for user in zenpy.users.user_fields(user_id=123):
    print user.name
    print user.id
    print user.email
```
but I get the following error: **zenpy.lib.exception.RecordNotFoundException: {"description": "Not found", "error": "RecordNotFound"}**

I was able to get this to work, but it outputs all users and not the one I have listed for user_id:

```
for user in zenpy.users(user_id=123):
    print user.name
    print user.id
    print user.email
```

Please let me know if you want me to open a separate issue for this, I know this is getting a little off topic. I thought for sure I had this figured out.

**Comment by facetoe** [comment]
The `RecordNotFoundException` means there is no user with that id. The code:

`zenpy.users(user_id=123)`

is equivilent to:

`zenpy.users()`

which returns all users as the keyword argument `user_id` is ignored. 

It might be useful if you turn debugging on so you can observe the API requests that are being made. Try adding the following code to enable debugging:

```python
log = logging.getLogger()
log.setLevel(logging.DEBUG)
ch = logging.StreamHandler(sys.stdout)
formatter = logging.Formatter('%(levelname)s - %(message)s')
ch.setFormatter(formatter)
log.addHandler(ch)
logging.getLogger("requests").setLevel(logging.WARNING)
```

**Comment by Myst3ri0n** [comment]
So I ran the one that pulls all users and grabbed their id and passed it to the other code that I based above that returned the error and this what I got along with the error.

```
DEBUG - Cache MISS: [User_field 229509947]
DEBUG - GET: https://mydomain.zendesk.com/api/v2/user_fields/229509947.json&include=
```

Thanks

**Comment by facetoe** [comment]
No worries.

**Comment by Myst3ri0n** [comment]
Any ideas on what would cause that when using a known good id?

**Comment by facetoe** [comment]
This looks like a bug actually. I'll have a look tomorrow as I need to set up a test Zendesk with user fields to troubleshoot further.

**Comment by Myst3ri0n** [comment]
Ok, that sounds good. Just quick question to make sure I'm trying to approach this correctly. When you say user fields, you mean fields like name, email etc. Because that's what I'm trying to accomplish. Basically I have all the ticket info loaded into a table. But he requester and assignee is stored as an ID so I need to get all the basic user info with their id so I can do a join and get the actual name when I build reports off of the data.

Just wanted to make sure I wasn't trying to grab that data from the wrong place.

Thanks

**Comment by facetoe** [comment]
Nope I'm talking about https://developer.zendesk.com/rest_api/docs/core/user_fields. You need to check out the docs on the User object - https://facetoe.com.au/zenpy/docs/api_objects.html#zenpy.lib.api_objects.User. 

Please read the documentation, both Zendesk's (https://developer.zendesk.com/rest_api/docs/core/introduction) and Zenpy's (https://facetoe.com.au/zenpy/docs/) before posting any more comments. If you find a bug I am happy to investigate and fix it, however I cannot figure out the API for you.
