### ISSUE TITLE
ticket inside SearchResultGenerator differ from ticket.count

### ISSUE THREAD

**Issue by federicopuntoni** [facetoe/zenpy#281]
If someone delete a ticket from zendesk platform and i perform a search during next 10/15 seconds, this appened:

```
print(tickets, tickets.count)
for t in tickets:
    print(t)
```

> <zenpy.lib.generator.SearchResultGenerator object at 0x000001F1EEC910F0> 6
> Ticket(id=4900)
> Ticket(id=5146)
> Ticket(id=5103)
> Ticket(id=4899)
> Ticket(id=4901)

ticket.count is 6
but tickets has 5 Ticket

**Comment by facetoe** [comment]
Search is always a bit delayed. If you perform the search in the web interface you will see the same behavior.

**Comment by federicopuntoni** [comment]
How i can perform a correct slice for pagination without know the exact amount of tickets in search result?

**Comment by facetoe** [comment]
I'm not sure I understand, why do you need to slice?

**Comment by facetoe** [comment]
I believe that should still work as expected. You will just have a partially filled view.
