### ISSUE TITLE
zenpy_client.tickets() won't retrieve all ticket IDs

### ISSUE THREAD

**Issue by gitlech** [facetoe/zenpy#282]
Hi facetoe!
First of all, thanks for zenpy, it's a really good and performant wrapper! However, I have a question:

I want to download all tickets and we have 270K of them.
I tried 
`tickets = zenpy_client.tickets(*args, **kwargs)`
and it would do pagination for 650 times and stop then, retrieving only 65K Tickets. Interestingly the Tickets of the last 4 months seem to be rather complete whereas tickets older than 4 months suffer from massive gaps.

I tried the incremental load then with a start date of the first day we started using Zendesk as a kw argument
`return zenpy_client.tickets.incremental(*args, **kwargs)`
and voila all 270K Tickets could be retrieved.

I'm not sure if this could be a bug or if there is any other explanation to this behavior. Maybe you can shed some light on this.

Thanks

**Comment by facetoe** [comment]
Hi, sorry for taking so long to get back to you. The incremental API is the right one to use if you want to retrieve all tickets. I'm not sure why the normal `tickets()` endpoint stops iterating, however if you want all the tickets you shouldn't use it anyway as it is so slow.

TBH it sounds a bit like a Zendesk issue and not a Zenpy one, so it might be worth asking them if you want more info. I don't have an account with such a volume of tickets to test with so can't really dig any further.

Cheers,
Facetoe.
