### ISSUE TITLE
zenpy.search should escape special characters like `&`

### ISSUE THREAD

**Issue by crunis** [facetoe/zenpy#283]
Currently this happens:
```
>>> res = zenpy_client.search(name="The wood & fire experts", type='organization')
>>> res.next()
Ticket(id=286322)
```
Note that we were querying for "organizations" and a ticket is returned.

If we manually escape the organization name (which contains the `&` symbol):
```
>>> res3 = zenpy_client.search(name=urllib.quote_plus("The wood & fire experts"), type='organization')
>>> res3.next()
Organization(id=27447913607)
```
We get the correct organization.
What seems to be happening is that zenpy is performing the request without escaping the `&` symbol and that is somehow truncating the request, and the `type="organization"` part is lost, and we are just searching for "The wood".
This has been check to happen in both python2.7 and python3.7.1

**Comment by facetoe** [comment]
Thanks for the report. Yep, wasn't escaping the query properly, for some reason I thought requests did it all automagically but I guess not.
