### ISSUE TITLE
RecordInValid after setting requester in create Ticket

### ISSUE THREAD

**Issue by ghost** [facetoe/zenpy#287]
I'm having trouble creating a ticket with Zenpy.

This works:

            submitter = User(name="John Doe", email="john@doe.com")
            submitter = self.zenpy_client.users.create_or_update(submitter)
            
            zendesk_ticket = Ticket(
                subject=subject,
                description=description,
                submitter=submitter,
                assignee=self.zenpy_client.users.me()
            )

This doesn't: 

            submitter = User(name="John Doe", email="john@doe.com")
            submitter = self.zenpy_client.users.create_or_update(submitter)
            requester = User(name="Jane Doe", email="jane@doe.com")
            requester = self.zenpy_client.users.create_or_update(requester)
            
            zendesk_ticket = Ticket(
                subject=subject,
                description=description,
                submitter=submitter,
                requester=requester,
                assignee=self.zenpy_client.users.me()
            )

Result:
```
{"description": "Record validation errors", "details": {"requester": [{"description": "Requester: Name:  is too short (minimum is 1 character)"}]}, "error": "RecordInvalid"}
```

If I dump the body and post it via a REST Client it works without a problem. Any idea what the problem might be?

**Comment by facetoe** [comment]
No worries, also FYI I released a new version - https://github.com/facetoe/zenpy/releases/tag/2.0.8
