### ISSUE TITLE
Question - Pulling phone recordings as attachments

### ISSUE THREAD

**Issue by TheFoolInRed** [facetoe/zenpy#289]
Hey, I'm trying to figure out how to pull phone recordings via Zenpy. I'm still a bit of a Python noob, so I I'm probably missing something obvious. I looked over the script in: https://github.com/facetoe/zenpy/issues/192 and was able to pull the ticket attachments, but aside from a handful of pdfs I didn't get any phone recordings. I found this page: https://support.zendesk.com/hc/en-us/articles/225850728-Can-I-download-call-recordings- and while I could download these manually, I need like ~5k recordings for a data dump. Any idea what the best way for that might be or how I can pick those up in a loop? Current code is as follows: 

`print('Importing datetime...')`
`import datetime`
`import requests`
`print('Import complete.')`

`print('Storing authentication information...')`
`# Zenpy accepts an API token`
`creds = {`
    `'email' : 'email',`
    `'token' : 'token',`
    `'subdomain': 'subdomain'`
`}`
`print('Authentication details stored.')`

`print('Importing the Zenpy client.')`
`# Import the Zenpy Class`
`from zenpy import Zenpy`
`print('Zenpy client imported.')`

`print('Signing into Zendesk via Zenpy...')`
`# Default`
`zenpy_client = Zenpy(**creds)`
`print('Signed into Zendesk!')`

`x='1'`
`n = 0`
`print('Processing date time filter. Currently going back ' + x + ' days')`

`yesterday = datetime.datetime.now() - datetime.timedelta(days=1)`
`today = datetime.datetime.now()`
`print('Iterating over tickets.')`
`for ticket in zenpy_client.search("Phone call from%", created_between=[yesterday, today],` `type='ticket', minus='negated'):`
`    for audit in zenpy_client.tickets.audits(ticket.id):`
`        for event in audit.events:`
`            for attachment in event.get('attachments', []):`
`                res = requests.get(attachment['content_url'], auth=('user', 'password'))`
`                with open(attachment['file_name'], 'wb') as fout:`
`                    fout.write(res._content)`

**Comment by facetoe** [comment]
Hi, @TheFoolInRed, this should do the job:

```python
zenpy_client = Zenpy(**creds)


def download_call(session, call_url, destination):
    r = session.get(call_url, stream=True)
    with open(destination, 'wb') as f:
        for chunk in r.iter_content(chunk_size=1024):
            if chunk:
                f.write(chunk)


yesterday = datetime.datetime.now() - datetime.timedelta(days=1)
today = datetime.datetime.now()
print('Iterating over tickets.')
for ticket in zenpy_client.search("Phone call from%", created_between=(yesterday, today), type='ticket'):
    for comment in zenpy_client.tickets.comments(ticket):
        if comment.type == 'VoiceComment':
            download_call(session=zenpy_client.tickets.session,
                          call_url=comment.data['recording_url'],
                          destination='/tmp/{}.mpeg'.format(comment.data['call_id']))
```

Hope this helps!
