### ISSUE TITLE
query on users

### ISSUE THREAD

**Issue by hugoeloue** [facetoe/zenpy#29]
Hello,

How can I get a user thanks to his email ?
zenpy.users(email="theemailadress") doesnt work. I got a resultgenerator instead of an object.

Regards

HW

**Comment by facetoe** [comment]
You're better off using the `search` endpoint for this. Eg, 

```python
user = next(zenpy.search(email="theemailadress", type='user')) 
```

The `users` endpoint only supports the calls defined in the documentation for Zendesk - https://developer.zendesk.com/rest_api/docs/core/users, so you can't retrieve a user by email, only by id.
