### ISSUE TITLE
jobs_report on high imports

### ISSUE THREAD

**Issue by insspb** [facetoe/zenpy#291]
Hi. Currently, I am preparing large migration (160k users, 300k tickets, tons of comments). 
During test migration one issue with job_status found. 
After ~20k of migrated objects in queue (by 100) zendesk not making https://example.domain/api/v2/job_statuses/[job_id].json 
I reported this issue to zendesk, but they ignore me for two days. 
Log still available in `zenpy_client.job_status()`, because this parses `https://example.domain/api/v2/job_statuses` endpoint. 
It will be great to note this in documentation or ever make some flag to id scanner, that will still be usable as zenpy_client.job_status(id=job_id), but will parse all list under the hood.

**Comment by facetoe** [comment]
Hi, 

Thanks for the report. I'm not quite sure I understand the problem, does the job_status endpoint hang or not return correctly?

FYI you can pass a list of job status ids to the `job_status` endpoint:

```
zenpy_client.job_status(ids=['id1', 'id2', 'id3'])
```

Not sure if this helps. It's probably not clear from the docs.

**Comment by insspb** [comment]
it will not return [hash].json links
so I workaround this like
```
jobs = zenpy_client.job_status()
for job in jobs:
    if job.id == hash:
        do something
```
Not brilliant code, but works )

**Comment by facetoe** [comment]
Does it throw an error or just return None or something?

**Comment by insspb** [comment]
page in browser throw 404, 
client HTTPError

**Comment by facetoe** [comment]
Ahh OK, yea does sound like an issue with Zendesk. I guess you have a solution, but I wonder if you wait a bit if the JobStatus will be retrievable by hash. Their systems might be a bit behind on processing or something.

**Comment by insspb** [comment]
https://developer.zendesk.com/rest_api/docs/support/job_statuses
> Zendesk only logs the last 100 jobs.
So in bulk migrations, there is no time to wait. New jobs already overwrite old one.

**Comment by facetoe** [comment]
> A job may no longer exist to query. Zendesk only logs the last 100 jobs. Jobs also expire within an hour.

Looks like that might be what is happening here, it's a constraint of their system. That's a bit of a pain if you are creating such a large volume of objects and need to wait until they are persisted.

I don't really want to add something to Zenpy to handle this case, it's probably better handled by the application like you have done. Can add a note to the docs though to help out anyone else looking to do big data loads.

**Comment by insspb** [comment]
After I done all migration I will try to find time to fill some gaps in documentation. 
Currently I am on deadlines.
