### ISSUE TITLE
Unassigned tickets

### ISSUE THREAD

**Issue by fajrihanny** [facetoe/zenpy#294]
Nice library. I couldn't seem to find how to find unassigned tickets. Is sending query with assignee='none' working? Tried that and it didn't give me the correct result.

**Comment by jdmarch** [comment]
driveby question -- did you try `assignee='None'` ?

**Comment by fajrihanny** [comment]
> driveby question -- did you try `assignee='None'` ?

Yeah - both `none` and `None` returns nothing.

**Comment by facetoe** [comment]
Thanks for the report @fajrihanny, this looks like a bug. The search works fine in the Zendesk interface but returns nothing via Zenpy. A workaround could be to use the unassigned tickets view until I have a chance to investigate this properly.
