### ISSUE TITLE
Intermittent failures due to uncaught IncompleteRead exceptions

### ISSUE THREAD

**Issue by mybludrunsorange** [facetoe/zenpy#295]
This occurs both in Docker and on my desktop. I'm not sure what's going on here or whether the issue is on the Zendesk side or locally.

> DEBUG - https://xxxxx.zendesk.com:443 "GET /api/v2/incremental/ticket_events.json?include=comment_events&start_time=1550676714 HTTP/1.1" 200 None
> Traceback (most recent call last):
>   File "/Users/trevorhunt/general_dev/lib/python3.7/site-packages/urllib3/response.py", line 572, in _update_chunk_length
>     self.chunk_left = int(line, 16)
> ValueError: invalid literal for int() with base 16: b''
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/trevorhunt/general_dev/lib/python3.7/site-packages/urllib3/response.py", line 331, in _error_catcher
>     yield
>   File "/Users/trevorhunt/general_dev/lib/python3.7/site-packages/urllib3/response.py", line 637, in read_chunked
>     self._update_chunk_length()
>   File "/Users/trevorhunt/general_dev/lib/python3.7/site-packages/urllib3/response.py", line 576, in _update_chunk_length
>     raise httplib.IncompleteRead(line)
> http.client.IncompleteRead: IncompleteRead(0 bytes read)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/trevorhunt/general_dev/lib/python3.7/site-packages/requests/models.py", line 749, in generate
>     for chunk in self.raw.stream(chunk_size, decode_content=True):
>   File "/Users/trevorhunt/general_dev/lib/python3.7/site-packages/urllib3/response.py", line 461, in stream
>     for line in self.read_chunked(amt, decode_content=decode_content):
>   File "/Users/trevorhunt/general_dev/lib/python3.7/site-packages/urllib3/response.py", line 665, in read_chunked
>     self._original_response.close()
>   File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 130, in __exit__
>     self.gen.throw(type, value, traceback)
>   File "/Users/trevorhunt/general_dev/lib/python3.7/site-packages/urllib3/response.py", line 349, in _error_catcher
>     raise ProtocolError('Connection broken: %r' % e, e)
> urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/trevorhunt/code/zendesk_export/ticket_event_export.py", line 154, in <module>
>     for event in event_generator:
>   File "/Users/trevorhunt/general_dev/lib/python3.7/site-packages/zenpy/lib/generator.py", line 156, in __next__
>     return self.next()
>   File "/Users/trevorhunt/general_dev/lib/python3.7/site-packages/zenpy/lib/generator.py", line 45, in next
>     self.handle_pagination()
>   File "/Users/trevorhunt/general_dev/lib/python3.7/site-packages/zenpy/lib/generator.py", line 54, in handle_pagination
>     self._response_json = self.get_next_page(page_num=page_num, page_size=page_size)
>   File "/Users/trevorhunt/general_dev/lib/python3.7/site-packages/zenpy/lib/generator.py", line 185, in get_next_page
>     return super(ZendeskResultGenerator, self).get_next_page(page_num, page_size)
>   File "/Users/trevorhunt/general_dev/lib/python3.7/site-packages/zenpy/lib/generator.py", line 71, in get_next_page
>     response = self.response_handler.api._get(url, raw_response=True, params=params)
>   File "/Users/trevorhunt/general_dev/lib/python3.7/site-packages/zenpy/lib/api.py", line 104, in _get
>     response = self._call_api(self.session.get, url, timeout=self.timeout, **kwargs)
>   File "/Users/trevorhunt/general_dev/lib/python3.7/site-packages/zenpy/lib/api.py", line 125, in _call_api
>     response = http_method(url, **kwargs)
>   File "/Users/trevorhunt/general_dev/lib/python3.7/site-packages/requests/sessions.py", line 525, in get
>     return self.request('GET', url, **kwargs)
>   File "/Users/trevorhunt/general_dev/lib/python3.7/site-packages/requests/sessions.py", line 512, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/Users/trevorhunt/general_dev/lib/python3.7/site-packages/requests/sessions.py", line 662, in send
>     r.content
>   File "/Users/trevorhunt/general_dev/lib/python3.7/site-packages/requests/models.py", line 827, in content
>     self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
>   File "/Users/trevorhunt/general_dev/lib/python3.7/site-packages/requests/models.py", line 752, in generate
>     raise ChunkedEncodingError(e)
> requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

**Comment by mybludrunsorange** [comment]
This error does appear to be intermittent.

**Comment by facetoe** [comment]
This looks like a networking issue. Are you able to `curl` the Zendesk API successfully?

**Comment by mybludrunsorange** [comment]
I am. My process runs just fine but this error occurs up from time to time during a large pull of the event data. That makes it hard for me to schedule/automate. This happens on my local machine when connected directly, via VPN as well as on an app box I have in AWS (code is run from docker). I haven't seen this issue with the incremental ticket API, only events.

**Comment by facetoe** [comment]
Not sure there is anything I can do here, you might want to raise an issue with Zendesk. 

You might be able to catch the exception, retrieve the `next_page` attribute from the generator and carry on when this happens.

**Comment by mybludrunsorange** [comment]
Cool, I appreciate the response. All indications I found pointed to network issues as well. Unfortunately, it occurs from multiple networks on my end, including AWS, so I think you're correct in that there may be some sort of issue on the AWS side.

Does there happen to be any sort of session duration limit or something along those lines in the libraries you're using? While the issue appears to be intermittent - it happens at varying points (batches) in a run - it could be that the issue is time-based and variances in the time for Zendesk to respond are what cause the problem to appear intermittent.

Is there any chance of that being the case?

**Comment by facetoe** [comment]
Zenpy uses a requests session under the hood (http://docs.python-requests.org/en/master/user/advanced/#session-objects), however I don't think there is any concept of  a session duration or anything.
