### ISSUE TITLE
Is there a way to get user who voted on a post ?

### ISSUE THREAD

**Issue by sdavos** [facetoe/zenpy#297]
Is there a way to get user who voted on a post ?

Thanks in advance

**Comment by facetoe** [comment]
Yep, looks like the user id is recorded in the Vote object - https://developer.zendesk.com/rest_api/docs/help_center/votes.

**Comment by sdavos** [comment]
Yes, but how to call the Zenpy api to get this ?

[logo]<http://www.smag.tech/>
[Twitter]<https://twitter.com/SMAG_SmartAgri?lang=fr>[LinkedIn]<https://www.linkedin.com/company/9269773/>[Youtube]<https://www.youtube.com/channel/UCwkE7rndASxb6owyxVxgTYw>

Sébastien DAVOS
Project Management Officer
Project management officer
sdavos@smag.tech <mailto:sdavos@smag.tech>
04 34 35 23 10
06 43 20 00 22

Le Terra Verde - Parc Eureka
55 rue Euclide | 34960 Montpellier Cedex 2 | France
Tél : 04 34 35 20 50
Fax : 03 26 21 84 29
smag.tech <https://www.smag.tech>



Ce message (y compris toute annexe) est confidentiel, et protégé par le secret professionnel. Si vous n'êtes pas destinataire de ce message, merci de bien vouloir nous en informer immédiatement et de le supprimer.
This e-mail (including all attachments) is intended for the named addressee. It is confidential and privileged. If you have received it in error, please contact us immediately and then delete it.


[Bandeau]


De : Facetoe <notifications@github.com>
Envoyé : jeudi 21 février 2019 12:56
À : facetoe/zenpy <zenpy@noreply.github.com>
Cc : Sébastien DAVOS <sdavos@smag.tech>; Author <author@noreply.github.com>
Objet : Re: [facetoe/zenpy] Is there a way to get user who voted on a post ? (#297)


Yep, looks like the user id is recorded in the Vote object - https://developer.zendesk.com/rest_api/docs/help_center/votes.

**Comment by facetoe** [comment]
This should do it:

```python
for vote in zenpy_client.help_center.articles.votes(<article_id>):
    print(vote.user)
```

**Comment by sdavos** [comment]
This is for article only? Not post?


Sébastien DAVOS
CHEF D'EQUIPE SUPPORT
sdavos@smag-group.com   Hôtel d'Entreprises du Millénaire
120, allée John Napier | 34000 Montpellier | France
Tél. +33(0)3 26 21 84 20
Fax. +33(0)3 26 21 84 29
smag-group.com
________________________________
De : Facetoe <notifications@github.com>
Envoyé : dimanche 24 février 2019 01:03:19
À : facetoe/zenpy
Cc : Sébastien DAVOS; Author
Objet : Re: [facetoe/zenpy] Is there a way to get user who voted on a post ? (#297)


This should do it:

for vote in zenpy_client.help_center.articles.votes(<article_id>):
    print(vote.user)

**Comment by facetoe** [comment]
Works the same for posts:

```python
for vote in zenpy_client.help_center.posts.votes(<post_id>):
    print(vote.user)
```
