### ISSUE TITLE
Importing zenpy.__version__ on setup.py causes installation errors

### ISSUE THREAD

**Issue by fmartingr** [facetoe/zenpy#311]
Having zenpy imported on the setup.py tries to import all the references modules whitin it, failing because they are not yet installed.

The failing line: https://github.com/facetoe/zenpy/blob/ea29362a85e776f51e438c8bcc37c622f3136fc1/setup.py#L3

Commit: https://github.com/facetoe/zenpy/pull/303/commits/fdae24b9aa45000afec1f3368e4bc39db05837be

``` 
➜ docker run -it --rm python:3 bash
root@adeca9e9e3c5:/# pip install zenpy==2.0.9
Collecting zenpy==2.0.9
  Downloading https://files.pythonhosted.org/packages/7c/28/176f813940586e4b90cd1771b1474c2516fdccc6b706dad73483c8070de2/zenpy-2.0.9.tar.gz (65kB)
    100% |████████████████████████████████| 71kB 720kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-nanrf1j_/zenpy/setup.py", line 3, in <module>
        from zenpy import __version__
      File "/tmp/pip-install-nanrf1j_/zenpy/zenpy/__init__.py", line 2, in <module>
        import requests
    ModuleNotFoundError: No module named 'requests'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-nanrf1j_/zenpy/
```

If you give me directions on how do you want his handled I can make a PR myself.

But the critical thing is that right now the 2.0.9 minor version is broken on pypi.

**Comment by facetoe** [comment]
Thanks for the report. This was added recently, I'm just going to remove the import.

**Comment by facetoe** [comment]
OK I've updated the version on PyPi, let me know if you still have issues installing.

**Comment by fmartingr** [comment]
@facetoe 2.0.10 works like a charm, thanks a lot for being so fast!

**Comment by facetoe** [comment]
No worries!

**Comment by insspb** [comment]
hmmm. Interesting why it was working on tests while I PR it... hm...

**Comment by facetoe** [comment]
I think this is only an issue on initial install.

**Comment by fmartingr** [comment]
On your local environment you already had the dependencies installed so the installation of the new dependencies gives no errors, and Travis may have environments cached as well... :disappointed:
