### ISSUE TITLE
todo: Implement git clone test in travis to exclude problems like in #311

### ISSUE THREAD

**Issue by insspb** [facetoe/zenpy#312]

**Comment by cryptomail** [comment]
💀 travis?

**Comment by insspb** [comment]
@cryptomail We are too old for this :) 4 years passed )

**Comment by cryptomail** [comment]
> @cryptomail We are too old for this :) 4 years passed )

I'm doing the best I can with all the dilythium I can afford.  Please excuse the mess :)
