### ISSUE TITLE
Output of a ticket_field.to_dict() doesn't serialize to dict nested resource 'CustomFieldOption'

### ISSUE THREAD

**Issue by miguelgr** [facetoe/zenpy#313]
Hello,

I have an issue using the `TicketFieldApi` when casting `to_dict()` a ticket field as the nested resources `CustomFieldOption` are not casted to dict as well.

I've seen the issue is similar/the same to https://github.com/facetoe/zenpy/issues/284 but doing
`json.loads(ticket_field.to_dict())` doesn't seem very pythonic.

Here is an example (simplified) of the problem:

```
>>> ticket_field.to_dict()
{'active': True, 'collapsed_for_agents': False, 'created_at': '2017-02-06T18:15:31Z', 'description': '', 'editable_in_portal': False, 'id': 3853, 'title': 'Agente', 
 'custom_field_options': [CustomFieldOption(id=3929), CustomFieldOption(id=40249), CustomFieldOption(id=38005)]}
```

Thanks in advance for all the effort.

**Comment by facetoe** [comment]
Hi, which version of Zenpy are you using?

**Comment by miguelgr** [comment]
`pip install --upgrade` for `zenpy==2.0.10` did the fix. Thanks!
