### ISSUE TITLE
To check: Organization query returns list, not generator

### ISSUE THREAD

**Issue by insspb** [facetoe/zenpy#316]
During my preparations I found that:
```python
zenpy_client.organizations(ids=[tuple with 1 id])
```
return type is list, not zenpy generator. Strange.

**Comment by insspb** [comment]
During some tests: 
If we query zendesk for first time, no matter how many organizations or users in list. We will receive Generator. 
If we make same query again we will receive list.

If we query all organizations first we will receive generator. 
If we query some organizations after it we will receive list. 

Seems that it is related to caching. As not reproducible with `zenpy_client.disable_caching()`

@facetoe Should we consider this as a bug or just a note to zenpy docs? This makes not possible to check like `isinstance`.

**Comment by facetoe** [comment]
Good catch @insspb. Yep, this is a bug.
