### ISSUE TITLE
Sla loading

### ISSUE THREAD

**Issue by bstjepanovic1** [facetoe/zenpy#317]
How can I load slas? In Zendesk documentation it is stated that single ticket supports side-loading of slas. Is this supported in zenpy and if not is there other way to load slas for specific ticket? Thanks

**Comment by facetoe** [comment]
Yep, this should do the trick:

```python
zenpy_client.tickets(id=<ticket id>, include=['slas'])
```

**Comment by bstjepanovic1** [comment]
@facetoe thanks for reply. Once I get ticket how do I access `slas` data from it? I tried `ticket.slas`

**Comment by facetoe** [comment]
Yep, that should show the slas. When I run:

```python
ticket = zenpy_client.tickets(id=6827, include=['slas'])
print(ticket.slas)
```

I get:

```
{u'policy_metrics': []}
```

But that makes sense as I have no SLA policies defined in my test env:

```python
print(list(zenpy_client.sla_policies()))
```

**Comment by bstjepanovic1** [comment]
I tried that that and I get error `'Ticket' object has no attribute 'slas'`.  What am I doing wrong? I do get ticket loaded with all data.

**Comment by facetoe** [comment]
Hmm, that's weird, what version of Zenpy are you using?

**Comment by bstjepanovic1** [comment]
This is what I am doing
```python
tickets = client.search(type="ticket", created_after=bookmark)
for ticket in tickets:
	t = client.tickets(id=ticket.id, include=["slas"])
	print(t.slas)
```

**Comment by facetoe** [comment]
Looks like this is related to caching. You can disable the cache as follows:

```python
client.disable_caching()
```

Basically, the first time the ticket is retrieved it is cached but without the sideload. When you call it again you get the cached version. Disabling caching prevents this so you get the sideloaded version as expected.

**Comment by bstjepanovic1** [comment]
It is working. Thanks!
