### ISSUE TITLE
Follow-up to issue #28 for ticket metrics

### ISSUE THREAD

**Issue by ecorcor** [facetoe/zenpy#318]
Hello,
I'm getting an error when using the solution provided from a [previous post.](https://github.com/facetoe/zenpy/issues/28) 

I'm able to pull basic ticket fields as described at the start of the issue: 
ticket = zenpyClient.tickets(id=544015)
print(ticket.subject)
print(ticket.status)
print(ticket.organization.name)

However, when I attempt to pull the metrics field for a particular ticket (the exact solution provided in this issue), I get an error indicating that metrics cannot take "Ticket_id" as an argument. 
Example: 
zenpyClient.tickets.metrics(ticket_id=544015),
I get the following error:
metrics() got an unexpected keyword argument 'ticket_id'

I'm also able to call zenpyClient.ticket_metrics(ticket_id=544015), however as expected from the solution provided in issue #28, this is ignoring the "ticket_id" argument and that it is getting all metrics for all tickets. 

Please advise, thanks in advance.

Emilie

**Comment by facetoe** [comment]
Quite a while ago the method signatures changed so:

```python
zenpyClient.tickets.metrics(ticket_id=544015)
```

Should be:

```python
zenpyClient.tickets.metrics(ticket=544015)
```

For the `ticket_metrics` endpoint, as it is a "top level" endpoint, it  will return a single object when an id is passed (note, "id" here is a TicketMetric id (https://developer.zendesk.com/rest_api/docs/support/ticket_metrics), not a ticket id):

```python
zenpy_client.ticket_metrics(id=544015)
```

and all ticket metrics as a generator if no id is passed. For unknown params (such as `ticket_id`) it just ignores them and returns all metrics.

This is kindof documented here http://docs.facetoe.com.au/zenpy.html#querying-the-api, although the docs always need work...
