### ISSUE TITLE
show all identities

### ISSUE THREAD

**Issue by APWK** [facetoe/zenpy#323]
Is there a way to show all identities for all users similar to this one:
organizations = zenpy_client.organizations()
users = zenpy_client.users()

This does not work:
identities = zenpy_client.users.identities.show()
identities = zenpy_client.users.identities()
as it require arguments.

As I have to compare databases with each other I must know all email addresses of a user. Hence, I would have created a identity dictionary and pull the email addresses from there for each user. This would avoid an API request for every single user. 

Current code snippet:
users = zenpy_client.users() # get users
for user in users:
        # API users request delivers only primary email 
        # all other emails can be found via identity
        # identities have own id 
        for identity in zenpy_client.users.identities(id=user.id): 
              print(identity.value)

**Comment by Ptr314** [comment]
Hi APWK!

This library is just a wrapper to the official API. 

If there is no any endpoint you need, the library can't easily provide it. Unfortunately, the "List Identities" endpoint requires a ticket id: https://developer.zendesk.com/rest_api/docs/support/user_identities#list-identities

For my tasks, when I need to get so much data, I use multi-threading, but paying attention to the API rate limits.

**Comment by APWK** [comment]
Thanks so much for the fast fast response and the awesome work you did with Zenpy. It is a pleasure to work with it. Happy Eastern!
