### ISSUE TITLE
Null values for new ticket

### ISSUE THREAD

**Issue by ypperlig** [facetoe/zenpy#325]
When creating a ticket object and dumping to JSON all keys are included despite value being `None`. Description field is not mandatory, and in case of e.g a ticket import with comments description field should not be included because first comment will be used as description. If a description is provided the first comment will be double-up.

Reproducable with:
```python
import json
from zenpy.lib.api_objects import Ticket

def convert_ticket_to_dict(obj):
    return obj.to_dict()

test = Ticket(
    subject="Test",
    comments=[]
)

with open("test.json", "w") as f:
    json.dump(test, f, indent=4, default=convert_ticket_to_dict)
```

Output:
```
{
    "assignee_id": null,
    "brand_id": null,
    "collaborator_ids": null,
    "created_at": null,
    "custom_fields": null,
    "description": null,
    "due_at": null,
    "external_id": null,
    "fields": null,
    "forum_topic_id": null,
    "group_id": null,
    "has_incidents": null,
    "id": null,
    "organization_id": null,
    "priority": null,
    "problem_id": null,
    "raw_subject": null,
    "recipient": null,
    "requester_id": null,
    "satisfaction_rating": null,
    "sharing_agreement_ids": null,
    "status": null,
    "subject": "Test",
    "submitter_id": null,
    "tags": null,
    "type": null,
    "updated_at": null,
    "url": null,
    "via": null,
    "comments": []
}
```

Would you be open to remove null values from new tickets, or is it more ideal to filter out these values in a custom filter? I am working around this issue for ticket import specifically by just popping the description key, so it's not a major issue.

**Comment by facetoe** [comment]
You can most of the way by changing your `convert_ticket_to_dict` function as follows:

```python
def convert_ticket_to_dict(obj):
    return obj.to_dict(serialize=True)
```

The `serialize` parameter ensures only attributes that have been modified (and the id) are returned.
