### ISSUE TITLE
Search with parameter commenter not working

### ISSUE THREAD

**Issue by elianmarks** [facetoe/zenpy#327]
Hi,

I'm doing a search using the commenter parameter, but in the else of endpoint.py, the following quotation marks are inserted:
Line 258:
`
renamed_kwargs.update ({key + ':': '"% s"'% value})
`

This way the URL is generated in this format:
URL: https://XXXXXX.zendesk.com/api/v2/search.json?query=commenter:"XXXXXXX"

Using this URL Zendesk does not return any information to me, so I inserted a new elif into the __call__ function of the SearchEndpoint class with the following code:
`
elif key == 'commenter':
       renamed_kwargs.update ({key + ':': '%s' % value})
`

Removing the quotation marks from the search URL, Zendesk worked as expected.

Hugs

**Comment by facetoe** [comment]
I'm not able to replicate this. Could you please provide a minimal code snippet. The Zendesk docs for search show the value being quoted - https://support.zendesk.com/hc/en-us/articles/203663226-Zendesk-Support-search-reference.

**Comment by elianmarks** [comment]
Sorry for the delay in replies, I was traveling.
In tests that I performed by doing the search directly in the API, without using zenpy, I identified that the problem occurs when the search is performed using the user ID. When I do the search using email or user name, with or without quotation marks it works normally. However, with user ID I only get information return if it is done without quotes.

Search using e-mail without quotes.
https://prnt.sc/nlnk8a

Search using e-mail with quotes.
https://prnt.sc/nlnl2r

Search using ID with quotes.
https://prnt.sc/nlnl8j

Search using ID without quotes.
https://prnt.sc/nlnlfs

Regards

**Comment by facetoe** [comment]
Hmm interesting, thanks for the report. I'll try to have a look this weekend.

**Comment by facetoe** [comment]
I'm still not able to replicate this in Zenpy. The following code:

```python
result = zenpy_client.search(commenter=116514121092)
print "Found:", len(result)

result = zenpy_client.search(commenter="116514121092")
print"Found:", len(result)

result = zenpy_client.search(commenter="116514121092 ")
print "Found:", len(result)
```

Yields: 

```
DEBUG - https://d3v-zenpydev.zendesk.com:443 "GET /api/v2/search.json?query=commenter:116514121092 HTTP/1.1" 200 None
Found: 200
DEBUG - https://d3v-zenpydev.zendesk.com:443 "GET /api/v2/search.json?query=commenter:116514121092 HTTP/1.1" 200 None
Found: 200
DEBUG - https://d3v-zenpydev.zendesk.com:443 "GET /api/v2/search.json?query=commenter:%22116514121092%20%22 HTTP/1.1" 200 None
Found: 0
```

So it only quotes the parameter if it contains spaces. Could you post a minimal snippet that reproduces the issue?
