### ISSUE TITLE
Search query excluding multiple tags

### ISSUE THREAD

**Issue by Prodeguerriero** [facetoe/zenpy#328]
Hi there,

More of a question than an issue, to be honest.

Let's say I have the following tags:
* good_tag
* bad_tag_01
* bad_tag_02

If I wanted to search for tickets that are *not closed* and have `good_tag`, while excluding tickets with either one of the two bad tags, I would write the following in the Zendesk search bar:
- `status<closed tags:good_tag -tags:bad_tag_01 -tags:bad_tag_02`

To obtain the same search result with Zenpy, I would write
```
search_result = zenpy_client.search(
status_less_than='Closed', tags='good_tag', minus=['tags:bad_tag_01', 'tags:bad_tag_02']
)
```

While this works fine when hard-coding the search query, it becomes a bit trickier when wanting to exclude a list of tags that might change over time (let's say that the tags are sourced from a file into a set or a list, for example).
Any suggestion on how to achieve this? Maybe I am looking at this the wrong way.

**Comment by facetoe** [comment]
Seems you could just do something like (untested):

```python
def search(include_tags, exclude_tags):
    return zenpy_client.search(status_less_than='closed',
                               tags=include_tags,
                               minus=["tags:{}".format(tag) for tag in exclude_tags])
```

**Comment by Prodeguerriero** [comment]
Yup, I ended up using map() and a lambda. Should have thought about it before asking :P

Cheers

**Comment by facetoe** [comment]
All good, glad it's working :)
