### ISSUE TITLE
"objects" directory was there? and now it's gone?

### ISSUE THREAD

**Issue by berrytsakala** [facetoe/zenpy#33]
I installed zenpy from source about 2 weeks ago.
it included "/objects/" subdirectory.

Today I can't find the "objects" subdir (neither in pipy nor in github).
Where did it go?
Am I missing something?

**Comment by facetoe** [comment]
Yes you are correct @berrytsakala, the `objects` directory is no more. As the objects are generated automatically I moved them all into a single file - https://github.com/facetoe/zenpy/blob/master/zenpy/lib/api_objects.py.
