### ISSUE TITLE
Ticket object unexpected serialization behaviour.

### ISSUE THREAD

**Issue by Prodeguerriero** [facetoe/zenpy#330]
Hi there,

Here is what I am trying to achieve: add and remove tags which control values inside custom dropdown fields.

Let's take this code snippet:
```
ticket = zenpy_client.tickets(id=291990)
ticket.tags.append("test_apple")
ticket.tags.remove('test_cake')
zenpy_client.tickets.update(ticket)
```
The ticket is updated, and the tags update as well.

If I add an iteration among the custom fields, though, things stop working.
```
ticket = zenpy_client.tickets(id=291990)
ticket.tags.append("test_apple")
ticket.tags.remove('test_cake')
for field in ticket.custom_fields:
  pass
zenpy_client.tickets.update(ticket)
```
Running the above snippet, adding tags still works, while removing them doesn't seem to.

For fun, I checked what the serialization looks like.
```
ticket = zenpy_client.tickets(id=291990)
ticket.tags.append("test_apple")
ticket.tags.remove('fp2_refurb_april_19')
print(ticket.to_dict(serialize=True))
for field in ticket.custom_fields:
  pass
print(ticket.to_dict(serialize=True))
zenpy_client.tickets.update(ticket)
```
The print statement **before** the iteration returns only `id` and `tags`
```
{'id': 291990, 'tags': ['about_product', [...]
```
while the one **after** the iteration also includes all the custom fields.
```
{'custom_fields': [{'id': 25279383, 'value': None}, [...]
```
My deduction at this point is that having the fields serialized and pushed as an update is somehow overriding the tag removal.

I assume the iteration is not supposed to add the fields as something that needs an update, but maybe it is a behaviour that cannot be avoided.

I can find a workaround to this (push the tag update separately using `zenpy_client.tickets.set_tags()`) but I thought it worth sharing with you.

**Comment by facetoe** [comment]
Thanks for the report @Prodeguerriero, this is truly bizarre... I'll try to have a look this weekend.

**Comment by Prodeguerriero** [comment]
No problem, happy to help. :) I have a workaround running for now, so not a
big deal at all.

Cheers

**Comment by facetoe** [comment]
Ok this should be fixed, let me know if you get any other weird behavior.

**Comment by Prodeguerriero** [comment]
All seems to work according to plan. Thanks :)

P.S. I did not find a new release on PyPI, so I downloaded the repo and installed it with pip locally.

**Comment by Prodeguerriero** [comment]
Hi @facetoe, when do you think you'll be able to include the commit into an official release on PyPI?
I need to share the tool with a coworker and it would be easier to do so using pip and PyPI.

Thanks!

**Comment by facetoe** [comment]
No worries, created a new release - https://github.com/facetoe/zenpy/releases/tag/2.0.12.
