### ISSUE TITLE
Trying to add custom drop down field with spaces

### ISSUE THREAD

**Issue by rshariff-inter** [facetoe/zenpy#332]
i am using the ticket.create.. call to create a ticket that has a custom field which is a drop down.  It works when i put a valid value that doesn't have a space like `City` but  when i attempt to add a valid value with a space like `Center City District` the ticket gets created but the value isn't filled.
```
Ticket(subject='subject',
            description='description',
            type='problem',
            priority='normal',
            custom_fields=[CustomField(id=360000103667, value='Center City District')],
            tags=tags,
            ticket_form_id=960228
        )
```

**Comment by facetoe** [comment]
This seems to be a limitation of the API. Executing the request with `curl` doesn't seem to work either for options with spaces:

```
curl https://zenpydev.zendesk.com/api/v2/tickets/6849.json -d '{"ticket": {"id": 6849, "custom_fields": [{"id": 360019224712, "value": "Something Else"}]}}' -v -u user:pass' -X PUT -H "Content-Type: application/json"
```

**Comment by 0x10a** [comment]
Why this issue is closed if it doesn't work ?

**Comment by hassaku63** [comment]
I've meet similar problem.
In my case, it was simply i passed a wrong value to API (but I felt the documentation is a little difficult to find out these spec).

If you cloud like to create ticket with a custom field of drop down type, you must pass a TAG of field value (not field value text).

Documentation is as following:
https://developer.zendesk.com/rest_api/docs/support/tickets#setting-custom-field-values

> For fields with values defined by tags, such as drop-down lists, specify the option’s tag name for the value property, not the option text displayed in the list. For example, if the option’s display text is “HD 3000 color printer” and its tag is hd_3000, set the custom field’s value as follows: ...

**Comment by accvik** [comment]
@hassaku63 Can confirm this way works (by setting tag value instead of actual drop down value). Thanks for the help!
