### ISSUE TITLE
Inconsistency issues

### ISSUE THREAD

**Issue by amitassaraf** [facetoe/zenpy#333]
Hey,

I believe this might be coming from a rate limit of some sorts on the Zendesk API, but when running the following query, it sometimes returns results and sometimes doesn't.

```
open_tickets = zenpy_client.search(type='ticket', requester_id=int(zendesk_id), status='open')
open_ticket_queue = deque(open_tickets, maxlen=1)
```

The thing is that it is not that I get an exception that I hit the rate limit but I actually just get a response with no tickets and this screws up the logic in my platform. and I am not even sure that this is a rate limit issue, might be something else that causes the inconsistency.

Do you know how I can solve this?

**Comment by facetoe** [comment]
Hi @amitassaraf, I've found the search endpoint can take a while to return newly created tickets, so you are not guaranteed to be returned all existing matches all the time, especially if they are new.

You might be able to use views to achieve what you are after - https://developer.zendesk.com/rest_api/docs/support/views.

Hope this helps.
