### ISSUE TITLE
New search API results limit -> 1000

### ISSUE THREAD

**Issue by gitlech** [facetoe/zenpy#334]
Today Zendesk customers received an email from Zendesk stating that the results from querying the search API will be limited to 1.000 starting from 15.10.2019 (today limit is 200.000). I would not expect any impacts on the incremental APIs regarding this change. Can you confirm?

**Comment by facetoe** [comment]
Should be fine. The generator that handles pagination just keeps consuming pages until there are no more left, it's really up to Zendesk how many they send.
