### ISSUE TITLE
zenpy in Python 3

### ISSUE THREAD

**Issue by ecorcor** [facetoe/zenpy#335]
"Zenpy supports both Python2 and Python3", however when I import zenpy in Python 3, I get the following error:
ModuleNotFoundError: No module named 'zenpy'

When I do the same thing in Python 2.7, I have no problem. I've tried re-running the pip install zenpy command, with no luck. Help would be greatly appreciated.

**Comment by facetoe** [comment]
Most likely you have installed Zenpy into your Python2.7 installation. Can you try: `pip3 install zenpy`?
