### ISSUE TITLE
Access Denied, Do I Need OAuth? I have Password and API Token

### ISSUE THREAD

**Issue by zonecodez** [facetoe/zenpy#336]
When I run:

`for ticket in zenpy_Client.search('zenpy', created_between = [yesterday, today], type = 'ticket', minus = 'negated'):
    print(ticket)
`
Nothing is returned, no matter how large I make the interval. Then when I run:

`for user in zenpy_Client.users():
    print(user.name)`

I receive this error: ""Forbidden", "message": "You do not have access to this page. Please contact the account owner of this help desk for further help." "

I have entered, username, subdomain, api token and password. Could it be that I need to enter an OAuth token for these types of queries?

I am not the Admin of the Zendesk account in question, but I am an agent and I have access to the admin to be granted any permissions.

Thank you for this tool.

**Comment by zonecodez** [comment]
Please help!

**Comment by insspb** [comment]
@zonecodez I do not have a system to test this behavior, maybe @facetoe will help. 
But for my opinion error message is self-described. You have no access. 

From the technical part, I used zenpy with any type of auth and have no problems with it, but I always have admin rights.

**Comment by facetoe** [comment]
Hi @zonecodez, yep as @insspb points out, it is an access issue. The API is not available to all agents necessarily, this needs to be enabled by the admin. You might be able to ask them for an API token, however this comes with essentially admin permissions so they might not want to. Alternatively, the API can be enabled with normal user/pass credentials, or if you need tightly scoped permissions you could consider using an OAuth token with just the access that is required.

Hope this helps!

**Comment by zonecodez** [comment]
I have been given an API token and Oauth token

**Comment by zonecodez** [comment]
Please reopen this

**Comment by facetoe** [comment]
Yes they need to enable API access, this page might help - https://support.zendesk.com/hc/en-us/articles/115002555167-Using-the-API-dashboard.

> In the Settings tab, enable password or token access.

If you still have issues you're probably better of reaching out to Zendesk. This doesn't seem to be an issue with the Zenpy library, more an issue with the Zendesk API access.
