### ISSUE TITLE
Circleci integration

### ISSUE THREAD

**Issue by insspb** [facetoe/zenpy#338]
Circleci was integrated in PR #324, but what it gives to the project? 
At this point, I cannot find Circleci badge in docs, or cannot find PR build in Circleci itself. 
All this service is done at this moment is to bring more CI/CD configuration, with no effect. 

So there can be to solutions and you need to choose one. 
1. Update Circleci configuration and integrate it to GitHub on PR as Travis does. But I do not see any benefits, only project complexity. 
2. Drop Circleci support.

**Comment by facetoe** [comment]
I'm half planning on migrating away from Travis at some point as they have been acquired. The CircleCI code is not doing any harm that I can see, and it will come in handy whenever I get the motivation to do the transition.
