### ISSUE TITLE
Avoid setting logging options

### ISSUE THREAD

**Issue by dangerwheeler** [facetoe/zenpy#34]
Setting the logging options in https://github.com/facetoe/zenpy/blob/master/zenpy/__init__.py wreaks havoc on the logging configuration of consumers of the module. I would recommend removing the logging configuration and simply let ZenPy consumers handle it.

**Comment by facetoe** [comment]
Good point @dangerwheeler, I've removed the offending code (20f1bcc06bd7c5d1df093d9fe260435780ffb513). Thanks for the suggestion!

**Comment by dangerwheeler** [comment]
Epic! Thanks!

**Comment by facetoe** [comment]
No worries :)
