### ISSUE TITLE
NameError: name 'Ticket' is not defined

### ISSUE THREAD

**Issue by trr-RodriguesJD** [facetoe/zenpy#341]
I keep getting NameError: name 'Ticket' is not defined when running

`from zenpy import Zenpy

zenpy_client = Zenpy(oauth_token="TOKEN")

zenpy_client.tickets.create(Ticket(subject="Test", description="Thing"))

for ticket in zenpy_client.search('PC LOAD LETTER', type='ticket', assignee='EMAIL'):
    print(ticket.requester.name)
    print(ticket.to_dict())
    print(ticket.to_json())`

**Comment by insspb** [comment]
Add this line and will work: 
```python
from zenpy.lib.api import Ticket
```

Final result:

```python
from zenpy import Zenpy
from zenpy.lib.api import Ticket

zenpy_client = Zenpy(oauth_token="TOKEN")

zenpy_client.tickets.create(Ticket(subject="Test", description="Thing"))

for ticket in zenpy_client.search('PC LOAD LETTER', type='ticket', assignee='EMAIL'):
    print(ticket.requester.name)
    print(ticket.to_dict())
    print(ticket.to_json())
```
