### ISSUE TITLE
Is it possible to get ticket number after creating one?

### ISSUE THREAD

**Issue by taufique786** [facetoe/zenpy#342]
I am able to create tickets with zendesk using Zenpy but is it possible to get the ticket number right after its creation?

**Comment by facetoe** [comment]
Yep, when you create a ticket an TicketAudit object is returned, which contains the ticket, eg:

```python
ticket_audit = zenpy_client.tickets.create(Ticket(description='test', subject='test'))
print(ticket_audit.ticket.id)
```
