### ISSUE TITLE
<zenpy.lib.generator.SearchResultGenerator at 0x109c94780>

### ISSUE THREAD

**Issue by LewisCharlesBaker** [facetoe/zenpy#345]
Hello! I have been working through the sample API requests and keep encountering - 

<zenpy.lib.generator.SearchResultGenerator at 0x109c94780>

I cannot identify a method for avoiding this. I have done some pretty deep searching, well at least I think I have!

Any help is hugely appreciated.

Thanks in advance,

**Comment by insspb** [comment]
HI @LewisCharlesBaker 
I do not understand you problem. 
It seems that you have use `zenpy_client.search()` endpoint somewhere and then just calling result of this action. 
But by default all zenpy_client answers are generators. 
If you need list you can unpack generator with list comprehension. 
Like
```python
[something for something in zenpy_client.search()]
```

**Comment by facetoe** [comment]
Yup, many endpoints return generators. So you can unpack the generator as @insspb shows, or you could iterate over it directly, eg:

```python
for ticket in zenpy_client.tickets():
    print(ticket)
```

Hope this helps!

**Comment by LewisCharlesBaker** [comment]
Hi!

That does actually seem to work. That's really helpful. Thank you.

**Comment by insspb** [comment]
@facetoe they always quote your answers. What I doing wrong. Haha :question: :smiley:

**Comment by facetoe** [comment]
I don't think you're doing anything wrong haha, sometimes people just answer the last person that commented :)

**Comment by LewisCharlesBaker** [comment]
Hi Both,

I have another quick question, hope that's okay.

Would it be possible to return a json / dataframe with all the columns &
rows of the User & Tickets table?

Many thanks in advance,

Lewis
