### ISSUE TITLE
Update custom_fields documentation?

### ISSUE THREAD

**Issue by tgehrs** [facetoe/zenpy#346]
Yesterday I was using this library to update a large number of tickets was having trouble updating a ticket's custom_fields according to the documentation in the readme:
```
ticket = zenpy_client.tickets(id=some_ticket_id)
ticket.custom_fields.append(CustomField(id=43528467, value=1337))
zenpy_client.tickets.update(ticket)
```
This did not work for me, the custom field did not seem to save for some reason.

To debug I took a look at ticket.custom_fields it then looked like  a dictionary with the custom_field already existed:
`[..., {'id': 43528467, 'value': None}, [CustomField(id=43528467)]]`

The only way I was able to get the custom_field to update is the following:
```
ticket = zenpy_client.tickets(id=some_ticket_id)
for f in ticket.custom_fields:
    if f['id'] == 43528467:
        f['value'] = 'field_value' #actual value instead of ID
zenpy_client.tickets.update(ticket)
```

Was I doing something incorrect the when trying the documented solution? If not and the documentation needs to be updated I would be happy to put together a PR

**Comment by facetoe** [comment]
PRs welcome.
