### ISSUE TITLE
Retries policy on ZendeskResultGenerator

### ISSUE THREAD

**Issue by Teoretic6** [facetoe/zenpy#348]
More of a question than an issue but still...

Let's say **I want to iterate over generator by chunks and then save chunks to database.**
```
zenpy_client = Zenpy(**zendesk_creds)
tickets_gen = zenpy_client.tickets()

while True:
    tickets = get_values_from_zendesk_gen(tickets_gen, chunk_size=10000)

    if not tickets:
        break

    # saving tickets to database...
    # save_to_database(tickets)
```

I want to iterate by chunks using a function `get_values_from_zendesk_gen` **with exponential retries over it** (through `tenacity` package or any other implementation)

```
@retry(stop=stop_after_attempt(4),
       wait=wait_exponential(multiplier=1))
def get_values_from_zendesk_gen(zendesk_gen, chunk_size):
    items = [i.to_dict() for i in itertools.islice(zendesk_gen, chunk_size)]

    return items
```

So the question is - **if I fail in the middle of `itertools.islice(zendesk_gen, chunk_size)` (network error, for example) and then make a retry of `itertools.islice(zendesk_gen, chunk_size)`, will I still get previous data from the generator?** 

**Example**
Let's make an example - in my example `chunk_size` equals to 10000. This is a multiple-page chunk.

Let's say that **there's a network error in the middle of a chunk retrieval** (in `get_values_from_zendesk_gen` function). 
**So some queries to Zendesk API has already been made** but when network was lost not all data was retrieved yet.

The exception was handled by `tenacity` package and `get_values_from_zendesk_gen` function was called again with the same `zendesk_gen` object and the same `chunk_size`.

If I understand correctly, **the old data (that was queried from Zendesk API before network error) will be lost and chunk of new 10000 tickets will be returned.**

**So how can I implement retries policy in this situation?** 
If there's an error occurred than should I recreate `ZendeskResultGenerator` object? (by calling `tickets_gen = zenpy_client.tickets()`)

**Comment by facetoe** [comment]
I'm not really sure to be honest, I would have to run some experiments to find out.
