### ISSUE TITLE
filtering users() by group always returns all users

### ISSUE THREAD

**Issue by netllama** [facetoe/zenpy#351]
I'm attempting to filter the users returned by a specific group, but no matter what I specify for the group, it always returns all users, regardless of group membership.

I've tried doing it by group id:
users = api.users(group=360005453791)

and also group name:
users = api.users(group='Ops')

This group has 14 members, but I always get back thousands of users from the 2 calls above.  Am I doing something wrong, or is there a bug lurking?

**Comment by facetoe** [comment]
Hi,

You can achieve what you want as follows:

```python
for user in zenpy_client.groups.users(group=group_id):
    print(user.name)
```
