### ISSUE TITLE
possible to search tickets updated by specific list of users?

### ISSUE THREAD

**Issue by netllama** [facetoe/zenpy#358]
I'm trying to compose a search query that will return tickets where ```updated_before``` is a parameter, but only for a specific list of users.  In other words, the search should return all tickets that were updated before a specific date, as long as the updates were performed by the specified list of users.  

Without the list of users, its a fairly straightforward query:

```zenpy_client.search("zenpy",'type'='ticket', 'updated_before'=days_ago)```

But I'm at a complete loss how to do this with a specific list of users.

**Comment by insspb** [comment]
@netllama 

If you need to search for tickets with some assignees:
```python
zenpy_client.search(type='ticket', updated_before=days_ago, assignee=assignees)
```
If you need to search for tickets with some requesters:
```python
zenpy_client.search(type='ticket', updated_before=days_ago, requester=requesters)
```
``assignees`` and ``requesters`` are itterables of users ids. Not sure that will work with ``User`` objects, cannot test now.

You may use any keywords like in advanced zendesk search in web interface.

**Comment by netllama** [comment]
@insspb   Thanks for the tips, but I don't think this answers my question.  What I need to do is search for tickets that were (or were not) updated by a specific list of requesters, yet not others.  The key detail is forming an association between the updated time range and which user(s) have performed the update.

The intent is to perform a specific action with a ticket if it has not been updated by a specific list of requesters in the past X days.  For example, I'd want a list of all tickets that were last updated at least 7 days ago as long as the user performing the update was not my user.  Thus, I could update the ticket every day, but the API call would still return the ticket as long as no other user had updated the ticket in the past 7 days.

**Comment by facetoe** [comment]
As @insspb mentions, you can perform any search supported by Zendesk in the web interface. If you can't build a search query that solves your problem, then you will need to write some custom code to achieve what you want.

**Comment by insspb** [comment]
@netllama if you need any custom code or application (like Zendesk app with custom reports. You can contact me directly and hire to code the whole project. My contacts and portfolio as a freelancer is in my profile.
