### ISSUE TITLE
Support for Jira Links API pagination

### ISSUE THREAD

**Issue by LewisDavies** [facetoe/zenpy#359]
I'm using `Zenpy.jira_links()` to retrieve data on Jira tickets raised via the Zendesk integration. We recently passed the 1000 ticket barrier and Zenpy is now only returning the first 1000 results. 

I did some digging and it appears that Zenpy is looking for the next page header, but this endpoint doesn't provide one. I contacted Zendesk and here's their reply:

> The API design for JIRA integration is as you describe (no next_page). We use cursor-based pagination. This is because Offset-based pagination is inefficient and has a significant performance impact - especially for large offsets. Offset-based pagination may also return incorrect results if the underlying data served by API mutates.

They recommended using the `since_id` option to get the results in batches but this doesn't seem compatible with how the library currently works. I'd love to contribute in some way but frankly have no idea where to start - any help or pointers would be appreciated!

**Comment by insspb** [comment]
Hi @LewisDavies 
Thank you for the post. I personally do not understand the whole problem and whall issue. 
Can you share some reproducible example with code, so I can understand what you try to do, and where is the problem is.

**Comment by facetoe** [comment]
@LewisDavies there is an example of a cursor based generator here - https://github.com/facetoe/zenpy/blob/master/zenpy/lib/generator.py#L204. I'm guessing you can use the same logic just need to target `since_id` instead. 

Let me know if you have any questions!

**Comment by LewisDavies** [comment]
Thanks for the quick replies! I've looked into this today and I'm struggling with the best way to fix the issue.

The main problem is that unlike all other API endpoints I've checked, the [Jira Integration API](https://developer.zendesk.com/rest_api/docs/services/jira#list-links) doesn't return the URL for the next page. @facetoe It seems like in your example you're overriding where to find the URL but this won't work for the Jira endpoint because it doesn't exist.

Instead, we need to provide a ticket ID to search from. Let's say I've run this:
```
zenpy_client = Zenpy(**creds)
jira_links = zenpy_client.jira_links()
```

The raw JSON contains two arrays: `links`, the IDs and timestamps of links created through the Jira integration; and `total`, which is simply an integer of how many links exist. A maximum of 1000 links will be returned at once.

To access the next batch I need to know the last ID in the first batch of links, then submit a new request using that ticket ID as the `since_id` parameter. Basically, we need to construct our own URL to access the next batch of links. I've tried making a new generator class to do this, but I don't know the best way to pass the proper endpoint to it from the `JiraLinkApi`.

Hopefully that's relatively clear - any pointers you can provide would be appreciated.
