### ISSUE TITLE
Status open when creating ticket

### ISSUE THREAD

**Issue by OscarPDR** [facetoe/zenpy#361]
Hi! When I create a new ticket using zenpy, it is created with status='open', when it should be 'new'. As the update method doesn't allow 'new' as a valid status, there is no further way of modifying it.
I have tried to create a ticket through a POST request using the official API and the status is set to 'new' by default, as it should be.

**Comment by facetoe** [comment]
When I create a ticket via the API with curl it also creates the ticket in the "open" state. Zenpy does not send a status unless you define one, so this is an issue to raise with Zendesk.
