### ISSUE TITLE
Export custom field value

### ISSUE THREAD

**Issue by rafaga444** [facetoe/zenpy#362]
Hello.
How can i print custom ticket field values with specific id?
It tried this
`for ticket in zenpy_client.views.tickets(my_view_id):`
    `wallet = ticket.custom_fields(id=360017093212)`
    `print(ticket.id, ticket.requester.email,wallet)`
but obviously it doesn't work. Could you please help me.

**Comment by facetoe** [comment]
This should do it:

```python
for ticket in zenpy_client.tickets():
    print(next((filter(lambda f: f["id"] == 360001824571, ticket.custom_fields)), None))

```
