### ISSUE TITLE
Cannot Query Ticket_Metrics

### ISSUE THREAD

**Issue by jbreen18** [facetoe/zenpy#365]
Hello,
There is an API page which has useful information for my tickets with the URL:
...api/v2/ticket_metrics...,
but if I try to query it as:
"result_generator = zenpy_client.ticket_metrics(ticket_ids=[1,2])"
then instead of giving the metrics of tickets 1 and 2 it dumps the metrics of every ticket. I cannot find any suitable alternative, could you please advise why this is happening?

Thank you :)

**Comment by facetoe** [comment]
Zendesk doesn't support querying multiple ticket metrics by id, only listing all and by specific ids - https://developer.zendesk.com/rest_api/docs/support/ticket_metrics#show-ticket-metrics.

It's a bit slower but you can ask for each individually:

```python
ticket_metric = zenpy_client.tickets.metrics(ticket=10)
print(ticket_metric)
```
