### ISSUE TITLE
UserIdentityApi.update convert identity to id so payload is incorrect

### ISSUE THREAD

**Issue by dstarod** [facetoe/zenpy#366]
Decorator `extract_id` under UserIdentityApi.update method convert argument `identity` into integer id, so `self.build_payload(identity)` generate `{'identity': ID}` instead of correct json document.

**Comment by facetoe** [comment]
Can you post a snippet that causes the failure and  a stacktrace?

**Comment by dstarod** [comment]
> Can you post a snippet that causes the failure and a stacktrace?

`zenpy_client = Zenpy(
    subdomain='subdomain',
    email='email@domain.com',
    token='token',
)

user = zenpy_client.users(id=9876543210)
identity = list(zenpy_client.users.identities(user.id))[0]
identity.value = 'customer@example.com'
zenpy_client.users.identities.update(user, identity)

Traceback (most recent call last):
  File "/path/to/zenpy_sketch.py", line 17, in <module>
    zenpy_client.users.identities.update(user, identity)
  File "/path/to/zenpy/lib/util.py", line 110, in inner
    return func(*new_args, **new_kwargs)
  File "/path/to/zenpy/lib/api.py", line 606, in update
    return UserIdentityRequest(self).put(self.endpoint.update, user, identity)
  File "/path/to/zenpy/lib/request.py", line 191, in put
    return self.api._put(url, payload=payload)
  File "/path/to/zenpy/lib/api.py", line 104, in _put
    response = self._call_api(self.session.put, url, json=self._serialize(payload), timeout=self.timeout)
  File "/path/to/zenpy/lib/api.py", line 149, in _call_api
    self._check_response(response)
  File "/path/to/zenpy/lib/api.py", line 288, in _check_response
    raise APIException(json.dumps(_json), response=response)
zenpy.lib.exception.APIException: {"error": {"title": "Invalid attribute", "message": "... Invalid parameter: identity must be a hash"}}
`

**Comment by facetoe** [comment]
Need to build release.

**Comment by dstarod** [comment]
> Need to build release.

Waiting for this one :)

**Comment by facetoe** [comment]
Pushed a new version - https://github.com/facetoe/zenpy/releases/tag/2.13
