### ISSUE TITLE
Requested response size was greater than Search Response Limits

### ISSUE THREAD

**Issue by jokerejoker** [facetoe/zenpy#371]
I get this exception when doing a search.
```
raise APIException(json.dumps(_json), response=response)
zenpy.lib.exception.APIException: {"error": "invalid", "description": "Invalid search: Requested response size was greater than Search Response Limits"}
```

Simple query is `zenpy_client.search(query="created<1year", type="ticket")`

When doing the same search in zendesk it show a count of 1028 entities.

According to the documentation the limit on search is 100 entities per page. How do I force this limit?
https://developer.zendesk.com/rest_api/docs/support/search#results-limit

**Comment by facetoe** [comment]
Looks like you're out of luck - https://develop.zendesk.com/hc/en-us/articles/360022563994--BREAKING-New-Search-API-Result-Limits

**Comment by UtsavChokshiCNU** [comment]
@facetoe ..
Just curious : 
I can retrieve 14K tickets with following call. How is it possible (if search API can send 1000 results at max) ?
```
tickets = zenpy_client.search(type='ticket', status='closed', created_between=[start_date, end_date])
```
Have you incorporated Incremental API. I went through code but could not find traces of incremental API being used in `SearchResultGenerator`.
By the way, I am using `zenpy==2.0.12`
