### ISSUE TITLE
Searching for tickets with no organization

### ISSUE THREAD

**Issue by aesmat1** [facetoe/zenpy#372]
I need to search for tickets with no organization (None, or Null)

How to use a search like:
`zenpy_client.search(type='ticket', organization=org)`

What to use instead of org? I tried 'None', 'none', 'Null', 'null', and nothing is working. But when I pull all the tickets I get tickets with organizations ids and also the ones with nulls

Please help

**Comment by facetoe** [comment]
This is more of a Zendesk question than a Zenpy question. If you can't define a search that does what you want in the interface then you can't do it in Zenpy. One random suggestion is it could be possible to do this with views somehow - https://developer.zendesk.com/rest_api/docs/support/views

**Comment by aesmat1** [comment]
I need something equivalent to:
`https://mdomain.zendesk.com/api/v2/search.json?query=type:ticket organization:none
`
which \h is returning some 34 records, how can I do this in Zenpy?

**Comment by facetoe** [comment]
Have you tried:

```python
zenpy_client.search(type='ticket', organization='none')
```

Might work.

**Comment by aesmat1** [comment]
Yes I tried None, none, Null, null and ''
This is similar to https://github.com/facetoe/zenpy/issues/294

**Comment by ypperlig** [comment]
Using client.search(type='ticket', organization='none') works fine for me:
DEBUG - https://company.zendesk.com:443 "GET /api/v2/search.json?query=type:ticket%20organization:none HTTP/1.1" 200 None

Which version of Zenpy are you currently running?

**Comment by aesmat1** [comment]
Zenpy 2.0.12

**Comment by facetoe** [comment]
I've also tested this and passing `organization="none"` also works for me.
