### ISSUE TITLE
It not 100% clear what the prefered way to pass credentials to zenpy

### ISSUE THREAD

**Issue by Wheaties466** [facetoe/zenpy#374]
I see there is a json file in the test environment. But in the quick start or docs there is built in logic to parse that. If this can be clarified to me I would like to update some of the docs or write some logic on the preferred way to handle this.

**Comment by facetoe** [comment]
It depends on your preferred authentication method, see the docs for more info - http://docs.facetoe.com.au/zenpy.html#usage

**Comment by Wheaties466** [comment]
Thanks, didn't see this part in the docs.
