### ISSUE TITLE
Add GitHub Sponsors

### ISSUE THREAD

**Issue by shicholas** [facetoe/zenpy#375]
@facetoe, this is an awesome project. And while I don't have much time to contribute to it, I would love to pay for more features here to be developed.

It'd be great if you consider adding GitHub sponsors to this project so it can encompass more of the Zendesk API. For me, I am looking for integrations into Zendesk Guide and Zendesk Sell.

What do you think? My email is nick@1337lawyers.com if you'd like to take this discussion offline.

**Comment by facetoe** [comment]
Hi @shicholas, thanks for your interest in Zenpy. I'd be happy to take you up on your offer early next year but wouldn't be able to do much earlier. Am super busy at the moment as recently started a new job, so not much time to work on Zenpy. I've signed up for Github sponsors so we will see if that goes through.

Also FYI most of Zendesk Guide (called Help Centre in their docs) is implemented in Zenpy it is just poorly documented. You can see what is available here - https://github.com/facetoe/zenpy/blob/master/zenpy/lib/api.py#L2080.

I had a quick scan of the Zendesk sell docs and it looks pretty doable. The format is different to the other Zendesk APIs but it looks fairly consistent.

**Comment by shicholas** [comment]
great! I hope GitHub Sponsors goes through too and thanks for sharing the Guide API.

**Comment by facetoe** [comment]
Hi @shicholas, I've added Github sponsors to the project and it has all gone through.

**Comment by shicholas** [comment]
great, happy holidays! once you're settled in your new job, please reach out and let's chat a bit.

**Comment by facetoe** [comment]
Yep no worries, will reach out early January. Happy holidays!
