### ISSUE TITLE
2.0.13 version - AttributeError: 'SearchApi' object has no attribute '_get_user'

### ISSUE THREAD

**Issue by meathead2k2** [facetoe/zenpy#378]
The following no longer works and throws a Attribute Error.

AttributeError: 'SearchApi' object has no attribute '_get_user'

```
for tick in zenpy_client.search(type='ticket', status=["new","open","pending","solved"], created_between=[yesterday, now]):

ticket_req_email = tick.requester.email

```

**Comment by facetoe** [comment]
Thanks for the report @meathead2k2, will fix it up ASAP

**Comment by facetoe** [comment]
I pushed a new version, should be good now.

**Comment by meathead2k2** [comment]
Good stuff, will let you know if I notice anything else.
