### ISSUE TITLE
Release 2.0.13 has backwards incompatible change

### ISSUE THREAD

**Issue by lukeburden** [facetoe/zenpy#379]
Hola,

It appears the 2.0.13 release has changed the interface for uploading attachments.

Prior to 2.0.13, you could call:

```python

file_obj = <some file-like object>

client.attachments.upload(
    file_obj,
    target_name=file_obj.filename,
)
```

Starting 2.0.13, using this function in this same way results in the error:

```expected str, bytes or os.PathLike object, not <file_obj.__class__>```

This caused an outage for at my work-place today, as we assumed (somewhat naively) that Zenpy is semantically versioned and that therefore within a major version release, backwards compatibility would be respected.

We've rolled back to 2.0.12 and this resolved the issue for us.

Was this change intentional? Of course, bugs happen, I'm mostly keen to understand how you version this library and therefore how I and others should be defining it as a dependency. Does Zenpy aim to use semantic versioning?

Thanks for your work @facetoe.

**Comment by lukeburden** [comment]
It appears this breakage is caused by the following line:

https://github.com/facetoe/zenpy/commit/c08b5ea40c601ae9f82f39df9d66497a17d06d4f#diff-7d94d3873e4c95215581e088518e68bfR223

That should probably have been an `elif` rather than `if`.

Here are some repro steps:

```python
from zenpy import Zenpy

f = open('somefile.txt', 'w')
f.write('haha')
f.close()

f = open('somefile.txt', 'r')

creds = {
    "email": "yourshere",
    "token": "yourshere,
    "subdomain": "yourshere",
}

client = Zenpy(**creds)


attachment = client.attachments.upload(
    f,
    target_name='somefile.txt'
)
```

With 2.0.12 this works fine, with 2.0.13 and 2.0.14, this results in the following traceback:

```
TypeError                                 Traceback (most recent call last)
<ipython-input-1-cba3417fd409> in <module>
     18 attachment = client.attachments.upload(
     19     f,
---> 20     target_name='somefile.txt'
     21 )

/usr/local/lib/python3.7/site-packages/zenpy/lib/api.py in upload(self, fp, token, target_name, content_type)
    889             Zendesk API `Reference <https://developer.zendesk.com/rest_api/docs/core/attachments#uploading-files>`__.
    890         """
--> 891         return UploadRequest(self).post(fp, token=token, target_name=target_name, content_type=content_type)
    892
    893     def download(self, attachment_id, destination):

/usr/local/lib/python3.7/site-packages/zenpy/lib/request.py in post(self, fp, token, target_name, content_type, api_object)
    228             target_name = target_name or fp.name
    229
--> 230             fp = open(fp, 'rb')
    231
    232         elif isinstance(fp, str):

TypeError: expected str, bytes or os.PathLike object, not _io.TextIOWrapper
```

**Comment by facetoe** [comment]
HI @lukeburden, change was not intentional. Zenpy doesn't use semantic versioning but changes should be backwards compatible.
