### ISSUE TITLE
Tickets: filter & sideload at the same time

### ISSUE THREAD

**Issue by Senpos** [facetoe/zenpy#384]
Hey!

I was wondering if there's a way to both filter and sideload data at the same time.

Example:
```python
tickets = zendesk.search(tags=vip_tags, status=['new', 'open'], include=['users', 'slas'])
for ticket in tickets:
    print(ticket.slas)
```

At the moment, this gives me an empty result, since it assumes that the `include` keyword is a Zendesk keyword, not a sideload attempt.

Do I have to use the following pattern?
```python
tickets = zendesk.search(tags=vip_tags, status=['new', 'open'])
for filtered_ticket in tickets:
    ticket = zendesk.tickets(id=filtered_ticket.id, include=['users', 'slas'])
```

I have also tried to do this:
```python
tickets = zendesk.tickets(tags=vip_tags, status=['new', 'open'], include=['users', 'slas'])
```

But I guess, it is not possible to do filtering outside of `search` method.

Thanks!

**Comment by Senpos** [comment]
> Do I have to use the following pattern?

Ah, this method has its own [disadvantages](https://github.com/facetoe/zenpy/issues/317#issuecomment-477072947). :(

**Comment by facetoe** [comment]
Yep that's pretty much the state of things. In your case though disabling caching for this purpose doesn't cost you anything as you have to query Zendesk for each filtered ticket no matter what.
