### ISSUE TITLE
Allow to disable cache for particular entities

### ISSUE THREAD

**Issue by Senpos** [facetoe/zenpy#387]
At the moment, we can only disable cache as a whole.

But it would be useful to disable cache only for **tickets** or for **users** etc

That would solve the problem with search & sideloading tickets described [here](https://github.com/facetoe/zenpy/issues/317#issuecomment-477072947)

As a workaround. I modify `venv/Lib/site-packages/zenpy/lib/cache.py` by hand and comment out `ticket`, so they will not be cached, while other entities will:
```python
class ZenpyCacheManager:
    def __init__(self, disabled=False):
        ...
        self.mapping = {
            ...
            # 'ticket': ZenpyCache('TTLCache', maxsize=10000, ttl=30),  <--- here
            ...
        }
```

In my use case, it decreases the load time by a half (which is useful when the script is running in AWS Lambda or similar platforms, who charge users for execution time).

Something like this would be awesome:
```python
zendesk.disable_caching()  # for all entities
zendesk.disable_caching(tickets=True)  # only for tickets
zendesk.disable_caching(tickets=True, users=True)  # for tickets and users
```

Please, share your thoughts on this and thanks for your time.

**Comment by Senpos** [comment]
I ended up with this:
```python
zendesk = Zenpy(...)
del zendesk.cache.mapping['ticket']
```

Not the prettiest solution, but works just fine :D

**Comment by facetoe** [comment]
There is also a method for this, eg:

```python
zenpy_client.delete_cache("ticket")
```
