### ISSUE TITLE
Inconsistencies with the ticket attachment upload endpoint

### ISSUE THREAD

**Issue by sundayj** [facetoe/zenpy#388]
I've recently had issues with attachment uploads failing when submitting and/or updating tickets in Zendesk. The program I wrote that utilizes your awesome package has been working very well for the past year, but over the last month or so the attachment uploads have been failing regularly. I'm attaching the emails I've received directly from Zendesk's support in case it may help resolve this issue. TLDR: It looks like the failed attempts are all utilizing the GET method instead of the POST method and the request headers seem to be lacking the content_type of "application/octet-stream."
[Zendesk_Zenpy_Attachment_Upload_Errors.zip](https://github.com/facetoe/zenpy/files/3995281/Zendesk_Zenpy_Attachment_Upload_Errors.zip)
The zip folder contins the original error text file and the email thread with Zendesk as an outlook file, a text file, and an html file to make sure it can be opened on your end. Thank you for your assistance!

**Comment by facetoe** [comment]
Thanks for the report @sundayj. There were some changes to the code that handles attachment uploads recently and this seems to have broken something. Until I have a chance to look into this, others are reporting that rolling back to version 2.0.10 (#382) fixes the issue so that may help you also.

**Comment by sundayj** [comment]
Thank you! I will give that version a shot and let you know. It looks like it was failing for me at version 2.0.12 and up. In case this helps you out, here is the last response between myself and the Zendesk support team:
[Zendesk Support Re Ticket attachment upload API failure..zip](https://github.com/facetoe/zenpy/files/4005244/Zendesk.Support.Re.Ticket.attachment.upload.API.failure.zip)
I've included debugging info from my IDE as well as what Zendesk support thinks the most likely cause may be.

**Comment by facetoe** [comment]
That is super useful info, thanks!

**Comment by sundayj** [comment]
Awesome! Your hard work has really helped me out in my job, so I'm happy to help in any way I can. However, I just noticed in the screenshot of that message in the zip folder that one of the headers shows the user-agent as "Zenpy/2.0.10."

**Comment by facetoe** [comment]
That hasn't been updated in a while - https://github.com/facetoe/zenpy/blob/master/zenpy/__init__.py#L47. Should either remove it or add some tooling to manage it as right now it doesn't track the actual version.

Something that would be very useful though is an example that consistently fails/returns the 502. I haven't been able to replicate this issue which makes it a bit tricky to fix. I think it is likely though that https://github.com/facetoe/zenpy/pull/373/files is the culprit as it changed the file upload code path, and makes it possible to submit a request without any content-type headers set. 

In any case, I should have some time to look into it properly in the next week or so.

**Comment by allan-simon** [comment]
Hello here's a code that reproduces the issue consistently 

```python
from io import BytesIO
from zenpy import Zenpy # type: ignore

zendesk_client = Zenpy(
    subdomain="your_subdomain",
    token="your_token",
    email="your_email",
)

upload_token = zendesk_client.attachments.upload(
    BytesIO(b"a"*1024*1024), target_name="xxxx.txt"
)
```

I will try to also have a look in the issue if you want (as it's quite blocking for me)

**Comment by facetoe** [comment]
Thanks @allan-simon, I've pushed a fix and uploaded a new version.
