### ISSUE TITLE
allow domain to be overridable from Zenpy()

### ISSUE THREAD

**Issue by allan-simon** [facetoe/zenpy#391]
currently it is hardcoded to "zendesk.com" in some environment, mainly local dev environment where we have a mock of zendesk apis (soon to be opensourced \o/ ), it would be great to be able to replace it by "whatever" , so that  just by changing env variables, one could point to a "local zendesk" which permits greated flexibility when testing. (especially when you have a dozen of developers that all try to create a ticket referencing a "external_id=1" ^^")

if such a change is welcomed, I would be glad to try at providing the PR

it could be either 

1. exposing `domain`
2. introducing "base_url" (so that one can put `http://localhost:4343`)

(I personnally think the second one makes more sense, as 1. is very limited in term of use case)

**Comment by facetoe** [comment]
Yep, makes sense and should be a relatively simple change 👍

**Comment by naomatheus** [comment]
Hi @allan-simon and @facetoe 

I have a similar need to change the preset subdomain to accommodate Zendesk accounts which have custom domain mapping enable (i.e. do not have the domain suffix `zendesk.com`). 

Found the preset here in BaseApi class in api.py :

 `Line 72 self.url_template`

Was this change implemented? Or what are some other options? 
Could I fork this repo, and import the Zenpy class manually?

Thanks mate

**Comment by allan-simon** [comment]
thanks a lot for the patch, now that I tink about it , it will not handle the case where you want to have your zendesk mock on "http://localhost:8080" , but I guess I can cover this special case by directly overriding _url_template like pointed out by @naomatheus

**Comment by facetoe** [comment]
Yep should work fine. Just be aware of the edge case here - https://github.com/facetoe/zenpy/commit/da57270939c9cd904562bb59266d70e2ef013f22#diff-56fa6ddca735d969aa726d73ea821dd3R49.

**Comment by allan-simon** [comment]
hmmm also if I  remember correctly the BaseAPI is not directly visible but is hidden at several place in the client right ? i.e it's not as straightforward as doing 

```
my_client = Zenpy()
my_client._url_template
```

right ?

**Comment by facetoe** [comment]
Actually looking at the code `_url_template` isn't even used anywhere, so that aint gonna work for you. 

I guess would need to allow overriding the check that prevents calling Zendesk api without a subdomain, and then you could just set the domain to localhost and it should work

**Comment by allan-simon** [comment]
https://github.com/allan-simon/http-zendesk-mock/ I've tested my change against this , with zenpy , it works great \o/

**Comment by facetoe** [comment]
That project looks really cool @allan-simon!

**Comment by facetoe** [comment]
Solved in https://github.com/facetoe/zenpy/pull/406
