### ISSUE TITLE
Creating and/or assigning tickets to groups

### ISSUE THREAD

**Issue by b3Nd2** [facetoe/zenpy#392]
Currently creating a number of tickets for a number of end_users, but the new tickets are in need of being assigned to an existing group in Zendesk.

I am guessing the code is wrong, but here is what I have used and am unable to get it to assign to a specific group:

`zenpy_client.tickets.create(
Ticket(
subject="Equipment Lease renewal",
requester_id=userId,
group_id=groupId,
comment=Comment(
body="""
Records show this account has a leased device.
Use the standard macro and verify the lease and contact the customer.
""", public=False)
)
)`

I combed through the readme along with the other documentation but I was not able to find anything in regards to assigning newly created tickets to a group.

**Comment by ypperlig** [comment]
Passing group_id is correct, but it needs to be the id of the group within Zendesk.
If the id is correct, and the group is not correct after creation, a trigger in your Zendesk instance is probably routing it as well.

**Comment by b3Nd2** [comment]
That is what I thought. I used curl to grab the ID from Zendesk and put in the script but when I add-in group_id the ticket doesnt generate. When I remove group_id from the code it generates the ticket but doesnt assign it to the group.

**Comment by b3Nd2** [comment]
It looks like if you do not include a status of the ticket when creating it AND assigning it to a group the ticket will not be created. Once I added the status type, it assigned it to a group. Interesting that not assigning the ticket doesnt require a status when creating a ticket without a group id.
