### ISSUE TITLE
Can we add support for create_or_update User?

### ISSUE THREAD

**Issue by mattKaczorowski** [facetoe/zenpy#40]
https://developer.zendesk.com/rest_api/docs/core/users#create-or-update-user

If the client supports this, please forgive my ignorance.

**Comment by facetoe** [comment]
This is pretty cool, is it a new feature? I don't remember seeing it when I was writing the user api part. Yes it looks easy to implement, I'll try to get to it this weekend.

**Comment by rishi-freshbooks** [comment]
This would be awesome! Would help reduce the number of API requests :smile:

**Comment by facetoe** [comment]
All done, let me know if you guys have any issues with the new method.
