### ISSUE TITLE
Add functionality to pull all custom_fields via API

### ISSUE THREAD

**Issue by sandinak** [facetoe/zenpy#401]
Right now there are CRUD options for ticket_fields ( which include custom fields ) but no GET option to pull the dump of all existing custom_fields for a user+domain account.  This would allow library users to craft custom_field input via text names rather than having to store a structure defining the names and field_id numbers.  

The URL is: https://{domain}.zendesk.com/api/v2/ticket_fields.json  

which should be accessible after authentication.  My use case is a zendesk ansible module I am about to commit back to ansible.

**Comment by ypperlig** [comment]
This is already possible with `client.ticket_fields()`.
