### ISSUE TITLE
Is it time to cut a new release?

### ISSUE THREAD

**Issue by mattKaczorowski** [facetoe/zenpy#41]
Hi facetoe,

Thank you for implementing my request with issue #36. I am hoping to use the latest changes in production very soon. Is the current state of master ready for version 1.0.3? :smile:

**Comment by facetoe** [comment]
Sure @mattKaczorowski, not a problem. How about I implement #40 and then create the release?

**Comment by mattKaczorowski** [comment]
Sounds good to me! Thanks for the quick response :+1:

**Comment by rishi-freshbooks** [comment]
@facetoe Hey! Do you mind creating a release before implementing https://github.com/facetoe/zenpy/issues/40? It will save us the trouble of using your latest work https://github.com/facetoe/zenpy/commit/e824deb0d04864034163d9c7417537709f62c97b

**Comment by mattKaczorowski** [comment]
@facetoe #40 is not a super high priority at the moment, it could wait until 1.0.4. I would not mind if you went ahead and satisfied @rishi-freshbooks request.

**Comment by facetoe** [comment]
Sure, not a problem, I've created 1.0.3.

**Comment by mattKaczorowski** [comment]
:clap:

**Comment by facetoe** [comment]
:)

**Comment by rishi-freshbooks** [comment]
Thank you so much!

**Comment by facetoe** [comment]
No worries!
