### ISSUE TITLE
assignee not working in search calls for list of assignee Id values

### ISSUE THREAD

**Issue by netllama** [facetoe/zenpy#410]
It doesn't seem possible to craft a ticket search that specifies a list of assignee Id values.  For example, this works as expected (returns greater than zero tickets):

`tickets = api.search(type='ticket', status='pending', assignee=171)`

However, this returns zero tickets (the only change is to make the assignee field a list, so that I could specify multiple assignee Id values):

`tickets = api.search(type='ticket', status='pending', assignee=[171])`

Is there a way to specify multiple assignee Id values in a single search?

**Comment by jwalterclark** [comment]
You currently two options:

1. Fallback to using the `query` argument

`api.search(query='assignee:123 assignee:456', type='ticket', status='pending')`

2. Reference assignee's by something other than their ID number (name or email).

`api.search(type='ticket', status='pending', assignee=["user1@domain.com", "user2@domain.com"])`

`api.search(type='ticket', status='pending', assignee=["John Doe", "Mary Smith"])`


Currently only the `ids` argument supports a list of integers.
https://github.com/facetoe/zenpy/blob/8f0faf293364db0d6b1103adc28d945be0163f69/zenpy/lib/endpoint.py#L271

Any other lists that are not explicitly supported or formatted with enclosing double-quotes.
https://github.com/facetoe/zenpy/blob/8f0faf293364db0d6b1103adc28d945be0163f69/zenpy/lib/endpoint.py#L320

**Comment by netllama** [comment]
Thanks, I can confirm that searching with a list of assignee email addresses does work.
