### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by lalfaro1704** [facetoe/zenpy#412]
Hi @facetoe i understand that the zendesk api returns the first 1000 records.
```
response = client.tickets()
print(len(response))
>>> 1756
```
How could i access the next page using paginator?

**Comment by lalfaro1704** [comment]
I mean, the following 1000 records...

**Comment by lalfaro1704** [comment]
![image](https://user-images.githubusercontent.com/34684622/77962841-bb47a000-72b2-11ea-8bc5-b0e9209ab8a1.png)
This is not true, you can't split a value greather than 1000.

With `tickets = results[1900:2000:100]`. Raise the following error:
`This search has resulted in more results than zendesk allows. We got what we could.`

**Comment by jwalterclark** [comment]
This indicates that your Zendesk instance only has 1756 tickets.

> ```
> print(len(response))
> >>> 1756
> ```

You're trying to retrieve the 1900th through the 2000th ticket in your Zendesk instance (not to be confused with ticket ID 1900 through ticket ID 2000). You only have 1756 tickets so the maximum you can slice would be `results[:1756]`.

> With `tickets = results[1900:2000:100]`. Raise the following error:
> `This search has resulted in more results than zendesk allows. We got what we could.`

**Comment by joejohn05** [comment]
@facetoe I have been trying to understand how the pagination works in zenpy .Can you help me on this . 

    response = zenpy_client.tickets()
    print(len(response))
    33324

How do I slice it for this value ? Please help me on this .

**Comment by McCabeOura** [comment]
How were you able to accomplish this?
