### ISSUE TITLE
api.tickets.comments() calls periodically failing with ReadOnlyRecord error

### ISSUE THREAD

**Issue by netllama** [facetoe/zenpy#415]
In the past few weeks, I've started to see `api.tickets.comments()` calls occasionally failing with ReadOnlyRecord errors.  The ticket is different every time the failure occurs, and the failure only seems to happen once for any given ticket Id, before it works again on the next attempt (an hour later).  The traceback for the failure is always like this:
```
Traceback (most recent call last):
  File "/apps/titusjob/lib/python3.7/site-packages/cdnopslib/partnercomms.py", line 552, in get_zd_ticket_comments
    comments = api.tickets.comments(ticket_id)
  File "/apps/titusjob/lib/python3.7/site-packages/zenpy/lib/util.py", line 110, in inner
    return func(*new_args, **new_kwargs)
  File "/apps/titusjob/lib/python3.7/site-packages/zenpy/lib/api.py", line 1103, in comments
    include_inline_images=repr(include_inline_images).lower())
  File "/apps/titusjob/lib/python3.7/site-packages/zenpy/lib/api.py", line 274, in _query_zendesk
    return self._get(url=self._build_url(endpoint(*endpoint_args, **endpoint_kwargs)))
  File "/apps/titusjob/lib/python3.7/site-packages/zenpy/lib/api.py", line 129, in _get
    response = self._call_api(self.session.get, url, timeout=self.timeout, **kwargs)
  File "/apps/titusjob/lib/python3.7/site-packages/zenpy/lib/api.py", line 166, in _call_api
    self._check_response(response)
  File "/apps/titusjob/lib/python3.7/site-packages/zenpy/lib/api.py", line 307, in _check_response
    raise APIException(json.dumps(_json), response=response)
zenpy.lib.exception.APIException: {"error": "ReadOnlyRecord", "description": "Requested record cannot be altered"}
```

What is rather puzzling here is why a call that should be read-only is somehow triggering an error from the API about altering a record.  I'm guessing that something is intermittently broken on Zendesk's end (maybe some weird maintenance, or an actual API bug).  However, since this failure is ocurring literally for less than 1% of these API calls, its been a challenege to find a way to reproduce it to debug further.  

I was hoping to get zenpy to return more detailed information whenever this fails, but I'm struggling to find a means of accomplishing that.  Ideally I'd like to see the actual http response code, and the actual call (payload plus endpoint) that resulted in the failure.  Is there some way to coax that from zenpy only when there is an APIException event?

**Comment by rpaterson** [comment]
See other people complaining about the same thing, across several different APIs, and some of them calling using a PHP lib: https://develop.zendesk.com/hc/en-us/community/posts/360044009813-GET-request-ReadOnlyRecord-Requested-record-cannot-be-altered-

**Comment by facetoe** [comment]
This is unfortunately not something that can be handled in Zenpy as it seems to be an issue with the Zendesk API itself.

> I was hoping to get zenpy to return more detailed information whenever this fails, but I'm struggling to find a means of accomplishing that. Ideally I'd like to see the actual http response code, and the actual call (payload plus endpoint) that resulted in the failure

Yes this should be possible by catching the APIException as it has holds the requests response object (which also has a reference to the request). Something like:

```python
try:
    somecall
except APIException as e:
    print(e.response)
```
