### ISSUE TITLE
View the entire ticket container/object

### ISSUE THREAD

**Issue by xd3262nd** [facetoe/zenpy#417]
Hello, 

I am trying to figure out how the ticket objects look like, and not sure how to view all the attributes that are inside the ticket object via this library. For example, I want to view all the descriptions in the ticket and potentially grab a few attributes from the ticket and append to a df. Please help me out thank you.

**Comment by facetoe** [comment]
You can view the contents of the ticket easily by printing it as JSON, eg:

```python
print(ticket.to_json())
```
