### ISSUE TITLE
Problems with tickets_events

### ISSUE THREAD

**Issue by AgentBlond** [facetoe/zenpy#419]
I am doing this to extract some info from the response I get.
I have a problem with this line:  result.append(metric.timestamp) - I want to get the timestamp information from the response. but I seems to have a problem with it being called "timestamp".

results = []
for metric in zenpy_client.tickets.events(start_time = max_up):
    result = []
    result.append(metric.id)
    result.append(metric.ticket_id)
    result.append(metric.timestamp)
    result.append(metric.updater_id)
    result.append(metric.via)
    for x in metric.child_events:
        for k,v in x.items():
            if k == 'status':
                results.append(v)

    uploaded_at = datetime.now()
    result.append(uploaded_at)
    results.append(result)

I get the following error message:
"Parser must be a string or character stream, not int"

Can you please help me to fix this issue?
I am using the latest version of the package.

**Comment by facetoe** [comment]
Hmm sounds like a bug, will have a look when I get the chance.

**Comment by AgentBlond** [comment]
Thanks - I really need this for a report and with the package it is much easier for than doing it other ways.
