### ISSUE TITLE
Custom Ticket Field Updates Fail Silently

### ISSUE THREAD

**Issue by mike-schiller** [facetoe/zenpy#420]
The following code is a snippet from a helper class to update zendesk tickets using zenpy. I have a dictionary within the class to map field names to IDs:

```
    def set_ticket_field(self, field_name, value):
        for f in self._ticket.custom_fields:
            fid = self._custom_ticket_field_name_to_id[field_name]
            if f["id"] == fid:
                f["value"] = value
                return
```

When I subsequently call tickets.update() providing a valid custom field option for the value, the ticket updates properly in zendesk. However, if I supply a value that is not a valid custom field option and call tickets.update(), the update silently fails. Additionally, the audit returned by the call to tickets.update() is for an older update of the ticket, not the one that silently fails.

I'm using python 2.8.2 and zenpy 2.0.19.

**Comment by facetoe** [comment]
Are you able to reproduce this with `curl`? Zenpy itself doesn't do any validation of the data passed to the Zendesk API.
