### ISSUE TITLE
Error on a Date Custom Field

### ISSUE THREAD

**Issue by luxcem** [facetoe/zenpy#425]
I try to create a ticket with a Date Custom Field but the api always respond
`zenpy.lib.exception.APIException: {"error": "RecordInvalid", "description": "Record validation errors", "details": {"base": [{"description": "Date Field is not valid", "error": "InvalidValue", "ticket_field_id": 111111, "ticket_field_type": "FieldDate"}]}}`

I try to use `datetime.datetime.now()`, `2020-05-10`, `datetime.datetime.now().isoformat()` nothing works.

**Comment by facetoe** [comment]
I was able to create a ticket with custom date field as follows:

```python
zenpy_client.tickets.create(Ticket(
    subject="testdate", 
    description="testdate",
    custom_fields=[CustomField(id=360031823372, value="2020-01-02")])
)
```
