### ISSUE TITLE
after_url/cursor with Ticket Audits always points to records from today?

### ISSUE THREAD

**Issue by ldacey** [facetoe/zenpy#431]
I am trying to download historical Ticket Audit data. Ideally, this would be an incremental process where I would store the after_cursor and use it as my cursor during the next scheduled download process.

I listed all cursors and selected one back in February which is where I want to start my data archive from. If I print the audits from this cursor, I do see some February records. If I reverse the ticket_audits (using the before_url), I keep going back in time which is correct.

There seems to be an issue specifically with the after_url/after_cursor. It seems to always point to today.

```
audit_generator = zenpy_client.tickets.audits(cursor='fDE1ODA1NzIzNjcuMHx8MTAyMDY0NjQ3MDAxNA==', limit=5)
for audit in audit_generator:
    print(audit.created.date(), audit.created.time())

```

Although I limit 5 records, I see 10 results. Note that there is always data from today.
```
2020-02-01 15:51:42
2020-02-01 15:50:27
2020-02-01 15:49:50
2020-02-01 15:49:49
2020-02-01 15:49:26
2020-05-21 20:30:02
2020-05-21 20:29:51
2020-05-21 20:27:09
2020-05-21 20:26:01
2020-05-21 20:25:53
```

If I print the after_cursor:

`print(audit_generator.after_cursor)`

`MTU4MDU3MjMwMi4wfHwxMDIwNDM4MTA0MDUzfA==`

```
for audit in audit_generator:
    print(audit.created.date(), audit.created.time())
```

I return records from today. My cursor should be pointing to a record on 02/01 though...

```
2020-05-21 20:34:29
2020-05-21 20:33:58
2020-05-21 20:33:21
2020-05-21 20:33:20
2020-05-21 20:30:02
```

I tried to test this with the requests library as well manually. Am I doing something incorrectly?

**Comment by facetoe** [comment]
Did you get the same result when testing via requests library? As far as I can tell Zendesk is returning an "after_url" that points to records from today for some reason instead of returning None when the limit has been reached.

**Comment by ldacey** [comment]
`audits = requests.get(url, params={'cursor': 'fDE1ODA0NTc4NzcuMHx8MTAxODk5Njk5Mzk3Mw=='}, auth=HTTPBasicAuth(user, skey), headers=headers).json()`

If I check the before and after cursor, I return the following:

`Before cursor: fDE1ODAxMDg2MzUuMHx8MTAxNDAyOTczOTM3NA== After cursor: MTU4MDQ1Nzg3NS4wfHwxMDE4OTk2OTYwNTUzfA==`

If I check the minimum date in the cursor I chose originally, it is: `'2020-01-27T07:03:55Z'`

I would expect the after_cursor to include values around that same date so I could incrementally catch up, but this doesn't work:

`audits = requests.get(url, params={'cursor': 'MTU4MDQ1Nzg3NS4wfHwxMDE4OTk2OTYwNTUzfA=='}, auth=HTTPBasicAuth('jeffrey.vonhendy@sutherlandglobal.com/token', 'VksrQ2h4wUYCEB1qbQJuNgTGCvwDWDExgO4Ao9dN'), headers=headers).json()`

The min `created_at` is now in June: `'2020-06-02T11:02:53Z'`

`Before cursor: fDE1OTEwOTU3NzMuMHx8MTE2ODczNzUwMjgzNA== After cursor: MTU5MTExNzgwMC4wfHwxMTY5NTA3MTc5NDUzfA==`

If I use the new `before_cursor`, my date is also in June. It completely shifts the results to the present time which is just undesired.


It seems like this is **not** a zenpy specific issue. Based on your understanding, does this seem like a Zendesk API bug to you - if so, is there anyone we can reach out to?

I simply just want to download data (maybe 10,000 records at a time), save the `after_cursor`, and then use that as the cursor for the next download in order to incrementally retrieve all changes.

**Comment by facetoe** [comment]
Yes this seems like a Zendesk big to me, it might be worth reaching out to their support. Your use case seems exactly what this sort of cursor based pagination is designed for.

**Comment by ldacey** [comment]
FYI - Zendesk Support informed me that the after_cursor will always point to the most recent ticket. We cannot walk backwards and forwards through the ticket audits it seems - we can only go backwards. It makes incrementally pulling new/changed audits more difficult imo.

> In the ticket audits, the after_cursor always points to the last ticket. This is how it was built.
> 
> However, this could be done in a different manner if I am using the before_cursor where I treat the top result as the latest result and I am back-tracking.
