### ISSUE TITLE
Unable to retrieve ticket metrics for a specific ticket by ticket_id

### ISSUE THREAD

**Issue by ScientiaDavid** [facetoe/zenpy#437]
Hi,

Firstly, thank you for the great work on zenpy, it's amazing :)

I have a list of tickets (retrieved from the search endpoint) which I would like to gather some additional ticket metrics for. 

I can successfully use ticket_metrics() to retrieve all metrics with the following:
`for t in (aZenpyClient.ticket_metrics()):` that you've mentioned elsewhere, but I'm unsure how to access the data within this. I've tried `t.id` or `t.ticket_id` ( and also `t.ticket_metrics.id` or `t.ticket_metrics.ticket_id` as I thought these might work) would have worked but I've had no luck. I was hoping to create a dictionary with the key's as `t.ticket_id` and the values as `t.id`. So I would have a link stored between the `ticket_id` and the metrics `id` from this separate endpoint.

Next, I was going to use the dictionary as a reference between the `ticket_id` and metric `id` values. I know I need to use the metric `id` value (rather than `ticket_id`) to retrieve metrics for an individual ticket with `aTicketMetric = (aZenpyClient.tickets.metrics(id=aMetricId))`. Then I would append the these extra metrics I'd like to the current information I have for a particular ticket. It's a shame `aTicketMetric = (aZenpyClient.tickets.metrics(id=aMetricId))` won't accept a `ticket_id`, that would have simplified the solution.

I know this method is inefficient but I don't have a large amount of tickets (approx. 300-400) in total. I couldn't think of a better way to get the metric `id` value needed for `aZenpyClient.tickets.metrics(id=aMetricId)`.

Could you provide an additional example for `for t in (aZenpyClient.ticket_metrics()):` where any of the metrics are being used?

Best regards,
David

**Comment by facetoe** [comment]
You can use the following to build a dict of ticket_id -> ticket_metric:

```python
ticket_metrics = {}
for ticket in zenpy_client.search(type="ticket", query="some query"):
    ticket_metric = zenpy_client.tickets.metrics(ticket=ticket)
    ticket_metrics[ticket.id] = ticket_metric
print(ticket_metrics)
```

You can additionally view the attributes of an object as JSON to see what is available: 

```
print(ticket.to_json())
```

Hope this helps.
