### ISSUE TITLE
List tickets by organization id

### ISSUE THREAD

**Issue by ruchitrami** [facetoe/zenpy#439]
I am trying to make this organizations/{organization_id}/tickets call using zenpy but not able to find the method in the documentation. Is it possible?

I am trying to list down tickets by organization for my interface. Search endpoint has certain delay in showing new tickets.

**Comment by facetoe** [comment]
Hi, 

The following should work:

```python
for ticket in zenpy_client.tickets.organizations(organization=361096284052):
    print(ticket)
```
