### ISSUE TITLE
Issue creating a new 'User' object

### ISSUE THREAD

**Issue by plockxng** [facetoe/zenpy#44]
Hi,

First and foremost, thanks for this zendesk api wrapper. 

After reading through the zenpy documentation though, I am having trouble creating new users.

After logging in with my credentials:
```python
zenpy = zenpy.Zenpy(**creds)
```

I can make zenpy queries on zenpy.users (etc.), but when I try to create a new user:
```python
user = User(name='Jim', email='jim@jim.com')
```
I get the following error message:
```
Traceback (most recent call last):
  ...
    user = User(name='Jim', email='jim@jim.com')
NameError: name 'User' is not defined
```
This was the example given in the [documentation](https://facetoe.com.au/zenpy/docs/api_objects.html#instantiating-objects). 

I am hesitant because I'm afraid it is an issue on my end (am I missing something?), but would like to see if anyone else has this issue since I've exhausted a lot of different options.

Thanks,
Preston

**Comment by facetoe** [comment]
Hi Preston, 

The docs are missing some crucial information, so thanks for bringing this to my attention! You need to import the `User` object before you can use it. Try the following:

```python
from zenpy.lib.api_objects import User
user = User(name='Jim', email='jim@jim.com')
```

I'll update the docs and add the location of all the API objects (they are all in `zenpy.lib.api_objects`).

**Comment by plockxng** [comment]
Hi facetoe,

Ah now I see it! Thanks for the quick response.

Best,
Preston
