### ISSUE TITLE
How to use SearchAPI to find tickets according to their CustomField id & value?

### ISSUE THREAD

**Issue by davidbernat** [facetoe/zenpy#444]
No idea how to do this. 

```
my_field_number = 1010101001010
client = Zenpy(**cfg.zendesk_credentials)
client.tickets.create(Ticket(subject="My new ticket",
                             description="this is a long description",
                             custom_fields=[CustomField(id=my_field_number, value="my-favorite-id")]))

for ticket in client.search('', type='ticket' ??????????????????):
    print(ticket.to_dict())
 ```

**Comment by facetoe** [comment]
This might help - https://support.zendesk.com/hc/en-us/articles/203663206-Searching-tickets?page=2#topic_wly_fev_uc

**Comment by netllama** [comment]
I don't think that helps.  The article explains how to search for a specific value in custom ticket fields by using the fieldvalue keyword.  It doesn't explain how to search a specific custom field (id) for a specific value.  

Is this not possible with zenpy?
