### ISSUE TITLE
Attachment at ticket creation time.

### ISSUE THREAD

**Issue by Benoss** [facetoe/zenpy#445]
With direct mail it looks like the attachment is attached to the ticket, with Zenpy it seems that I can only attach files to comment not the ticket itself. Is this a limitation of the API or Zenpy?

Feature request: Add uploads part of Ticket() object and accepted by zenpy_client.tickets.create(ticket)

**Comment by Benoss** [comment]
Awesome, I did not realise that you could do it this way.
You can't attach it to the ticket itself, but the first comment is a bit special because the body of the first comment becomes the description of the ticket. That's why I was confused.

**Comment by facetoe** [comment]
Yep, agreed it is a bit confusing.
