### ISSUE TITLE
Add ability to add custom "User-Agent" header value

### ISSUE THREAD

**Issue by iamshwin** [facetoe/zenpy#446]
We currently use Zenpy for a few of our services to update Zendesk tickets, and we'd like to be able to distinguish between which of them is updating a ticket. 

As such, it would be a nice feature for us to be able to specify a custom "User-Agent" in the request header.

What do you think about this?

**Comment by facetoe** [comment]
You can now pass a requests session object with a custom User-Agent header.

**Comment by iamshwin** [comment]
Thanks for this!

**Comment by iamshwin** [comment]
Hi @facetoe - thanks for implementing this. Are you planning to release a new version (that includes this code change) to PyPI anytime soon?

**Comment by facetoe** [comment]
No worries, just pushed a new release - https://github.com/facetoe/zenpy/releases/tag/2.0.22.
