### ISSUE TITLE
update users using for loop

### ISSUE THREAD

**Issue by ingridxx** [facetoe/zenpy#449]
Hi, I want to update a custom user field for a list of users which I loaded from CSV, identified by their email. I was able to update a single user, but when I try to read the data in a loop, it gives me a `StopIteration` error. Any idea how I could fix this? Thanks a lot!

```with open('users.csv') as csv_file:
    data = reader(csv_file)
    header = next(data)
    if header is not None:
        for row in data:
            user = zenpy_client.search(type='user', email=row[0]).next() # error on this line
            user.user_fields.update(dict(custom_field=True))
            zenpy_client.users.update(user)

**Comment by facetoe** [comment]
`.next()` raises `StopIteration` when there are no more items - https://docs.python.org/3/library/stdtypes.html#iterator.__next__. In your case it is likely that the search for this particular user returned nothing.
