### ISSUE TITLE
tickets incremental export infinite loop

### ISSUE THREAD

**Issue by nathanprat** [facetoe/zenpy#451]
Hello,

I have an issue when using the Tickets Incremental Exports API: zenpy is calling the same URL over-and-over, and ends up rate-limited.  
After some time my corporate proxy kills the connection, and therefore the job fails, but that is not the issue.

From what I could gather by debugging the URLs called and the payloads received, zenpy is:

1. calling _https://REDACTED.zendesk.com/api/v2/incremental/tickets.json?start_time=1600164837_
response is a lot of tickets:
```json
{
    "tickets": [...],
    "count": 267,
    "end_of_stream": true,
    "next_page": "https://REDACTED.zendesk.com/api/v2/incremental/tickets.json?start_time=1602587180",
    "end_time": 1602587180
}
``` 

2. but instead of stopping there because `end_of_stream=True`, it is calling _https://REDACTED.zendesk.com/api/v2/incremental/tickets.json?start_time=1602587180_ which gives:

```json
{
    "tickets": [
        {
            "url": "https://REDACTED.zendesk.com/api/v2/tickets/2081.json",
            "id": 2081,            
            ...
            "created_at": "2020-10-12T08:21:12Z",
            "updated_at": "2020-10-13T11:06:20Z",
            "generated_timestamp": 1602587180
        },
        {
            "url": "https://REDACTED.zendesk.com/api/v2/tickets/2085.json",
            "id": 2085,
            ...
            "created_at": "2020-10-12T10:09:14Z",
            "updated_at": "2020-10-13T11:06:20Z",
            "generated_timestamp": 1602587180
        },
        {
            "url": "https://REDACTED.zendesk.com/api/v2/tickets/2077.json",
            "id": 2077,
            ...
            "created_at": "2020-10-12T07:24:22Z",
            "updated_at": "2020-10-13T11:06:20Z",
            "generated_timestamp": 1602587180
        }
    ],
    "count": 3,
    "end_of_stream": true,
    "next_page": "https://REDACTED.zendesk.com/api/v2/incremental/tickets.json?start_time=1602587180",
    "end_time": 1602587180
}
```

3. back to 2, because it calls the same URL again, and again, and again...

The [zendesk docs](https://developer.zendesk.com/rest_api/docs/support/incremental_export#api-workflow) indeed say 
> In either export method, read the end_of_stream boolean value on each page to determine when the last page of results has been reached. When true, the last page has been reached.

and as you see it is set even on the first call.

Am I missing something or is this a bug?

`zenpy==2.0.22`

**Comment by facetoe** [comment]
Definitely sounds like a bug. Interesting this pops up now, I wonder if they added this at some point.

**Comment by facetoe** [comment]
OK thanks for the report and patch, I'll have a look to fix this one the weekend.

**Comment by facetoe** [comment]
Does this fix it for you - https://github.com/facetoe/zenpy/pull/455?

**Comment by nathanprat** [comment]
Yup, that seems to work just fine. Thanks!

**Comment by kolaworld** [comment]
@facetoe, thanks for the fix. Looks like #455 has not been merged into master yet? Any timeline to do so?
