### ISSUE TITLE
trying to update custom_field_options

### ISSUE THREAD

**Issue by johnchowdhari** [facetoe/zenpy#459]
Hi, 

i'm trying to achieve this [https://developer.zendesk.com/rest_api/docs/support/ticket_fields#updating-drop-down-field-options](url)

while running below line of code getting exception . Is this function have any issue? 

from zenpy.lib.api_objects import TicketField, CustomFieldOption

field_id=<my custom drop-down field id>
field_options=[{"name": "test_new", "value": "test_not_hot"},  {"name": "test_new1", "value": "test_not_hot1"}]

zenpy.ticket_fields.options.create_or_update(TicketField(id=field_id), CustomFieldOption(custom_field_options=field_options)
)

`File "zenpy/lib/util.py", line 111, in inner
    return func(*new_args, **new_kwargs)
  File "zenpy/lib/api.py", line 1465, in create_or_update
    custom_field_option)
  File "zenpy/lib/request.py", line 337, in post
    payload=self.build_payload(custom_field_option))
  File "zenpy/lib/api.py", line 87, in _post
    **kwargs)
  File "zenpy/lib/api.py", line 150, in _call_api
    self._check_response(response)
  File "zenpy/lib/api.py", line 307, in _check_response
    raise APIException(json.dumps(_json), response=response)
zenpy.lib.exception.APIException: {"error": "ParameterMissing", "description": "Parameter name is required"}`

is i'm doing anything wrong ? or calling with wrong paramaters ?

**Comment by johnchowdhari** [comment]
Find correct function

**Comment by tomerbsentinel** [comment]
@johnchowdhari 
What was that function?
I'm at the same spot as you were back days.
