### ISSUE TITLE
SearchEndpoint improper query string generation

### ISSUE THREAD

**Issue by theoschao** [facetoe/zenpy#46]
It seems that the if-elif conditions defined in SearchEndpoint don't properly handle cases when the value is a datetime object OR the value is of list type and key == ids.  In order for those arguments to make it into the final query string, they can't be handled as elif conditions.  They should probably be their own if conditions so that the code can fall through to assessment of the keys, and then modify renamed_kwargs.

**Comment by facetoe** [comment]
Hi @theoschao, thanks for the bug report! Could you provide an example where the `SearchEndpoint` creates an incorrect query string? The code there is a little messy but from your description of the problem I think it should still work as intended as the `value` can only ever be one of those cases at any given iteration of the loop. An example will help clear things up!
