### ISSUE TITLE
Handle TooManyValuesException by making multiple requests?

### ISSUE THREAD

**Issue by mikeroll** [facetoe/zenpy#467]
Recently stumbled upon this when doing a `Zendesk.tickets.update(many_tickets)` where `many_tickets` is larger than 100 items.

Probably more of a feature request than a bug, but I think zenpy is high-level enough to handle this under the hood by chunking the list and making multiple requests, in the same spirit as pagination is handled transparently with generators.

**Comment by facetoe** [comment]
I'm not going to implement this but PRs are welcome.
