### ISSUE TITLE
Add OAuth Support

### ISSUE THREAD

**Issue by facetoe** [facetoe/zenpy#47]
https://developer.zendesk.com/rest_api/docs/core/introduction#oauth-access-token

**Comment by facetoe** [comment]
Need to update docs.

**Comment by mirceaciu** [comment]
great and usefull wrapper, but I have troubles using Oauth for chat. 
I've created a zendesk account and used Zenpy to login with mail and password and was able to create tickets.

I've created Oauth 'client' in zendesk Api settings page, got the secret_key and tried using it inside the previous script with `oauth_token`, but i get the `invalid_token` error.  Am I missing something?

**Comment by facetoe** [comment]
Yep, your normal Zendesk OAuth token won't work for chat. I think I used this page to configure OAuth for chat - https://support.zendesk.com/hc/en-us/articles/115010760808-Generating-a-REST-API-token-for-integrated-Chat-accounts.

**Comment by mirceaciu** [comment]
That article helped. I got a new token manually, hope those steps can be scripted. 
Either way, Zenpy ChatApi works!
