### ISSUE TITLE
Type hints break Python 2 compatibility

### ISSUE THREAD

**Issue by grozen** [facetoe/zenpy#470]
While highly discouraged, some people are still using this fine package with Python 2 (👋🏻 ).
[This recent change](https://github.com/facetoe/zenpy/blob/9a77b323b48124ab210555a1941c0e3e076dae6b/zenpy/lib/util.py#L144) introduced some Python 3 type hints to the codebase, which sadly do not constitute as valid Python 2 syntax.

As far as I can tell this package still officially supports Python 2, though a very valid solution nowadays would be to explicitly drop support.

**Comment by facetoe** [comment]
Thanks for the report, I think I'll just drop the type hints. At some point it might make sense to drop support for python2 in order to use some nice new feature but it's easy enough to keep it for now.

**Comment by facetoe** [comment]
Fixed in cbb9fc3823b10c000c0810beda6ee8746b5bc1fb
