### ISSUE TITLE
Show Ticket Field - is it missing from the api?

### ISSUE THREAD

**Issue by tobenary** [facetoe/zenpy#471]
Hi,
From what I can see, this API is missing from the "ticket_fields" option. (Show Ticket Field)
https://developer.zendesk.com/rest_api/docs/support/ticket_fields#show-ticket-field

This is a mandatory SHOW command to get the actual data to work on the next API call (Show Ticket Field Option)
https://developer.zendesk.com/rest_api/docs/support/ticket_fields#show-ticket-field-option

I tried to do:
zenpy_client.ticket_fields.show, but it doesn't exist.
![image](https://user-images.githubusercontent.com/8009594/108367449-261f0400-7202-11eb-90bf-afba0e5447f4.png)

Am I missing something here?

**Comment by tomerbsentinel** [comment]
The issue resolved by calling the _zenpyclient.ticket_fields(id=242)_ directly OR using the for loop for all.
