### ISSUE TITLE
Error when searching tickets with `via` kwarg

### ISSUE THREAD

**Issue by zenahirsch** [facetoe/zenpy#479]
I am attempting to make a search using the `via` kwarg:

```python
tickets = client.search(query='charged', type='ticket', via='email')
```

I get the following error:

```
zenpy.lib.exception.APIException: {"error": "invalid", "description": "Invalid search: Error filtering on field: via_id"}
```

**Comment by etoulas** [comment]
I've tried multiple things, all fail with the same error.

I'm trying to find ticket matching a particular via.source.to.address.

```python
via = {
    'channel': 'email',
    'source': {
        'to': {
            'address': 'user@domain.tld'
        }
    }
}
tickets = client.search(via=via)
```

```python
from zenpy.lib.api_objects import Via, Source

via = Via(source=Source(to={'address': 'user@domain.tld'}))
tickets = client.search(via=via)
```

@cryptomail How is this supposted to work?

**Comment by cryptomail** [comment]
Well....this is interesting....I first would look up and see how search works on the public documentation and see if we can determine where things are breaking down. https://developer.zendesk.com/documentation/ticketing/using-the-zendesk-api/searching-with-the-zendesk-api/

**Comment by cryptomail** [comment]
Please let me know if you need more assistance. Or...if we can make the documentation better.

**Comment by cryptomail** [comment]
Closing as I've given kwargs that worked for me (with requester email).  Reopen if you need additional support/help.
