### ISSUE TITLE
Add support to list organizations

### ISSUE THREAD

**Issue by swiftace** [facetoe/zenpy#485]
Listing and paging through all organizations as shown in the docs at https://developer.zendesk.com/api-reference/ticketing/organizations/organizations/ needs to be supported please.

**Comment by Moke** [comment]
This library doesn't support it. You'll have to hit the zendesk api directly: https://developer.zendesk.com/api-reference/ticketing/organizations/organization_memberships/

**Comment by cryptomail** [comment]
Seems supported now https://github.com/facetoe/zenpy/blob/124cf002f71cbefd827a30bc7aa306397ee524aa/zenpy/lib/api.py#L1283
