### ISSUE TITLE
Add a comment to a ticket

### ISSUE THREAD

**Issue by ihaveajob** [facetoe/zenpy#49]
I'm trying to facilitate the work of our agents by adding a private comment to each incoming ticket, where we specify a few additional details about the requester, specific to our service. However, I can't figure out if it's possible to create a comment, either public or private, for a given ticket. Is this implemented at all? If not, any chance it will be?

**Comment by facetoe** [comment]
Yes this is implemented, although it's not exactly obvious how to go about it. The following example will create a private comment on the ticket with an id of 2:

```python
ticket = zenpy.tickets(id=2)
ticket.comment = Comment(body="I am a private comment", public=False)
zenpy.tickets.update(ticket)
```
There is a hint that this is possible in the docs regarding object serialization (https://facetoe.com.au/zenpy/docs/api_objects.html#object-serialization) however it's not the best example. I will update the docs using this example as it is a much better one.

**Comment by ihaveajob** [comment]
Much appreciated, thanks for the rapid response!

**Comment by facetoe** [comment]
No worries!

**Comment by mafrul** [comment]
How could i Comment with attachment ?

**Comment by TPolny** [comment]
is it possible to reply with an attachment yet?

**Comment by rtkwlf-hzzz** [comment]
tho it has been very late, but finally find how to add a comment with attachment from Zendesk offical https://developer.zendesk.com/documentation/ticketing/using-the-zendesk-api/adding-ticket-attachments-with-the-api/

you need to create a comment obj firstly : 

`comment = Comment(.....)` 

and then upload attachment and get the token that will be used on comment
```Python
    if attachment_file:
           # attachment_file can be a string obj, or abs filepath of file
            upload_token = self.client.attachments.upload(attachment_file).token
            comment.uploads = upload_token
```

here u go
