### ISSUE TITLE
Support for Webhooks

### ISSUE THREAD

**Issue by haizaar** [facetoe/zenpy#499]
Good day,

With Zendesk targets being [deprecated](https://support.zendesk.com/hc/en-us/articles/4408826284698-Announcing-the-deprecation-of-HTTP-targets-and-conversion-to-webhooks) on Feb 22, 2022, it's vital for this library to support [Webhooks](https://developer.zendesk.com/api-reference/event-connectors/webhooks/webhooks/) API that superseds HTTP targets.

**Comment by haizaar** [comment]
@facetoe I emailed you a proposal to sponsor development of this feature. Not sure if you are just silently saying "no" or my email s got caught up in your spam bin.

**Comment by casual-lemon** [comment]
I second this feature request, my team is moving to zendesk in the fall and we need support for zenpy using Webhooks API

**Comment by Ptr314** [comment]
@haizaar @casual-lemon made it. It is not released yet to PyPi but here it is commited. https://github.com/facetoe/zenpy#Working-with-webhooks

@facetoe could you please add me as a contributor in PyPi to let me bump a new version and upload it? My nick there is ptr314.

**Comment by akalex** [comment]
@Ptr314 curious when it's going to be released to PyPi?

**Comment by cryptomail** [comment]
@akalex Please confirm working as expected and we'll close.

**Comment by akalex** [comment]
@cryptomail What version of the client should start supporting Webhooks?
I am currently on `2.0.25`, which does not seem to support Webhook. Proof
```
from zenpy.lib.api_objects import Webhook
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ImportError: cannot import name 'Webhook' from 'zenpy.lib.api_objects' (/Users/aomyshev/venvs/ticket_hub/lib/python3.11/site-packages/zenpy/lib/api_objects/__init__.py)

```

**Comment by Ptr314** [comment]
@akalex 2.0.26, but it's not loaded ty PyPi. (27-28-29 have issues) So, please try 2.0.30

**Comment by akalex** [comment]
I tried on 2.0.30. It works. 🥳 
Thank you. We can resolve this issue.

**Comment by cryptomail** [comment]
<3
