### ISSUE TITLE
zenpy_client.users.organizations() returning a Organization object instead a  ResultGenerator

### ISSUE THREAD

**Issue by lowliet64** [facetoe/zenpy#501]
Hello , i'm trying to list all organizando of a user , in docs is showed a example like this

```
for organization in  zenpy_client.users.organizations(user=1916242080765):
        print (organization.name)
```

but when i try to run , a take this error:

```
    for organization in  zenpy_client.users.organizations(user=requester.id):
        TypeError: 'Organization' object is not iterable
```

**Comment by Moke** [comment]
It does not appear at this zendesk api library supports associating a user with multiple organizations.

**Comment by cryptomail** [comment]
Seems fixed, non reproducible, if you pass in a valid user id.
