### ISSUE TITLE
Tickets API getting reduced result set from Zendesk

### ISSUE THREAD

**Issue by ggbavi** [facetoe/zenpy#515]
Hello,

I am using the zenpy_client to fetch all the tickets from Zendesk. When I ran this piece of code a month ago, Zendesk returned around ~35k records, but when I ran the same code yesterday, it fetched only ~8k records. I am not able to understand the reason for this sudden shrink in the dataset. Please help. Thank you in advance.

Here is the piece of code
-----------------------------
    tickets_json = []
    
    tickets_df = pd.DataFrame()

    result_generator = zenpy_client.tickets()
    
    accurate_tickets = [ticket for ticket in result_generator]

    for ticket in accurate_tickets:
            tickets_json.append(ticket.to_dict())

    tickets_df = pd.json_normalize(tickets_json)

**Comment by cryptomail** [comment]
Tickets typically get archived.  Tickets that are archived may not come back from the result set from that API.
https://support.zendesk.com/hc/en-us/articles/4408887617050-About-ticket-archiving
