### ISSUE TITLE
Support for Show Membership API

### ISSUE THREAD

**Issue by kostasb** [facetoe/zenpy#525]
The organization_memberships method currently only supports creating a new membership or deleting a membership by its id.

Not knowing a membership id, I want to:

- retrieve all the organization memberships of a particular user
- check if there is membership with a specific organization
- if there is one, get that membership id and delete that membership

It looks like this would require zenpy to support the [show membership](https://developer.zendesk.com/api-reference/ticketing/organizations/organization_memberships/#show-membership) api.

**Comment by cryptomail** [comment]
org_memberships = zenpy_client.users.organization_memberships(id=my_user_id)
Supported by: https://github.com/facetoe/zenpy/blob/67562c6b0fdc7759c4597d836ab63823616abe8e/zenpy/lib/endpoint.py#L715
That should work.
