### ISSUE TITLE
Search through the articles

### ISSUE THREAD

**Issue by katerinafrid** [facetoe/zenpy#536]
Is it possible to search through the articles? Is there a search API for the help center?

**Comment by ahmedsabriz** [comment]
@katerinafrid while unified API does not seem to be implemented in Zenpy yet, you can use the articles search api. Here is an example to print the search result title:
```
from zenpy import Zenpy
from os import environ
from dotenv import load_dotenv

load_dotenv()

zenpy_client = Zenpy(
    subdomain=environ["SUBDOMAIN"],
    email=environ["EMAIL"],
    token=environ["APITOKEN"],
)
search_query = "help"
articles = zenpy_client.help_center.articles.search(search_query);
for article in articles:
    print(article.title)
```

**Comment by cryptomail** [comment]
Seems reasonable....typed search on specific entity is currently supported.
