### ISSUE TITLE
Get Articles - requires locale

### ISSUE THREAD

**Issue by nitrag** [facetoe/zenpy#538]
```python
help_center = zenpy_client.help_center
categories = help_center.categories()
for category in categories:
    section_data = []
    sections = help_center.categories.sections(category_id=category.id)
    for section in sections:
        articles = help_center.sections.articles(section=section)
```
Throws: 

`zenpy.lib.exception.APIException: {"error": {"title": "Invalid attribute", "message": "You passed an invalid value for the sort_by attribute. The endpoint must specify a locale in order to sort by titles"}}`

**Comment by ahmedsabriz** [comment]
I do not get this error if authenticated as an agent. Locale is required for end users and anonymous users, but it does not seem to be supported in zenpy yet.

**Comment by nitrag** [comment]
@facetoe the PR has been merged. We can close this as soon as we push to PyPi. AFAIK, you're the only one with access to do so.

**Comment by cryptomail** [comment]
Administratively closing this issue on the basis it's been merged and subsequent releases occurred :P
