### ISSUE TITLE
[Question] Does the library support Search Organizations by External ID

### ISSUE THREAD

**Issue by akalex** [facetoe/zenpy#542]
According to [documentation](https://developer.zendesk.com/api-reference/ticketing/organizations/organizations/#search-organizations-by-external-id), Zendesk API supports the organization's search by external ID. I did find the corresponding method as part of the object `Organizations`. Therefore, is this functionality supported? I would greatly appreciate any recommendations on alternative ways.

**Comment by ahmedsabriz** [comment]
Hi @akalex. I just tested the organizations.external method and it gave me an error. I didn't spend any time to troubleshoot it since this alternative has always worked for me:
```
from zenpy import Zenpy
from os import environ
from dotenv import load_dotenv
from zenpy.lib.api_objects import Organization

load_dotenv()


zenpy_client = Zenpy(
    subdomain=environ["SUBDOMAIN"],
    email=environ["EMAIL"],
    token=environ["APITOKEN"]
)

# Create a test org (external id will transform into a string even if you enter an integer)
draft_new_org = Organization(external_id=123456, name="Test Organization")
new_org = zenpy_client.organizations.create(draft_new_org)
print("created org:", new_org.name, "with id", new_org.id)

# Search for the test org by external_id (must be a string)
search_results = zenpy_client.organizations(external_id="123456")
for org in search_results:
    print("Found org:", org.name, "with id", org.id)
if not len(search_results):
    print("No results.")
```

Let me know if you have any questions

**Comment by akalex** [comment]
Thanks @ahmedsabriz for the prompt response, yes this works for me. Closing this issue.
