### ISSUE TITLE
Ticket update returning weird error from api_objects

### ISSUE THREAD

**Issue by opkorz** [facetoe/zenpy#56]
So I'm trying out zenpy for editing tickets but when I'm trying update it I receive this weird error:

`>>> ticket = zend.tickets.get_ticket(38884)`
`>>> ticket.tags.append(u'wrapper_testing')`
`>>> zend.tickets.update(ticket)`
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`  File "/home/xander-lubuntu/.virtualenvs/sabackend/local/lib/python2.7/site-packages/zenpy/lib/api_objects.py", line 25, in __repr__`
`    return super().__str__()`
`TypeError: super() takes at least 1 argument (0 given)`

It updates the ticket yes, but this is something I would not want to receive or see.
Can anyone shine a light on this thing?

**Comment by facetoe** [comment]
Hi @opkorz, 

This error is a bug, and I'll push a fix tonight, however I should point out that you are retrieving the ticket in a way that I did not intend. The correct way to retrieve a ticket is:

```python
ticket  = zenpy.tickets(id=38884)
```
The `get_ticket` method is actually used internally by other objects that have a ticket property and is not meant to be used directly. I can see that it's presence in the ticket api is confusing to users so I might make it a private method to make it more clear it is part of Zenpy's internals.

Let me know if you have any more problems or questions!
