### ISSUE TITLE
users.incremental() doesn't behave like tickets.incremental()

### ISSUE THREAD

**Issue by kovaacs** [facetoe/zenpy#572]
According to the [Zendesk docs](https://developer.zendesk.com/documentation/ticketing/managing-tickets/using-the-incremental-export-api/#cursor-based-incremental-exports) the `tickets` and `users` incremental endpoints should work the same way, either taking a `cursor` or a `start_time` value. In `zenpy` this is true for `tickets`, but not for `users`.

```
# works
for _ in zenpy_client.tickets.incremental(cursor="x"):
    pass

# doesn't work, but should
for _ in zenpy_client.users.incremental(cursor="x"):
    pass
```

I would expect them to work identically.

**Comment by cryptomail** [comment]
I'll have a squizz at it

**Comment by cryptomail** [comment]
That being said, if you've got **any** bandwidth, as the saying goes "patches welcome :P"

**Comment by kovaacs** [comment]
This PR seems to fix it: https://github.com/facetoe/zenpy/pull/576

**Comment by cryptomail** [comment]
Please have a look at https://github.com/facetoe/zenpy/pull/577
I've taken your work and added tests and a few other minor adjustments.

**Comment by kovaacs** [comment]
Thanks, I'll take a look tomorrow as soon as I get the chance!

**Comment by kovaacs** [comment]
It seems to be working as expected, but I cannot say anything conclusive as my integration is still in its infancy.

**Comment by cryptomail** [comment]
@kovaacs OK, doing administrative merge tomorrow.  I feel these are definitely positive changes and I added the tests.
