### ISSUE TITLE
Retrying on DatabaseDeadlock and DatabaseConflict errors returned by Zendesk

### ISSUE THREAD

**Issue by rishi-freshbooks** [facetoe/zenpy#58]
We sporadically see these errors in our logs:
```
APIException: {"description": "Database collision", "error": "DatabaseConflict"}
```
and
```
APIException: {"description": "Database deadlock found; please retry your transaction", "error": "DatabaseDeadlock"}
```

According to the [docs](https://developer.zendesk.com/rest_api/docs/core/introduction#500-range), the Zendesk API:
>A 503 response with a Retry-After header indicates a database timeout or deadlock. You can retry your request after the number of seconds specified in the Retry-After header.

Do you think zenpy can acknowledge this header and retry the request before raising APIException?

**Comment by facetoe** [comment]
Interesting! Zenpy *should* already handle the Retry-After header for get requests (https://github.com/facetoe/zenpy/blob/master/zenpy/lib/api.py#L53), however it doesn't yet for Post and Put. It is possible that the action being peformed is using one of these methods. I'll have a look at fixing this for Post and Put and we can see if the error dissapears.

**Comment by rishi-freshbooks** [comment]
In our use-case, the action being performed is Post and Put.

Thank you!!

**Comment by facetoe** [comment]
I've made the fix and pushed a new version. Let me know if you are still seeing the Exceptions in the logs after updating.

**Comment by rishi-freshbooks** [comment]
Thanks! Saw this today in our logs:
```
APIException: {"description": "Database deadlock found; please retry your transaction", "error": "DatabaseDeadlock"}
```
Tough to say if the transaction was retried.

**Comment by facetoe** [comment]
Hmm, that's too bad. I think it is likely that this error did not include the 503 header and as such wasn't retried however it's hard to say without additional logging. I'll patch the code tonight to include a little more information in the error message (HTTP error code, traceback) to help get to the bottom of this.

**Comment by rishi-freshbooks** [comment]
Thanks! Would you mind also logging the "X-Zendesk-Request-Id" header (https://developer.zendesk.com/rest_api/docs/core/introduction#500-range)

Apparently:
>>>If submitting a ticket to Support, provide the X-Zendesk-Request-Id header included in the HTTP response. This helps the Support team track down the request in the logs more quickly.

which will help us escalate issues to Zendesk.

**Comment by facetoe** [comment]
Sorry I forgot about this issue! Zenpy now logs the error code and headers for responses that are not in the 200 range. Are you able to increase the logging level to debug and run the code from master?

**Comment by rishi-freshbooks** [comment]
Unfortunately we cannot run code from master in production.
We can increase logging level to debug.
Thanks!

**Comment by facetoe** [comment]
Ok no problem, I'll push a new version.

**Comment by facetoe** [comment]
All done!

**Comment by rishi-freshbooks** [comment]
Thanks! Will get this to production and let you know how it goes.

**Comment by facetoe** [comment]
Awesome, will be interesting to hear what you find out.

**Comment by rishi-freshbooks** [comment]
The logging worked well! Thanks again 😄

**Comment by facetoe** [comment]
Good to hear! I'll mark this issue as closed but feel free to open it again if you have any more trouble with deadlocks etc.

**Comment by miet182** [comment]
Hey, I got here having the same issue. I'm trying to make PUT requests and sometimes get:

`APIException: {"description": "Database collision", "error": "DatabaseConflict"}`

I'm a little new in this, so don't know how to _increase the logging level to debug_. Is there any way to fix it and implement a retry-after?

Thank you
