### ISSUE TITLE
Add lilnter to Zenpy

### ISSUE THREAD

**Issue by cryptomail** [facetoe/zenpy#583]
@kovaacs keeps showing me bad stuff that likely a linter will outright prevent.

@kovaacs Any suggestions?

**Comment by kovaacs** [comment]
I use a mixture of [pylint](https://github.com/pylint-dev/pylint) and the default PyCharm inspector for normal daily work. I've also looked at [ruff](https://github.com/astral-sh/ruff) and it was pretty good as well.

**Comment by cryptomail** [comment]
Ruff stuff is now in the mix.  Lints in a 3.11 container.  Added make lint as well for local checks.

**Comment by kovaacs** [comment]
Thanks for being so proactive and receptive to input 🙏🏻
