### ISSUE TITLE
Create or Update many users does not work

### ISSUE THREAD

**Issue by akalex** [facetoe/zenpy#586]
Method `UserApi.create_or_update` does not seem to work (the create path). I am getting an error: `zenpy.lib.exception.RecordNotFoundException: {"error": "RecordNotFound", "description": "Not found"}`

Here is the code to reproduce
```
from zenpy import Zenpy
from zenpy.lib.api_objects

client = Zenpy(subdomain="<subdomain>", email="<email>, token="<token>")
user = User(external_id="1966566", email="at_email_1695024721350@domain.com", name="At_test_first1695024721350 At_test_last")
zd_user = client.users.create_or_update(user)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/akalex/venvs/myproject/lib/python3.11/site-packages/zenpy/lib/api.py", line 1103, in create_or_update
    return CRUDRequest(self).post(users, create_or_update=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/akalex/venvs/myproject/lib/python3.11/site-packages/zenpy/lib/request.py", line 81, in post
    return self.api._post(url, payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/akalex/venvs/myproject/lib/python3.11/site-packages/zenpy/lib/api.py", line 119, in _post
    response = self._call_api(self.session.post,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/akalex/venvs/myproject/lib/python3.11/site-packages/zenpy/lib/api.py", line 194, in _call_api
    self._check_response(response)
  File "/Users/akalex/venvs/myproject/lib/python3.11/site-packages/zenpy/lib/api.py", line 346, in _check_response
    raise RecordNotFoundException(json.dumps(_json),
zenpy.lib.exception.RecordNotFoundException: {"error": "RecordNotFound", "description": "Not found"}
```

A version of `zenpy` is `2.0.38`

**Comment by cryptomail** [comment]
looking into it

**Comment by cryptomail** [comment]
Let me get this straight...your use case is that you're specifying an external_id with email and name.
In order to best understand where the failure is, here's a question @akalex have you confirmed that the RAW POST as per the documentation works, and Zenpy does not?

**Comment by cryptomail** [comment]
Also, another question is this: is this going to be a CREATE given your data?  Is this a NEW user that does not exist yet?  I'll read the documentation on the behaviour expected.

**Comment by akalex** [comment]
Hey @cryptomail,
I have not tried the RAW POST, however, I can confirm that it works as expected using `zenpy` version 2.0.30.
The example I use is supposed to create new use as I do not provide User.id

**Comment by cryptomail** [comment]
https://developer.zendesk.com/api-reference/ticketing/users/users/#create-or-update-user
Here is the documentation.
```
Create Or Update User
POST /api/v2/users/create_or_update
Creates a user if the user does not already exist, or updates an existing user identified by e-mail address or external ID.
```

**Comment by cryptomail** [comment]
OK I'll confirm this and see where things have gotten off track.

**Comment by cryptomail** [comment]
confirmed, the presence of BlankID is what is causing the error.

**Comment by cryptomail** [comment]
The regression was brought on by https://github.com/facetoe/zenpy/blob/7e3c8e87a66da33c7f51fa1cc63993d24927116f/zenpy/lib/util.py#L118
Thinking of best fix....

**Comment by cryptomail** [comment]
Would the workaround be simply to invoke ```create```?

**Comment by cryptomail** [comment]
```create``` works just fine :) 
Again I reiterate my position.  Zendesk API has a bug where the mere presence of ```id`` is the contributing factor.

**Comment by akalex** [comment]
I am afraid this workaround does not work for me.

**Comment by cryptomail** [comment]
Crafting code solution via configuration.

**Comment by cryptomail** [comment]
```
# Default
zenpy_client = Zenpy(**creds)

user1 = User(external_id=str(os.getpid()), email="at_email_" + str(os.getpid()) + "0@domain.com", name="at_email_" + str(os.getpid()) + "0@domain.com")
zd_user = zenpy_client.users.create_or_update(user1)
print(zd_user.__dict__)
```
