### ISSUE TITLE
Cache should require TTL and otherwise creates errors

### ISSUE THREAD

**Issue by jdsadow** [facetoe/zenpy#59]
calling `set_cache_implementation()` or `set_cache_max()` results in an error at https://github.com/facetoe/zenpy/blob/master/zenpy/lib/cache.py#L68 because `cachetools` expects a value for TTL but that is not specified as a requirement in the above functions

you can get it to work by adding a `**kwarg` of `ttl=N` but this should be specified

**Comment by facetoe** [comment]
Good point @jdsadow, I'll add this info to the docs.
