### ISSUE TITLE
Users incremental endpoint is missing the cursor attribute

### ISSUE THREAD

**Issue by kovaacs** [facetoe/zenpy#596]
Hello,

I'm experiencing a very similar issue to #572:
```
# works
for _ in zenpy_client.tickets.incremental(cursor="x"):
    pass

# doesn't work, but should
for _ in zenpy_client.users.incremental(cursor="x"):
    pass
```

I get `AttributeError: 'IncrementalEndpoint' object has no attribute 'cursor'`.

I think it's because here the `PrimaryEndpoint` that should be assigned to `users.incremental.cursor` is missing: https://github.com/facetoe/zenpy/blob/124cf002f71cbefd827a30bc7aa306397ee524aa/zenpy/lib/endpoint.py#L711-L713

**Comment by cryptomail** [comment]
ACK, will have a look today.

**Comment by cryptomail** [comment]
well I "fixed" it, but then it appears well.....
https://github.com/facetoe/zenpy/pull/597 is not passing CI :( 
This is due to some whacky dependency not being resolved correctly, likely another ganking of http2 assets????
Woe is me.
Oddly on a fresh python install venv it still worked for me(tm).

**Comment by cryptomail** [comment]
@kovaacs what a headache 👅 
This reminds me of 2004 DLL hell.
I think I've shored things up.
I tested locally.  Do you want to pip install -e . and give your cursor a shot on this branch?
