### ISSUE TITLE
[Feature Request] zenpy to support cache backends

### ISSUE THREAD

**Issue by akalex** [facetoe/zenpy#599]
In the era of distributed systems and cloud-native applications, Storing cache not in process memory but in some external backends like Redis, Memcached, and even databases would be very beneficial. Have you ever considered adding support for cache backends?

**Comment by cryptomail** [comment]
A good first step is to abstract the notion of a cache.  And then we can implement various implementations of that interface.  Let's first analyze how the cache is being 
1. defined
2. implemented
3. used
And then we can come up with an appropriate abstraction and configuration method.

**Comment by akalex** [comment]
I would rather start with a problem than with use cases. The problem is that if my application runs in more than one instance then using cache in its current implementation nullifies all benefits and even more it can become a huge headache.

**Comment by cryptomail** [comment]
Agreed, so a first step could be abstracting what the current caching system does and then make a "pluggable" replacement system.
Have you looked at the internals of the existing cache and considered making an interface-conforming drop in replacement?

**Comment by akalex** [comment]
I have looked a little bit. Let me take a deeper look to come up with some ideas.
