### ISSUE TITLE
Setting ticket status to "pending" but the UI creates an "open" ticket

### ISSUE THREAD

**Issue by em3697** [facetoe/zenpy#600]
Hi, I'm wondering if there is something I'm overlooking in my call to create a ticket with a "pending" status. I've read through the zenpy and Zendesk API documentation, but continue to get tickets with an "open" status instead of "pending". Any ideas would be appreciated. Is open the default and something is wrong with how I attempt to make it "pending" causing it to revert to open?
<img width="401" alt="Screenshot 2023-10-27 at 12 17 01 PM" src="https://github.com/facetoe/zenpy/assets/101139133/07c4eb00-3dbf-4295-96c2-4f4e363633f0">

**Comment by cryptomail** [comment]
@em3697 Have you tried the UI?  Is there a way to create a ticket in this status from the UI?  Let me try it myself now.  I'll also read the documentation to see if there's any wording on this.

**Comment by cryptomail** [comment]
OK the UI seemingly allows it from the onset.  Interesting.  Continuing investigation.

**Comment by cryptomail** [comment]
Let's try a CURL from https://developer.zendesk.com/api-reference/ticketing/tickets/tickets/#create-ticket

**Comment by cryptomail** [comment]
True bug:

**Comment by cryptomail** [comment]
will look into, willfix.

**Comment by cryptomail** [comment]
Wait, I just tried it with my own script and it's working!!!
What version are you using?
This created a pending ticket!
```
# Import the Zenpy Class
from zenpy import Zenpy
from zenpy.lib.api_objects.help_centre_objects import Article, Post, Comment, Section, Category, Topic
from zenpy.lib.api_objects import User, Organization, Ticket, Group, GroupMembership

# Default
zenpy_client = Zenpy(**creds)
ticket = Ticket(description="A problem occurred", subject="test pending", status="pending")
t = zenpy_client.tickets.create(ticket)
breakpoint()
print(ticket.to_json)
print(t.to_json)
```

**Comment by cryptomail** [comment]
There could be automations on your side @em3697 that are putting things back into Open status. Please let me know how you want to proceed.
Maybe give me more data?

**Comment by cryptomail** [comment]
Please look at the ticket audit history.  You can click on the event history using the little clock button.
![Screenshot 2023-10-29 at 9 17 05 AM](https://github.com/facetoe/zenpy/assets/846177/7a2e5545-2221-4038-af22-3687d1d049a8)

**Comment by em3697** [comment]
@cryptomail I'm reviewing this today - will get back to you with more info

**Comment by em3697** [comment]
> Please look at the ticket audit history. You can click on the event history using the little clock button. ![Screenshot 2023-10-29 at 9 17 05 AM](https://user-images.githubusercontent.com/846177/278883516-7a2e5545-2221-4038-af22-3687d1d049a8.png)

<img width="793" alt="Screenshot 2023-10-30 at 3 55 09 PM" src="https://github.com/facetoe/zenpy/assets/101139133/daf26f4b-2220-487e-8e5d-113e286291f3">

I see that the ticket is submitted as "Pending" and then something is overriding it to become "Open". I looked at macros, automations, and triggers but nothing seems to be changing the ticket status.

**Comment by em3697** [comment]
I've narrowed it down to an issue with the triggers that get applied after creation changing the status - I will add an action to the trigger to enforce the status. @cryptomail thanks for your help with the history feature

**Comment by wolfassi123** [comment]
> I've narrowed it down to an issue with the triggers that get applied after creation changing the status - I will add an action to the trigger to enforce the status. @cryptomail thanks for your help with the history feature

I've been trying to work with triggers, but so far, I have been unsuccessful. How did you create an action using Zenpy? There appears to be no class of the type 'Action' to pass to the Trigger Object Instance.

**Comment by em3697** [comment]
> > I've narrowed it down to an issue with the triggers that get applied after creation changing the status - I will add an action to the trigger to enforce the status. @cryptomail thanks for your help with the history feature
> 
> I've been trying to work with triggers, but so far, I have been unsuccessful. How did you create an action using Zenpy? There appears to be no class of the type 'Action' to pass to the Trigger Object Instance.

I did not use 'actions' but I used the following line to create a trigger using zenpy:

`trigger_audit = zenpy_client.triggers.create(
                        Trigger(actions=[{"field": "assignee_id", "value": curr_user_id}],
                                conditions=org_conditions,
                                active=False,
                                title=f'{curr_user_name} Trigger'
                            ))`
