### ISSUE TITLE
`TicketCursorGenerator` returns no values 

### ISSUE THREAD

**Issue by dolbinskaBW** [facetoe/zenpy#619]
We are using the `tickets.incremental` endpoint for a few years and are now looking to switch from time to cursor pagination as per Zendesk's recommendation. 

After upgrading the version to 2.0.46 and moving to `paginate_by_time = False` default we stopped getting values in the response object. After running a debugger we noted that the `_response_json` contains a non empty response with our tickets, but the `values` attribute remains `None`.  

My call:
```python
client = Zenpy(email="***", token="***", subdomain="***")

# Cursor pagination 
output = client.tickets.incremental(start_time=datetime(2024,2,6,10,0,0))
assert output.values is None
assert output._response_json is not None

# Time pagination 
output_legacy = client.tickets.incremental(start_time=datetime(2024,2,6,10,0,0), paginate_by_time = True)
assert output_legacy.values is not None
assert output_legacy._response_json is not None
```

**Comment by cryptomail** [comment]
Top priority, I'll see what I can do to debug/triage.
Sorry for any duress this has caused you.

**Comment by dolbinskaBW** [comment]
Thank you @cryptomail!

**Comment by dolbinskaBW** [comment]
Also yesterday I noted a similar issue with `client.tickets.comments` where the `_response_json` is populated, but the `values` attribute is `None` - from our testing this seemed to be an issue from release `2.0.35` and when running a debugger it  looks like the object type gets overridden at some point from `comment` to `ticket` within the results generator. Please let me know if that should be raised as a separate issue 🙇‍♀️

**Comment by cryptomail** [comment]
Very odd, because I tested tickets last night and I got results.  Can you not use values and instead use an iterator pattern?
```
for ticket in zenpy_client.tickets.incremental(start_time=datetime(2024,2,6,10,0,0)):
   print(ticket) 
```

**Comment by cryptomail** [comment]
This may get you over the bug ....but I'll look into the ```values``` thing.

**Comment by cryptomail** [comment]
BTW, I agree that values should result in the correct serialization but you do have a workaround :)
you can collect and iterate yourself as a slight detour away from this issue 😄

**Comment by cryptomail** [comment]
Update, I have reproduced your bug but I'd like confirmation that this is a minor issue that can be worked around by traversing the iterator, which is good practice.  I can see that ```values``` has not been coerced to have anything in it yet because that's only done on ```next``` (for now).  I may try to coerce the array to be populated soon :)

**Comment by cryptomail** [comment]
@dolbinskaBW Can you consume this and install zenpy locally to test this?
https://github.com/facetoe/zenpy/pull/620

**Comment by dolbinskaBW** [comment]
Hi @cryptomail, I do yes - sorry I thought the values are the easiest to communicate, but we don't actually use the `values` attribute. We do have a few layers of abstraction and we do iterate over the output eventually, but the current setup which was run for the last 2 years has stopped working after the recent upgrade.  

Our actual use case is actually based on Meltano's singer-sdk template [link](https://gitlab.com/meltano/sdk/-/tree/main/cookiecutter/tap-template)

We do eventually iterate but we were passing the response through few methods - I have now tested iterating directly after calling the API and this does seem to be working - do you know what could have caused this change? I.e. did the output object type change at any point?

**Comment by cryptomail** [comment]
> Hi @cryptomail, I do yes - sorry I thought the values are the easiest to communicate, but we don't actually use the `values` attribute. We do have a few layers of abstraction and we do iterate over the output eventually, but the current setup which was run for the last 2 years has stopped working after the recent upgrade.
> 
> Our actual use case is actually based on Meltano's singer-sdk template [link](https://gitlab.com/meltano/sdk/-/tree/main/cookiecutter/tap-template)
> 
> We do eventually iterate but we were passing the response through few methods - I have now tested iterating directly after calling the API and this does seem to be working - do you know what could have caused this change? I.e. did the output object type change at any point?

Thank you so much for explaining your use case.  I wholly acknowledge using values as a test to determine whether you SHOULD iterate or not :).

It wasn't the output that changed really...I think it was more some of the CBP code organization.
Here's my plan:
Get this and other incremental cursor changes in as you allude to.

I'll try to get some tests in there as well to ensure we have no further regressions.  Thanks for finding this.

**Comment by dolbinskaBW** [comment]
Thank you @cryptomail - in the meantime I digged through the classes and found the source  -  
from those releases the behaviour of `if response` changed in between releases - apologies I should have found this sooner!  We will amend this logic on our

**Comment by cryptomail** [comment]
@dolbinskaBW FYI, The PR is in review and will be reviewed by @Ptr314

**Comment by cryptomail** [comment]
This should be resolved :)
