### ISSUE TITLE
`Ticket.commets` return no values 

### ISSUE THREAD

**Issue by dolbinskaBW** [facetoe/zenpy#621]
After upgrading the Zenpy tap to version >=2.0.35 our singer sdk tap stopped producing values for `client.tickets.comments`. 

Similarly to [this issue](https://github.com/facetoe/zenpy/issues/619) the `values` attribute is `None`, but the `_response_json` is populated. 

I tested it after the bug fix but draft but this seem to be a different issue. 

```
client = Zenpy(email="***", token="***", subdomain="***")
output = client.tickets.comments(ticket=***)

assert output.values is None
assert len(output) == 0

assert output._response_json is not None
assert len(output._response_json) > 0
```

**Comment by dolbinskaBW** [comment]
Closing as per discussion [here](https://github.com/facetoe/zenpy/issues/619)

**Comment by cryptomail** [comment]
Yes, don't worry I'll fix it in the same issue ;)
