### ISSUE TITLE
Assignee: is not a member of the group

### ISSUE THREAD

**Issue by em3697** [facetoe/zenpy#628]
HI , I'm seeing the following error when I try to create a ticket with the following fields and can't find any documentation on how to resolve it. Any guidance would be appreciated:

zenpy_client.tickets.create(
            Ticket(
                requester_id=requester_id,
                assignee_id=assignee_id,
                subject=subject_line,
                description=ticket_descr,
                tags=tag_list,
                status='pending'))

zenpy.lib.exception.APIException: {"error": "RecordInvalid", "description": "Record validation errors", "details": {"assignee": [{"description": "Assignee: is invalid", "error": "InvalidValue"}, {"description": "Assignee: is not a member of the group"}]}}

**Comment by cryptomail** [comment]
Try setting a group id as well with 
```group_id```
And please make sure that the assignee is 
a) an agent
b) is in that group
It's clearly a validation error and if you take ZenPy out of the picture you should be able to debug even further with CURL or any other REST  library package :)
That being said, if you feel that Zenpy is somehow implicated and NOT passing the values correctly we had better talk again.

**Comment by cryptomail** [comment]
closing with no further information
