### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by facetoe** [facetoe/zenpy#63]
Update docs to reflect recent changes.

**Comment by tacobeard** [comment]
I found the object creation method listed in the documentation doesn't work:

'zenpy = Zenpy(**creds)'

However, per another users comments on ticket #44 I had success with:

'zenpy = zenpy.Zenpy(**creds)'

PS.  The error I got was the Name Error, same as in the ticket referenced above.

**Comment by facetoe** [comment]
Thanks for the heads up @tacobeard, looks like the docs are missing an import statement. The following should also work:

```python
from zenpy import Zenpy
zenpy = Zenpy(**creds)
```

I'll be sure to add this info to the docs.
