### ISSUE TITLE
TypeError to_dict() got an unexpected keyword argument 'serialize'

### ISSUE THREAD

**Issue by em3697** [facetoe/zenpy#632]
![Screenshot 2024-06-10 at 6 51 51 PM](https://github.com/facetoe/zenpy/assets/101139133/dc965ef3-a435-4efa-b24f-541539811dfa)
I'm trying to create an Organization and pass in the expected domain_names for that org, but I'm getting the error shown in the title. I'm passing in an array of strings as the data type for the domain_names. When I remove the domain_names parameter I'm successfully able to create the org so it definitely is caused by the type of the domain_names. In all the documentation I've seen that it should be an array. Any guidance on where I'm going wrong would be appreciated.

**Comment by Ptr314** [comment]
Hi!

Just tried this code and it works:

```
zenpy = Zenpy(**credentials)

org = Organization(
    name="Test org 1",
    domain_names=["123.com", "456.com"]
)

zenpy.organizations.create(org)
```

![chrome_qYWaGEi3wG](https://github.com/facetoe/zenpy/assets/14895115/a426da11-e56d-4c18-bf0b-548f59d1d939)

**Comment by em3697** [comment]
Got it thanks - I think it was saying it was an array in my IDE but was passing a pandas Series.
