### ISSUE TITLE
Missing support for guide/content_tags

### ISSUE THREAD

**Issue by almogilgil** [facetoe/zenpy#633]
The API for guide/content_tags is not implemented
Calls to guide get this error: 
An error occurred: 'Zenpy' object has no attribute 'guide'

This is the relevant API: https://developer.zendesk.com/api-reference/help_center/help-center-api/content_tags/

**Comment by cryptomail** [comment]
Any chance you'd like to have a crack at it? ^_^

**Comment by cryptomail** [comment]
@almogilgil

**Comment by almogilgil** [comment]
I’m not sure I have the proper knowledge to do it .
If you can give me some basic guidance I’m happy to try it out .

**Comment by keerthik** [comment]
I spent the afternoon figuring out how zenpy works and submitted a fix. While waiting for the PR, you can use my fork if you are familiar with how to install a local package (instead of `pip install zenpy` from official pypackage repo).

**Comment by cryptomail** [comment]
👆 New version who dis
