### ISSUE TITLE
Question: where in the ticket data structure do you find ticket attachments, and then download them.

### ISSUE THREAD

**Issue by topherchung** [facetoe/zenpy#635]
Hi,

i'm looking through the returned ticket data structure, and I don't see a field(s) that indicate that zendesk ticket has attachements, how to get the data required to retrieve them, and then download them.  Searching isn't yielding any examples, and code base isn't obvious as how to do it.

Thanks,
Chris Chung

**Comment by Ptr314** [comment]
Hi @topherchung !

Attachments belong to comments, so you need to get them - https://developer.zendesk.com/api-reference/ticketing/tickets/ticket_comments/

**Comment by wf-tchung** [comment]
Hi @Ptr314,  Thank you!
