### ISSUE TITLE
Create Examples Wiki Page

### ISSUE THREAD

**Issue by facetoe** [facetoe/zenpy#64]
Examples are handy.

**Comment by jeromemyers** [comment]
Can you provide an example of populating a custom fields in a ticket creation?

**Comment by facetoe** [comment]
Yep, sure can. I just added support for this actually, you can find a very brief example here - https://github.com/facetoe/zenpy/issues/65. 

I'll try to write some better ones this weekend.

**Comment by facetoe** [comment]
Put examples in README
