### ISSUE TITLE
New Version Not Returning Ticket field values

### ISSUE THREAD

**Issue by riley-fs** [facetoe/zenpy#641]
We recently upgraded from 2.0.24 to 2.0.46 due to cursor iteration support. After upgrading we noticed that the ticket load does not return any field values in the ticket object as it did previously in 2.0.24.

Example: Previously the `zd_client.tickets()` would return a list with the field ID and the field value but now is returning `None`. Are there additional changes that need to be made after upgrading to get the full list field values along with tickets?

Example response from 2.0.24 of the fields field on the ticket object ```'fields': [{'id': 360021810534, 'value': True}, {'id': 52025108, 'value': 'N/A'}, {'id': 46058547, 'value': None}, {'id': 114096630114, 'value': ''}, {'id': 360024577153, 'value': False},```

Example response from 2.0.46 of the fields field on the ticket object ```'fields': None```

**Comment by cryptomail** [comment]
Interesting....I will look into this.

**Comment by cryptomail** [comment]
Can't dupe.
Please post your script and or supporting data suggesting it's not working correctly.

```
# Import the Zenpy Class
from zenpy import Zenpy
from zenpy.lib.api_objects import Ticket, User

# Default
zenpy_client = Zenpy(**creds)

zendesk_ticket = int(sys.argv[1])
response = zenpy_client.tickets(id=zendesk_ticket)

print(response.to_dict())

```

Result of getting a ticket:
python get_ticket.py 34 (on my instance)
```
{'assignee_id': 26155588908179, 'brand_id': 26155621587603, 'collaborator_ids': [], 'created_at': '2024-09-13T20:25:56Z', 'custom_fields': [{'id': 26155630658963, 'value': None}, {'id': 26155656851603, 'value': None}, {'id': 33384564488723, 'value': 'chocolate'}], 'description': 'Does this come back from the API with chocolate flavour?', 'due_at': None, 'external_id': None, 'fields': [{'id': 26155630658963, 'value': None}, {'id': 26155656851603, 'value': None}, {'id': 33384564488723, 'value': 'chocolate'}], 'forum_topic_id': None, 'group_id': 26155552049811, 'has_incidents': False, 'id': 34, 'organization_id': 26155621659539, 'priority': None, 'problem_id': None, 'raw_subject': 'The flavour is NOT chocolate', 'recipient': None, 'requester_id': 26155588908179, 'satisfaction_rating': None, 'sharing_agreement_ids': [], 'status': 'open', 'subject': 'The flavour is NOT chocolate', 'submitter_id': 26155588908179, 'tags': [], 'type': None, 'updated_at': '2024-09-13T20:25:56Z', 'url': 'https://z3npuddn.zendesk.com/api/v2/tickets/34.json', 'generated_timestamp': 1726259156, 'follower_ids': [], 'email_cc_ids': [], 'is_public': True, 'custom_status_id': 26155621641107, 'followup_ids': [], 'ticket_form_id': 26155621471251, 'allow_channelback': False, 'allow_attachments': True, 'from_messaging_channel': False, 'via': {'channel': 'web', 'source': {'from_': {}, 'rel': None, 'to': {}}}}
```
The ticket I created:
<img width="1358" alt="Screenshot 2024-09-13 at 1 25 54 PM" src="https://github.com/user-attachments/assets/c9d02e6e-e281-4ea6-9af2-41b51533176f">

**Comment by cryptomail** [comment]
can't repro
