### ISSUE TITLE
Add Name to the Custom Field Spec

### ISSUE THREAD

**Issue by dolfo-fever** [facetoe/zenpy#645]
Hi team,

Thank you so much for this lib it has helped me a lot to write wrappers and webhook for Zendesk.

I want to talk about Custom Fields. According to the [spec in the Zendesk API](https://developer.zendesk.com/api-reference/sales-crm/resources/custom-fields/#json-format) it has several attributes and the one I have been having a hard time is name. 

I would like to see if we can add this attribute to the list of the `ZenpyTicket` so that it will be easier to parse what custom fields are coming. 

I can give it a go, but first I wanted to talk to you and see if this makes sense to add. 

Thank you,

**Comment by Ptr314** [comment]
Hi @dolfo-fever!

Thank you for your kind words!

I'm not sure if it is possible to be done correctly. You need to get a list of ticket fields before getting tickets. It is at least one additional API call (and more if number of fields is significant). 

Now we just do it outside of the library core, and you want to integrate it to the endpoints working with tickets? Which moment they have to be called? Each time you get a ticket? It will ruin performance and call rates. Using some kind of cache? Too complicated, I think, and may cause additional problems.

**Comment by cryptomail** [comment]
closing for now
