### ISSUE TITLE
Add support for custom fields

### ISSUE THREAD

**Issue by bdejong** [facetoe/zenpy#65]
- Go to zendesk and add a custom field in your ticket (admin > ticket fields > add custom field)
- Add a custom field and copy-paste the ID
- If you now go to the ticket view you will be able to see new fields on the left-hand side of the ticket.

You can now fill this custom field at Ticket creation by doing this API call:

```bash
curl https://[SUBDOMAIN].zendesk.com/api/v2/tickets.json -d '{"ticket": { "custom_fields": [{"id": [CUSTOM FIELD ID], "value": "HELLO"}], "requester": {"name": "John Doe", "email": "john@domain.com"}, "subject": "This is the subject!", "comment": { "body": "This is the question." }}}' -H "Content-Type: application/json" -v -u [EMAIL ADDRESS]/token:[TOKEN] -X POST
```

It would be great if zenpy supported this, perhaps as:

```python
Ticket(custom_fields=[CustomField(id=1234, value="Hello", CustomField(id=1235, value=15), CustomField(id=1236, value=datetime.now()], ...)
```

Custom fields can be strings, numbers or dates.

It does seem that it takes a while for custom fields to become "active" in the API. I.e. there is some delay between creating a custom field and actually being able to POST it via the API...

**Comment by bdejong** [comment]
Ah, they can also be bools...

**Comment by facetoe** [comment]
You should now be able to assign `CustomField` objects as described above, eg:

```python
ticket = Ticket(subject='subj', description='desc', custom_fields=[CustomField(id=41052168, value='another1')])
```

Let me know if you have any issues.

**Comment by jeromemyers** [comment]
I'm using the following call and getting "NameError: name 'CustomField' is not defined"

    tkt = Ticket(priority='high',custom_fields=[CustomField(id=22640128, value='low'),CustomField(id=71026, value='other')],subject=subjectLabel, description=descriptionContent, type='incident',assignee_id='259871026',submitter_id='259871026',requester_id='259871026', tags=tagsLabel)

**Comment by bdejong** [comment]
Hey @facetoe awesome work!

Looks like ints and bools work, dates seem to not get serialised to JSON, or at least they don't seem to be sent.

```python
custom_fields = [
    CustomField(id=30294425, value=True),  # is active
    CustomField(id=30294725, value=datetime.now()),  # joined
    CustomField(id=30153569, value=datetime.now()),  # last login
    CustomField(id=30295025, value=15),  # num sounds
    CustomField(id=30295045, value=16),  # num posts
    CustomField(id=30153729, value=17),  # num comments
]
```

All work, except the datetime fields.

**Comment by bdejong** [comment]
BTW, @jeromemyers it works just fine. You need to pip install from github, not from pypi. I.e.

```bash
pip install git+https://github.com/facetoe/zenpy.git
```

**Comment by facetoe** [comment]
Awesome @bdejong, thanks for the testing! I probably need to serialize the datetime objects explicitly to whatever format they expect before sending off to the API. I'll have a look tonight and see if I can get dates working.

**Comment by bdejong** [comment]
You need ISO 8601 dates: https://developer.zendesk.com/rest_api/docs/help_center/introduction

`date.isoformat( )` or `datetime.isoformat( )` should work.

The python datetime does not have the "Z" (as in Zulu) suffix and don't have a timezone, but with a bit of chance you don't need it. If you do then have a look at http://stackoverflow.com/a/23705687 which lists how you can get the UTC ISO date format with timezone offset.

**Comment by bdejong** [comment]
Confirmed that dates are not being sent:

u'custom_fields': [{u'id': 30294425, u'value': True}, {u'id': 30294725, u'value': **None**}, {u'id': 30153569, u'value': **None**}, {u'id': 30295025, u'value': 15}, {u'id': 30295045, u'value': 16}, {u'id': 30153729, u'value': 17}]

where I'm setting:

```python
custom_fields = [
    CustomField(id=30294425, value=is_active),  # is active
    CustomField(id=30294725, value=date_joined),  # joined
    CustomField(id=30153569, value=last_login),  # last login
    CustomField(id=30295025, value=num_sounds),  # num sounds
    CustomField(id=30295045, value=num_posts),  # num posts
    CustomField(id=30153729, value=num_comments),  # num comments
]
```

**Comment by facetoe** [comment]
As of 1918ad667222975c625fa1d2bab7276489d1fb33 `date` and `datetime` objects should be serialized and sent to the API correctly. In the case of `datetime` objects they are first converted to a `date` before being sent off. 

I also created a method `serialize` that is responsible for serializing the Python objects to JSON and made it available for troubleshooting these sorts of things. For example:

```python
from zenpy.lib.api import serialize

today = datetime.datetime.now()
ticket = Ticket(subject='subj', 
                description='desc', 
                custom_fields=[
                    CustomField(id=41222567, value=today)
                ])
ticket.requester = User(name='Bob', email='bob@facetoe.com.au', )
print serialize(ticket)
```

Let me know if you run into any trouble.

**Comment by bdejong** [comment]
Works!! 👍 

Let me know when you publish to pypi!

**Comment by facetoe** [comment]
Hi @bdejong, I just pushed a new build to Pypi.

**Comment by bdejong** [comment]
👍
