### ISSUE TITLE
Deprecation of Email & Password Authentication

### ISSUE THREAD

**Issue by tredontho** [facetoe/zenpy#651]
Zendesk is deprecating use of Email & Password auth for API calls, see the [announcement](https://support.zendesk.com/hc/en-us/articles/7386291855386-Announcing-the-deprecation-of-password-access-for-APIs)

Any examples/comments highlighting email & password for authenticating to the API should be updated, and users should be warned about the upcoming deprecation - for some accounts, this authentication method may already be disabled/unavailable.

**Comment by cryptomail** [comment]
Noted, will vector towards that 🫡

**Comment by cryptomail** [comment]
released in new version
