### ISSUE TITLE
GenericCursorResultsGenerator does not have after_cursor attribute

### ISSUE THREAD

**Issue by rkhakurelupgrade** [facetoe/zenpy#657]
I am pulling ticket audits using:

self.zenpy_client.tickets.audits(**kwargs)

and in the process of updating zenpy from version 2.0.24 to 2.0.53. I am now getting:

`AttributeError: 'GenericCursorResultsGenerator' object has no attribute 'after_cursor'`

when i try to access cursor values. Previously i used to access this attribute from the TicketCursorGenerator object. Any input on how i can continue to access cursor values while using the ticket audits endpoint?

**Comment by Ptr314** [comment]
Hi!

If you try a cursor_pagination=False parameter for this endpoint ony? I think it can help.

**Comment by rkhakurelupgrade** [comment]
@Ptr314 your suggestion is working. Thank you.
