### ISSUE TITLE
WhatsApp Integration

### ISSUE THREAD

**Issue by katerinafrid** [facetoe/zenpy#663]
Is there any way to list all comments from a ticket created via whatsapp channel?
All comments are listed in ChatStartedEvent history, making it impossible to get them directly from the ticket.

**Comment by cryptomail** [comment]
One question I have is what APIs are available to us from API/V2?
How does one get all the comments now?
What does the documentation say?  https://developer.zendesk.com/api-reference/ticketing/tickets/ticket_comments/
Is there any data coming back from that, that exposes the source channel?
If so, we're in business and there's a possibility it can be done (Either client side or server side heh)
The server side could be a longer journey, but if there's any channel indicators now, ZenPy could help facilitate it.

**Comment by Ptr314** [comment]
Hi!

Ahh, working with Sunshine Conversations is a quite tricky thing and unfortunately it's mostly not implemented in ZenPy :(

As far as I understand (we solved this problem, but maybe there is an easier way?), you need to:

1. Get a conversation_id from ticket audits (Zenpy rules)
2. List (Add, Delete etc.) messages using https://docs.smooch.io/rest/#tag/Messages (Zenpy nervously smokes on the sideline)

### Part 1. Getting conversation_id
**You need:** Zendesk API classic or OAuth token
**Endpoint:** https://developer.zendesk.com/api-reference/ticketing/tickets/ticket_audits/#list-audits-for-a-ticket
**Pseudocode:**
```
audits_found = False
audits = zenpy_client.tickets.audits(id={ticket_id})
for audit in audits:
    events = audit["events"]
    for event in events:
        if event["type"] == "ChatStartedEvent":
            conversation_id = event["value"]["conversation_id"]
            audits_found = True
if audits_found:
    # Do something with conversation_id 
else:
    # This ticket hasn't come from Sunshine Conversations
```

### Part 2: List comments
**You need:** app_id, app_key и app_secret from a Conversation API Key: https://support.zendesk.com/hc/en-us/articles/4576088682266
**Endpoint:** https://docs.smooch.io/rest/#operation/listMessages
**Code example:**
```
app_key = #####
app_secret = #####
app_id = #####
conversation_id = #####
smooch_credentials = f"{app_key}:{app_secret}"

headers = {
    "Content-type": "application/json; charset=utf-8",
    "Authorization": "Basic " + base64.b64encode(smooch_credentials)
}

smooch_conn = http.client.HTTPSConnection(f"api.smooch.io")
url = f"/v2/apps/{app_id}/conversations/{conversation_id}/messages"
smooch_conn.request("GET", url, headers=headers))
r = smooch_conn.getresponse()
if int(r.status) != 200:
    # Got error, do something with it
else:
    resp = json.loads(r.read())
    # Process messages, repeat for subsequent pages if necessary
```

I think, it would be necessary to include support for this API in Zenpy, but this is quite a big job, which I personally am not ready to undertake yet. (@cryptomail sorry :( )

**Comment by cryptomail** [comment]
Ah I see @Ptr314 ..... Yes that does seem to be a whole domain that is NOT supported by ZenPy but is supported by smooch or sunshine conversations.  Let me think through this....but as @Ptr314 showed, this is all possible outside of ZenPy and accessible via API/V2 plus smooch API.

**Comment by Ptr314** [comment]
I took the second code part from a function that doesn't use external libraries to be lighter. As I can see, there is an official Python library for conversations - https://pypi.org/project/sunshine-conversations-client/ - and using it will be a bit easier than direct calls. Examples are available on the documentation pages., i.e. right here https://docs.smooch.io/rest/#operation/listMessages

But a fly in the ointment - as I can see, it's just a simple auto-generated wrapper for urls, and it doesn't have any advanced things like transparent pagination like ZenPy has - so your code can't be as simple as ZenPy allows to have.

**Comment by cryptomail** [comment]
This is something we should work towards maybe....but I'm a bit conflicted.  ZenPy is not officially part of Zendesk and yet smooch has python bindings :) 
I'm going to close this because there are viable workarounds....but the overall question remains:  Should ZenPy work towards integrating the Smooch class of APIs into it?
I don't think that's a bad thing it's just not prioritized right now.
