### ISSUE TITLE
NameError: name 'Zenpy' is not defined

### ISSUE THREAD

**Issue by TheFoolInRed** [facetoe/zenpy#67]
This one is probably on my end, but not sure what I'm doing wrong. 

> creds = {
>     'email' : 'usingmyemailforzendesk',
>     'password' : 'andmypasswordforzendesk',
>     'subdomain': 'usingmysubdomain'
> }
> 
> zenpy = Zenpy.Zenpy(**creds)
> 
> for comment in zenpy.tickets.comments(id=86):
>     print(comment.body)

I'm getting 
    zenpy = Zenpy.Zenpy(**creds)
NameError: name 'Zenpy' is not defined

I've tried 
'zenpy = Zenpy(**creds)' as well as adding 

> from zenpy import Zenpy
> zenpy = Zenpy(**creds)

The latter gives me an error about not being able to import 'Zenpy' though I did that before setup. 

Did my pip install go awry maybe?

**Comment by facetoe** [comment]
Hi @TheFoolInRed, the code:

```python
from zenpy import Zenpy
zenpy = Zenpy(**creds)
```

Should work. Are you able to post the output of the following commands:

```bash
pip freeze | grep zenpy
python --version
pip --version
``` 

Maybe you are using a different version of Python to the one you Pip installed Zenpy to?

**Comment by facetoe** [comment]
I think you have a typo, in the code you posted zenpy is all lowercase when the class should be uppercase. For example:

from zenpy import Zenpy
  module^^           class^^

**Comment by TheFoolInRed** [comment]
Sorry about that, that was me just trying a few different things to make sure I wasn't crazy. Even with from zenpy import Zenpy it has the same 'ImportEffort: cannot import name 'Zenpy'

**Comment by facetoe** [comment]
Can you confirm that pip actually installed Zenpy correctly? Not sure how you do it on Windows.

**Comment by TheFoolInRed** [comment]
Looks like your instinct was right, my work installation of Python is hosed. Did a fresh install at home and it works like a charm. Thank you very much for the help (and awesome wrapper)!

**Comment by facetoe** [comment]
No worries @TheFoolInRed, glad it's working!
