### ISSUE TITLE
Filtering on Brands

### ISSUE THREAD

**Issue by charliemday** [facetoe/zenpy#670]
## What's happened? 

When I call the search ticket functionality and adding a brand as a search filter e.g. 

`zenpy_client.search(type="ticket", brand="Lorem")` 

It will return all the tickets associated with the brand `Lorem` _and_ any brand with the word `Lorem` in it e.g. `Lorem Ipsum`. Not sure if this is a Zenpy issue or a Zendesk one?

**Comment by cryptomail** [comment]
This will likely be a Zendesk issue.  I would advise you to try it in your live Zendesk instance and see if it returns Lorem Ipsum  from the UI there.
Also, 
Please see the documentation here: https://support.zendesk.com/hc/en-us/articles/4408886879258-Zendesk-Support-search-reference
It says:
```
A single-word search term returns a result if it appears in the data as follows:

a single word
a single word in a longer phrase
the prefix of a longer word
The search term will not return a result if it appears in the data as follows:

in the middle of a word
at the end of a word
For example, the search term "top" would match "top", "top tier", "Top Ten Trucking", "Tip-Top Mops", "Big Top Entertainment", and "Dessert Toppings, Inc". It would not match "Desktop Solutions" or "One-Stop Publishing".
```

**Comment by cryptomail** [comment]
If you still feel it's an error, please feel free to re-engage.  More than happy to go through more discernment with you.
Also....more importantly...thanks for using Zenpy, and Zendesk :) <3
