### ISSUE TITLE
Setting a timeout on requests to Zendesk's API

### ISSUE THREAD

**Issue by rishi-freshbooks** [facetoe/zenpy#68]
Hey! We are noticing that some requests to Zendesk's API will hang indefinitely. Would you be able to modify your zendesk client to allow for the setting of a timeout? I am not sure at what level the timeout should be applied, but here are a couple of ideas:
- Global timeout on the Zenpy object, for example:
```python
zenpy = Zenpy(**creds, timeout=<int>)
```
- timeout keyword argument on the method, for example:
```python
zenpy.users.create_or_update(zenpy_user, timeout=<int>)
```

What do you think?

**Comment by facetoe** [comment]
Hey @rishi-freshbooks, sure I'm happy to look into it, and I think the global timeout would be easiest to implement. Do you know where exactly it hangs? Are you able to provide a stack trace?

**Comment by rishi-freshbooks** [comment]
Hey @facetoe, since it hangs infinitely, it never errors out and does not print a stacktrace. However,    this is what the TCP connection looks like:
```
python2.7 24686 fb    5u  IPv4          381714646      0t0       TCP fb:58752->proxy.vip.pod6.iad1.zdsys.com:https (ESTABLISHED)
```
the connection is established but the python process is blocking on read to that TCP connection.

Does this help?

**Comment by rishi-freshbooks** [comment]
Hey @facetoe, do not mean to pester you about this, but it is has come up a few more times since. Let me know if I can lend a hand. Thanks!

**Comment by facetoe** [comment]
All good @rishi-freshbooks, I've been meaning to get to it but am really busy at the moment. With any luck I can have a look tonight!

**Comment by facetoe** [comment]
Hey @rishi-freshbooks, I've had a look and it is easy enough to add a timeout, however it will take a little refactoring to do it cleanly. I've got around halfway so with any luck will be able to have a branch for you to test by the end of the week.

**Comment by facetoe** [comment]
Hey @rishi-freshbooks, I've written an initial implementation of the timeout feature, are you able to test it out and see if it solves your problem? 

Currently I just let the exception thrown by Requests bubble up uncaught however I could wrap this if it's more convenient to catch. 

Let me know if you have any issues!

**Comment by rishi-freshbooks** [comment]
@facetoe wow that's great! Thank you for getting to this quickly. Unfortunately I will not be able test this out unless it is versioned and published to pypi.

Would you be able to cut a version? Do you think there are any regressions with these changes?

**Comment by facetoe** [comment]
Hey @rishi-freshbooks, it is possible these changes introduced regressions as they involved  a fairly major refactor under the hood. I wish I had tests to put my mind at ease! 

If you are unable to take this new version for a test drive I can perform some more extensive testing and release it as a version. I should be able to get that done in the next day or two.

**Comment by rishi-freshbooks** [comment]
Hey @facetoe, I can certainly wait a few days. Thanks again for your quick help on this.

**Comment by facetoe** [comment]
@rishi-freshbooks, I've pushed a new version to Pypi. You can now specify a global timeout value when you instantiate `Zenpy` with the default being 60 seconds. 

 Let me know if you have any issues!

**Comment by rishi-freshbooks** [comment]
Thank you so much!
