### ISSUE TITLE
SearchEndpoint kwargs bug

### ISSUE THREAD

**Issue by radalin** [facetoe/zenpy#69]
I found a few bugs regarding the SearchEndpoint parsing keyword arguments.

When I want to execute such a query:

`zenpy_client.search(
                type="ticket",
                updated_greater_than=last_fetch_time
                sort_by="id",
                sort_order="asc"
            )
`

where last_fetch_time is a datetime field
We are stuck in the elif clause:

`elif isinstance(value, datetime):
`

which is kind of wrong, because the if clause there is actually about keys and not the values. A similar problem arises in the 

`elif isinstance(value, list):
`

and

`elif isinstance(value, list) and key == 'ids':
`

the second clause is probably never executed because it enters the first if clause.

A workaround to bypass this datetime problem is to call the search method this way:

`zenpy_client.search(
                type="ticket",
                updated_greater_than=last_fetch_time.strftime("%Y-%m-%d")
                sort_by="id",
                sort_order="asc"
            )
`

which will work as expected as we are bypassing the datetime check.

**Comment by facetoe** [comment]
Thanks for the bug report @radalin. The code in the SearchEndpoint is not pretty, I think I'll rewrite it this weekend and try to do a better job of it!

**Comment by radalin** [comment]
If you require minute precision for your time. you have to use an iso format, which will convert the datetime to something like this: "2016-10-03T15:23:48+00:00". The problem comes when you want to use "+" with type parameter which turns your request to something like this:
`search.json?query=updated>2016-10-03T15:23:48+00:00+type:"ticket"&sort_order=asc&sort_by=id`

But as "+" is special to define the type parameter you have to encode "+" as "%2B" which will turn the request url as followed:
`search.json?query=updated>2016-10-03T15:23:48%2B00:00+type:"ticket"&sort_order=asc&sort_by=id`

There is no way to avoid sending the timezone parameter i suppose, unfortunately datetime.isoformat function's output is not on the desired output so something custom might be required (default isoformat also outputs microtime which is not valid for zendesk).

That's what I found so far. I will let you know if I find anything else.

**Comment by radalin** [comment]
>  "2016-10-03T15:23:48+00:00"
A correction on the above format (which converts my previous post to nonsense) is that you can use: "2016-10-03T15:40:48Z" which is easier and returns the correct results. This means your time should be in UTC timezone though so be careful when you are using it.

**Comment by facetoe** [comment]
Hey @radalin, I fixed the datetime bug. I ended up just converting to a date only and sending that to the API as I don't think the time information is used by Zendesk Search API. You can still pass a datetime string and it will be sent along.
