### ISSUE TITLE
Upload attachment by file content

### ISSUE THREAD

**Issue by onyb** [facetoe/zenpy#72]
I can imagine that something like this would be very useful, if we we don't have an actual file stored somewhere.

```py
zenpy.attachments.upload(content=some_binary_data, target_name='some.pdf')
```

What do you think about this? Maybe we can add `content` as an optional parameter, or even go for a new method like `upload_content(..)`.

**Comment by facetoe** [comment]
Zenpy just passes the file object to the `requests` library as the `data` parameter. Here are their docs for that parameter:

```
data -- (optional) Dictionary, bytes, or file-like object to send in the body of the Request.
```

Based on this I believe you should be able to pass any of these objects to the `attachments.upload` method as the `data` parameter and it _should_ be uploaded to Zendesk. 

Let me know if this works and I'll add it to the docs!

**Comment by facetoe** [comment]
My bad, looks like Zenpy accepts a path and not a file object. I can refactor this method to accept either a filepath or any of the objects accepted by requests for upload.

**Comment by onyb** [comment]
@facetoe I just created PR #73 which adds this feature. Could you please review it?
