### ISSUE TITLE
Merge Users endpoint

### ISSUE THREAD

**Issue by ravangen** [facetoe/zenpy#74]
Provide the ability to merge one user into another. See https://developer.zendesk.com/rest_api/docs/core/users#merge-users

Looks pretty straightforward to implement as the payload is just a user id.

I may be able to give this a go in the coming couple of weeks, but I am not sure how you normally test the package beyond manually.

**Comment by facetoe** [comment]
Hi @ravangen, yes this looks easy enough to implement. I currently only test the package manually.

**Comment by facetoe** [comment]
@ravangen, I've added support for merging users (http://docs.facetoe.com.au/zenpy.html#merge). Let me know if you have any trouble with the new feature.

**Comment by ravangen** [comment]
Thanks!!!

I haven't verified, but I think the `dest_user` could also accept an `id` instead of a full User object.

**Comment by facetoe** [comment]
No worries! It does seem likely that the dest user could accept an id. I'll see if this works and update the method if it does.

**Comment by facetoe** [comment]
Done in 27206f444fec743451cddb9dbe885485473b24eb

**Comment by ravangen** [comment]
Awesome 👍
