### ISSUE TITLE
User-Agent version does not match package version

### ISSUE THREAD

**Issue by ravangen** [facetoe/zenpy#75]
Version information is stored in three places, but not always in sync. Maybe centralize this information into one place that can be referenced?

https://github.com/facetoe/zenpy/blob/1.1.6/setup.py#L7
https://github.com/facetoe/zenpy/blob/1.1.6/docs/conf.py#L70
https://github.com/facetoe/zenpy/blob/1.1.6/zenpy/__init__.py#L274

**Comment by facetoe** [comment]
Yes this is a bit annoying. I'll have a look at centralizing this info when I get the chance.
