### ISSUE TITLE
Create ticket with new requester

### ISSUE THREAD

**Issue by evilskater** [facetoe/zenpy#78]
I'm getting this error while I'm creating a ticket with a new requester

```
>>> requester = { "name": "foo", "email": "email@foo.bar" }
>>> new_ticket = Ticket(subject=subject, description=description, requester=requester)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/zenpy/lib/api_objects.py", line 3376, in __init__
    setattr(self, key, value)
  File "/usr/local/lib/python2.7/dist-packages/zenpy/lib/api_objects.py", line 3563, in requester
    self.requester_id = requester.id
AttributeError: 'dict' object has no attribute 'id'
```

I checked the API and there is no object named Requester... only a property of Request.
Am I doing something wrong or there is no support for this action at the moment?

PS: It works via Zendesk Rest API:
https://developer.zendesk.com/rest_api/docs/core/tickets#creating-a-ticket-with-a-new-requester

**Comment by facetoe** [comment]
Hi @evilskater, a requester is a `User`, so the following code should work:

```python
zenpy.tickets.create(
    Ticket(
        description='Example', 
        requester=User(name='bob', email='bob@example.com')
    )
)
```

I believe the User must already exist in Zendesk. 

The Exception you are getting is because you are passing a dictionary to the `Ticket` object instead of a the expected `User` object.

**Comment by facetoe** [comment]
If that works for you I'll add it to the examples as it seems like it would be a common use case.

**Comment by evilskater** [comment]
Hi @facetoe, Thanks for the fast reply.
Yep! that's what I was looking for. I'm gonna test if it creates a new user if it doesn't exist in ZenDesk.

**Comment by evilskater** [comment]
It worked fine! Thanks @facetoe!

I think that it would be nice if this could be inserted into Docs for future searches.

**Comment by facetoe** [comment]
OK cool, I'll add it to the docs.
