### ISSUE TITLE
zenpy.tickets.update(tkt) does not return a TicketAudit object

### ISSUE THREAD

**Issue by anvisha** [facetoe/zenpy#80]
It looks like, when you call zenpy.tickets.update(ticket) -- it returns a Response type object and not a TicketAudit.

**Comment by facetoe** [comment]
Hi @anvisha, I just found and fixed this bug in ff55fe547a38a439e28cb88b981292ec769e31c7. I plan to push a new release in the next few days, however the fix is in master now if you want to to get your hands on it earlier!

**Comment by anvisha** [comment]
Hi @facetoe - any updates on when the release is going to happen? Thanks!

**Comment by facetoe** [comment]
I'll try to push one tonight!

**Comment by facetoe** [comment]
Sorry it took so long @anvisha, I've been crazy busy! Just pushed 1.1.17 which contains the fix for the update method.
