### ISSUE TITLE
Read a ticket's comments is broken

### ISSUE THREAD

**Issue by fenollp** [facetoe/zenpy#85]
Hey,

I can get this sample code (from the RST file) to work:

```python
for comment in zenpy.tickets.comments(id=86):
    print comment.body
```

I'm using Python3 & zenpy 1.1.7 installed using pip3 on ubuntu 16.10.

I get this error:

```
>>> ID = 25913
>>> zenpy.tickets.comments(id=ID)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: comments() got an unexpected keyword argument 'id'
```

**Comment by facetoe** [comment]
Hey @fenollp, I'll need to update the examples as many of these second level endpoints have had the id parameter renamed to be a bit more descriptive. Try this:

```python
for comment in zenpy.tickets.comments(ticket_id=3):
    print(comment.body)
```

**Comment by fenollp** [comment]
Dang, how did I miss that in the code...

**Comment by facetoe** [comment]
All good, the example was doing it's best to trick you! I've updated them now so noone else will suffer the same fate. Thanks for reporting the issue!

**Comment by zenahirsch** [comment]
I'm receiving the following error:

`TypeError: comments() got an unexpected keyword argument 'ticket_id'`

When I execute the following:

`comments = zenpy_client.tickets.comments(ticket_id=ticket.id)`

**Comment by facetoe** [comment]
FYI, it also accepts a Ticket:

```python
for ticket in zenpy_client.tickets():
    for comment in zenpy_client.tickets.comments(ticket):
        print(comment)
```
