### ISSUE TITLE
IncrementalEndpoint start_time arg for timezone aware datetime

### ISSUE THREAD

**Issue by ravangen** [facetoe/zenpy#86]
When providing a timezone aware datetime for `start_time` to `IncrementalEndpoint`, an incorrect value is sent to Zendesk when the systems local timezone does not match the datetime's timezone. This is highlighted in http://stackoverflow.com/a/11743262 and J.F. Sebastian's comment there.

Line affected: https://github.com/facetoe/zenpy/blob/1.1.7/zenpy/lib/endpoint.py#L120

Demo of problem
```python
import pytz
from datetime import datetime, timedelta

# create a shared reference point
start_time = datetime.now()

# by assigning timezone, its actually provides a different meaning to the time
utc_start_time = start_time.replace(tzinfo=pytz.timezone('UTC'))
eastern_start_time = start_time.replace(tzinfo=pytz.timezone('US/Eastern'))
assert utc_start_time != eastern_start_time  # passes
assert (utc_start_time - eastern_start_time) != timedelta(0)

# NOTE: my system timezone is US/Eastern, so the epoch_eastern_start_time is actually the correct value
epoch_utc_start_time = utc_start_time.strftime("%s")
epoch_eastern_start_time = eastern_start_time.strftime("%s")
assert epoch_utc_start_time != epoch_eastern_start_time  # fails
```

Workaround: Calculate `start_time` yourself correctly such that a datetime object isn't provided

**Comment by facetoe** [comment]
Thanks for the bug report @ravangen! Would another option be to explicitly convert the datetime object to UTC time before sending to Zendesk (it looks like they use UTC - https://developer.zendesk.com/rest_api/docs/core/introduction#time-stamps)?

I guess this issue is exists anytime a datetime object is sent to the API...

**Comment by ravangen** [comment]
The [Incremental export start time](https://developer.zendesk.com/rest_api/docs/core/incremental_export#start-time) uses Unix epoch time (from UTC). The actual problem is that `strftime("%s")` uses the systems timezone regardless of what timezone the datetime could have.

> Python doesn't actually support %s as an argument to strftime (if you check at http://docs.python.org/library/datetime.html#strftime-and-strptime-behavior it's not in the list), the only reason it's working is because Python is passing the information to your system's strftime, which uses your local timezone.

**Comment by facetoe** [comment]
> Python doesn't actually support %s as an argument to strftime 

Wow that's quite a gotcha! 

I'll look into this tonight.

**Comment by facetoe** [comment]
Sorry it took so long to get to this one @ravangen. I think the fix in 8a135b0 should ensure that the datetime's timezone is used as expected.

**Comment by ravangen** [comment]
Thanks for looking into this. I believe there is still a bug here though.

When `kwargs['start_time']` is a timezone aware datetime (has `tzinfo`), you should be converting the datetime to the UTC timezone before using `timetuple()`. The problem is that `timetuple` does not do timezone conversions automatically so you are losing information here.

Suggested solution (since the package includes `python-dateutil`):
```python
from dateutil.tz import tzutc
time.mktime(kwargs['start_time'].astimezone(tzutc()).timetuple())
```

When `kwargs['start_time']` is a naive datetime, there is nothing much you can do except hope it is UTC.

**Comment by facetoe** [comment]
Thanks @ravangen, for some reason I tried to solve the `%s` unixtime formatting issue instead of the timezone issue...

Can you see any problems with this approach:

```python

def is_timezone_aware(datetime_obj):
    """
    Determine whether or not a given datetime object is timezone aware.
    """
    return datetime_obj.tzinfo is not None and datetime_obj.tzinfo.utcoffset(datetime_obj) is not None

....

        if isinstance(start_time, datetime):
            if is_timezone_aware(start_time):
                start_time.astimezone(tzutc())
            else:
                log.warning(
                    "Non timezone-aware datetime object passed to IncrementalEndpoint. "
                    "The Zendesk API expects UTC time, if this is not the case results will be incorrect!"
                )
            unix_time = time.mktime(start_time.timetuple())
        else:
            unix_time = start_time
```

**Comment by ravangen** [comment]
You want `start_time = start_time.astimezone(tzutc())` but the rest seems fine 👍

**Comment by facetoe** [comment]
Gah, of course... Thanks!

**Comment by snexus** [comment]
Hey @facetoe - think there is still a bug converting the timezones. 

Referring to the same code - you are using time.mktime(..) after converting to UTC, but time.mktime assumes local time, not the UTC one. As a result start_time which is passed  to incremental endpoint is wrong (depends on local time). 

The solution would be using calendar.timegm(..) instead? See https://stackoverflow.com/questions/2956886/python-calendar-timegm-vs-time-mktime

Thank you

**Comment by ravangen** [comment]
I believe @snexus is correct. If you have an datetime that is not timezone aware, the question is should the system assume `start_time` is the local time or the utc time. 

Given the log warning message includes `... The Zendesk API expects UTC time, if this is not the case results will be incorrect!`, I would think `start_time` should be assumed to be UTC where `calendar.timegm` looks like the correct function to use.

**Comment by facetoe** [comment]
Yep, makes perfect sense.
