### ISSUE TITLE
Support filters for Satisfaction Ratings. 

### ISSUE THREAD

**Issue by Heisenberg815** [facetoe/zenpy#87]
Hi,

It seems that it isn't possible to provide a filter such as `score=good` to the `satisfaction_ratings` endpoint. More precisely, I am not able to make the  `/api/v2/satisfaction_ratings.json?score=good`
api call with Zenpy.  It seems that `PrimaryEndpoint` instances do not support this kind of filters. Is there a good reason for that? Otherwise, could we implement this?

Thanks

**Comment by facetoe** [comment]
Hi @Heisenberg815, yes this looks to be an oversight when I implemented SatisfactionRatings. I'll look at adding the ability to specify filters as soon as I get the chance.

**Comment by facetoe** [comment]
Hi @Heisenberg815, 

You should now be able to filter Satisfaction Ratings like so:

```python
for s in zenpy.satisfaction_ratings(sort_order='desc', score='good'):
    print(s)
```

**Comment by Heisenberg815** [comment]
Hi @facetoe, thanks for your reactivity!

**Comment by facetoe** [comment]
No worries @Heisenberg815!
