### ISSUE TITLE
zenpy re-mounting the https transport breaks requests_toolbelt's monkeypatch for Google Appengine

### ISSUE THREAD

**Issue by cdman** [facetoe/zenpy#91]
Apparently zenpy remounts the HTTPS transport on whatever requests session it gets:

From https://github.com/facetoe/zenpy/blob/master/zenpy/__init__.py#L46

```python
# Workaround for https://github.com/kennethreitz/requests/issues/2364
session.mount('https://', HTTPAdapter(max_retries=3))
```

This prevents the correct working on Google Appengine, even if requests_toolbelt monkeypatch is used (see https://toolbelt.readthedocs.io/en/latest/adapters.html#appengineadapter). This in turn results in a lot of connection errors when running in Google Appengine standard environments:

```
*** ConnectionError: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='[redacted]', port=443): Max retries exceeded with url: /api/v2/search.json[redacted] (Caused by ProtocolError('Connection aborted.', error(13, 'Permission denied')))",),)
```

The workaround is to redefine what HTTPAdapter is for zenpy after importing it.

```python
zenpy.HTTPAdapter = requests_toolbelt.adapters.appengine.AppEngineAdapter
```

**Comment by cdman** [comment]
One idea would be to check the current adapter for HTTPS before re-mounting it and raise an exception (or just issue a warning) if it isn't request.HTTPAdapter?

**Comment by facetoe** [comment]
Yes that makes sense, I'll only remount if it is a HTTPAdapter and log if it it isn't. 

Thanks for the report!

**Comment by sigmavirus24** [comment]
Due to inheritance, *most* adapters will be an instance of `HTTPAdapter`. If you do 

```py
class Foo(HTTPAdapter):
    pass

f = Foo()
print(isinstance(f, HTTPAdapter))
```

You'll see `True`.

**Comment by facetoe** [comment]
Ahh good point @sigmavirus24. Can you see any issue with the following code?:

```python
adapter = session.get_adapter('https://')
if adapter.__class__ is HTTPAdapter: 
    # do things...
```

I'm not that familiar with requests internals to be honest.

**Comment by sigmavirus24** [comment]
If you're checking `__class__` you may as well do `type(adapter)` to get the same information. Still, requests-toolbelt *does* monkey patch both `sessions.HTTPAdapter` and `adapters.HTTPAdapter` (I suspect that you import HTTPAdapter here and then the monkey-patch function is called so the HTTPAdapter class here is not being replaced.) So if someone monkey patches first, then imports zenpy then this will be checking the wrong thing (because everything will default to a Google App Engine friendly adapter and you'll be checking against that). I think what you *actually* want is to take a parameter, e..g, `adapter_class` that defaults to `requests.adapters.HTTPAdapter` and you document that you will always replace the `https://` adapter with whatever is passed to that argument. That allows users to specify what adapter they want you to use and you get to configure the retries.

Alternatively, you could provide some function that provides keyword arguments that users should instantiate their adapters with, e.g.,

```
class Foo(HTTPAdapter):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault('max_retries', 10)
        super(Foo, self).__init__(self, *args, **kwargs)

import zenpy.utils
f = Foo(**zenpy.utils.get_adapter_args())
session = requests.Session()
session.mount('https://', f)
# pass session into zenpy
```

Make sense?

**Comment by cdman** [comment]
@sigmavirus24 - request-toolbelt patches both `sessions.HTTPAdapter` and `adapters.HTTPAdapter` only in master. The currently released version (0.7.0) only patches `sessions.HTTPAdapter`, hence this issue. Given the new information I think the correct solution would be:

- wait for a new release of requests-toolbelt and upgrade to it
- for other, similar situations (where the default adapter class isn't user): as @sigmavirus24 suggested, for zenpy to provide an `adapter_class` parameter in the client `__init__` method which defaults to `requests.adapters.HTTPAdapter` but can be customized. (and then, when re-mounting the transport do something like `session.mount('https://', self.adapter_class(max_retries=3))`)

If the above are implemented, we no longer need to play around with the classes of the adapters.

**Comment by sigmavirus24** [comment]
FYI, http://www.coglib.com/~icordasc/blog/2017/01/some-better-practices-for-using-requests-in-api-clients.html might help you with designing this

**Comment by facetoe** [comment]
Thanks @sigmavirus24, much appreciated!

**Comment by facetoe** [comment]
Thanks for your help with this @cdman, @sigmavirus24. If you could cast your eyes over my solution in b7fae7b943e8d6a77d1919586960854a4c55a7ac and let me know if you see any problems with my approach it would be much appreciated. I've also documented how users can provide their own adapters in aee901cbe6f330c6ef60353301e6feb8cea95a6a.

**Comment by sigmavirus24** [comment]
@facetoe this looks good to me! Hopefully @cdman can test this and assert it works for them as well. =)

**Comment by cdman** [comment]
@facetoe @sigmavirus24 - thank you for the fast and continuous updates!

Yes, that change would work for me (as would having an updated release of requests-toolbelt - pretty please :smile:).

However, @facetoe I would have two observations regarding b7fae7b943e8d6a77d1919586960854a4c55a7ac:

- it removes the comment which indicates the reasoning behind re-mounting the HTTPS adapter and I think we should leave it in since it is a tricky and not-evident-on-first-look kind of code (also, it would be probably better to reference https://github.com/kennethreitz/requests/issues/3661 in the comments rather than https://github.com/kennethreitz/requests/issues/2364 since I didn't understand much from the first one).

- we should update the documentation saying that "if you *do* pass in a custom session object make sure to mount the HTTPS transport with these options because of reasons ..."

**Comment by facetoe** [comment]
Thanks @cdman, I've added some comments to provide the reasoning for remounting the HTTPAdapter. With the docs, I've provided an example of how users can take advantage of the defaults Zenpy provides in aee901cbe6f330c6ef60353301e6feb8cea95a6a. 

I'm going to go ahead and merge these changes. Let me know if you have any further issues or suggestions!
