### ISSUE TITLE
Consider using something other than `zenpy` for the client in the examples

### ISSUE THREAD

**Issue by cdman** [facetoe/zenpy#92]
Currently the example in the README is something like:

```python
from zenpy import Zenpy
zenpy = Zenpy(**credentials)
# ... later down
zenpy.users.update(...)
```

However I'm using like this:

```python
import zenpy
client = zenpy.Zenpy(**credentials)
```

So when I've read `zenpy.users.update`, I just assumed that the `zenpy` module had a `users` field on it (or perhaps there was a `zenpy.users` module). To make it more clear, perhaps change `zenpy = Zenpy(**credentials)` into `client = Zenpy(**credentials)` (or `zenpy_client`).

**Comment by facetoe** [comment]
Yes I agree this is confusing, I'll fix up the docs. Thanks for the suggestion!
