### ISSUE TITLE
Unable to create an attachment

### ISSUE THREAD

**Issue by rtkghesselink** [facetoe/zenpy#94]
I'm using zenpy like so:
`self.client.attachments.upload(filename)`
and I'm getting an error back as so:
`HTTPError(u'400 Client Error: Bad Request for url: https://subdomain.zendesk.com/api/v2/uploads.json?&filename=/tmp/report-foo.pdf',))`

Its not obvious to me what the problem is as this seems to correlate to Zendesk API documentation. Any help on this would be greatly appreciated.

Additionally, running it through requests seems to work:
`>>> r = requests.post("https://subdomain.zendesk.com/api/v2/uploads.json?filename=\"foo.pdf\"", data="/tmp/report.pdf", auth=(username, password))
>>> print r.content
{"upload":{"token":"XdzLbEx0XYGJfOuV2MuVQ0TlN",....
>>> print r.ok
True`

**Comment by facetoe** [comment]
Interesting, I'm unable to reproduce this error. Are you able to upload a simple text file? How large is this PDF? What is the result of running `type(filename)`? What is the result of running `file /tmp/report-foo.pdf` in the shell?

**Comment by rtkghesselink** [comment]
Hi, thanks for the quick reply! I've tried changing it to text but still get the 400 error:
`file /tmp/report-awn.txt
/tmp/report-awn.txt: ASCII text`
output of type: 
`<type 'file'>`

resulting error:

Exception: ('Unable to create Ticket to Zendesk', HTTPError(u'400 Client Error: Bad Request for url: https://subdomain.zendesk.com/api/v2/uploads.json?&filename=/tmp/report-awn.txt',))

I think the issue is that the & follows the uploads.json? 
Since I'm not passing a token,  I think this might work in endpoint.py:
self.endpoint + urllib.urlencode(kwargs)

**Comment by rtkghesselink** [comment]
Further to this, attaching a pdf of 55K shows up as 23 bytes. Again, I don't quite understand:
````
f = os.stat(filename)
f.st_size
522647
with open(filename, 'r') as report_file:
        created_attachment = self.client.attachments.upload(filename, target_name=target_name)...[[Attachment(id=3988343383)],....,u'content_type': u'application/pdf', u'inline': False, u'id': 3988343383, u'size': 23}]]
```

**Comment by facetoe** [comment]
I don't think the issue is the `&` symbol as I am able to upload attachments without error. Can you post a minimal example that triggers the error? I am still unable to reproduce it.

**Comment by rtkghesselink** [comment]
I can no longer reproduce the problem. Thanks for the assistance.

**Comment by facetoe** [comment]
Ahh cool, let me know if you have any more trouble.
