### ISSUE TITLE
Add create_or_update organization to the API

### ISSUE THREAD

**Issue by rishi-freshbooks** [facetoe/zenpy#95]
Hey! Hope you are well.

Zendesk's API nows support create_or_update organization https://developer.zendesk.com/rest_api/docs/core/organizations#create-or-update-organization which is major improvement as it will eliminate the need to first check if the organization exists before creating or updating it.

Do you think you can support in your library? It would be a huge win for us.

Thanks!
Rishi

**Comment by facetoe** [comment]
Yup, not a problem @rishi-freshbooks. I'll add support for this as soon as I get a chance.

**Comment by facetoe** [comment]
HI @rishi-freshbooks, I've added support for create_or_update Organizations and pushed a new version!

**Comment by rishi-freshbooks** [comment]
Wow that was fast! Thank you!

**Comment by facetoe** [comment]
No worries!
